force-app/main/default/objects/CWS_Distributor_Reseller__c/CWS_Distributor_Reseller__c.object-meta.xml
<CustomObject>
    <description>This is the Object to maintain the Relationship between the Distributor/Reseller and the End Customer Account.</description>
    <label>Distributor/Reseller</label>
    <nameField>
        <label>Distributor/Reseller  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributors/Resellers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CWS_Distributor_Reseller__c/fields/CWS_Account__c.field-meta.xml
<CustomField>
    <fullName>CWS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account of the End Customer/Customer Account linked to the Distributor/Reseller.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Distributors/Resellers</relationshipLabel>
    <relationshipName>Distributors_Resellers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CWS_Minimum_Commit__c/CWS_Minimum_Commit__c.object-meta.xml
<CustomObject>
    <label>Minimum Commit</label>
    <nameField>
        <displayFormat>MIN-{000000}</displayFormat>
        <label>Minimum Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Minimum Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CWS_Minimum_Commit__c/fields/CWS_Account__c.field-meta.xml
<CustomField>
    <fullName>CWS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Minimum Commits</relationshipLabel>
    <relationshipName>Minimum_Commits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CWS_Minimum_Commit__c/fields/CWS_Month_Year__c.field-meta.xml
<CustomField>
    <fullName>CWS_Month_Year__c</fullName>
    <inlineHelpText>Field value format (MMM-YY)</inlineHelpText>
    <label>Month Year</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CWS_Minimum_Commit__c/fields/CWS_Monthly_Minimum_Commit__c.field-meta.xml
<CustomField>
    <fullName>CWS_Monthly_Minimum_Commit__c</fullName>
    <label>Monthly Minimum Commit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CWS_Minimum_Commit__c/fields/CWS_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>CWS_Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Minimum Commits</relationshipLabel>
    <relationshipName>Minimum_Commits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>CWS_Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Captures the Bill To Account associated to this Opportunity.</inlineHelpText>
    <label>Bill To (Account)</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>$Source.CWS_Route_to_Market__c</field>
            <operation>equals</operation>
            <value>Channel</value>
        </filterItems>
        <filterItems>
            <field>Account.CWS_Is_Distributor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Bill - To Account)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Master__c.field-meta.xml
<CustomField>
    <fullName>CWS_Master__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This indicates that the opportunity will have the legacy model of minimum commitment maintained as $value at Account level. This is not recommended; please contact System Administrator for help.</inlineHelpText>
    <label>Master?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <inlineHelpText>Captures the prospect&apos;s route to market; used for routing to BDR and PSE/SE pools.</inlineHelpText>
    <label>Route to Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Store_Bill_To_Id__c.field-meta.xml
<CustomField>
    <fullName>CWS_Store_Bill_To_Id__c</fullName>
    <inlineHelpText>Captures the Bill To ID for this Opportunity.</inlineHelpText>
    <label>Store Bill To Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CWS_MinCommitUploadCtrl_Test.cls
/*Class Name: CWS_MinCommitUploadCtrl_Test
*Description: Test Class for CWS_MinCommitUploadCtrl
*Created By: Ankit
*Created On: 6/24/2020
*Modification Log
*------------------------------------------------------------------------------------------
*Developer              Date            User Story              Description
*------------------------------------------------------------------------------------------
*Ankit                 06/24/2020        BED-8615            Initial Version
*/

@isTest(SeeAllData=false)
public class CWS_MinCommitUploadCtrl_Test{

   @testSetup static void createTestData(){
        //create custom setting data
        CWS_UTLDataFactory.insertTriggerSwitch(new List<String>{'CWS_Distributor_Reseller__c','Quote','SBQQ__QuoteDocument__c'});    
        
        //Create Sold TO Account
        Map<String, Object> soldtoaccountFieldValues=new Map<String, Object>{
            'SBQQ__PriceHoldEnd__c'=>Date.ValueOf('2020-01-01'),
            'currencyIsoCode'=>'EUR'};
        Account soldtoaccount=CWS_UTLDataFactory.createAccount('TestAccount', soldtoaccountFieldValues,true);
        
        
        Opportunity opp = CWS_UTLDataFactory.createOpportunity('optyName',soldtoaccount.Id, new Map<String, Object>{'CloseDate'=>System.today(),'CWS_Bill_To_Account__c'=>soldtoaccount.Id,'CWS_Route_to_Market__c'=>'Direct','CWS_Store_Bill_To_Id__c' => soldtoaccount.Id,'CWS_Master__c' => true}, true);
        
   }
   
    @isTest static void testMethod1(){

        Test.starttest();
        
        list<Opportunity> oppObj = [Select id from opportunity limit 1];
        list<Account> accObj = [Select id from Account limit 1];
        
        CWS_Minimum_Commit__c minCom = new CWS_Minimum_Commit__c();
        minCom.CWS_Account__c = accObj[0].id;
        minCom.CWS_Opportunity__c = oppObj[0].id;
        minCom.CWS_Monthly_Minimum_Commit__c = 10000;
        minCom.CWS_Month_Year__c = 'Jan-20';
        
        CWS_MinCommitUploadCtrl.insertMinCommits(new list<CWS_Minimum_Commit__c>{minCom});
        CWS_Minimum_Commit__c minComObj = [Select id,CWS_Month_Year__c from CWS_Minimum_Commit__c limit 1];
        system.assertEquals('Jan-20',minComObj.CWS_Month_Year__c);
        
        CWS_Minimum_Commit__c minCom1 = new CWS_Minimum_Commit__c();
        minCom1.CWS_Account__c = accObj[0].id;
        minCom1.CWS_Opportunity__c = oppObj[0].id;
        minCom1.CWS_Monthly_Minimum_Commit__c = 10000;
        minCom1.CWS_Month_Year__c = 'Jan-20';
        
        try{
            CWS_MinCommitUploadCtrl.insertMinCommits(new list<CWS_Minimum_Commit__c>{minCom1});
        }Catch(Exception e){
            list<CWS_Minimum_Commit__c> minComObjList = [Select id,CWS_Month_Year__c from CWS_Minimum_Commit__c where CWS_Month_Year__c = 'Jan-20'];
            system.assertEquals(1,minComObjList.size());
        }
        
        
        Test.stopTest();
    }
}