force-app/main/default/objects/Contract/fields/CWS_Distributor_Category__c.field-meta.xml
<CustomField>
    <fullName>CWS_Distributor_Category__c</fullName>
    <label>Distributor Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Master__c.field-meta.xml
<CustomField>
    <fullName>CWS_Master__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Contracts with Master? as TRUE, indicates only legacy records with $value for commitment.</description>
    <inlineHelpText>Contracts with Master? as TRUE, indicates only legacy records with $value for commitment.</inlineHelpText>
    <label>Master</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_Quote_Type__c</fullName>
    <description>Quote Type</description>
    <inlineHelpText>Quote Type</inlineHelpText>
    <label>Quote Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Renewal with Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Renewal_Category__c.field-meta.xml
<CustomField>
    <fullName>CWS_Renewal_Category__c</fullName>
    <label>Renewal Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Renewal_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_Renewal_Type__c</fullName>
    <description>Renewal Type of Contract. Picklist values - Opt-Out, Opt-In and Non-Renewable</description>
    <inlineHelpText>Renewal Type of Contract. Picklist values - Opt-Out, Opt-In and Non-Renewable</inlineHelpText>
    <label>Renewal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Renewal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <description>Route to market of the Contract.</description>
    <label>Route to Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Source__c.field-meta.xml
<CustomField>
    <fullName>CWS_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Source Contract from which this contract is cloned.</description>
    <inlineHelpText>Source Contract from which this contract is cloned.</inlineHelpText>
    <label>Source</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_Status__c</fullName>
    <description>Contract Status
If Cancelled flag = TRUE, then Status = Terminated
If Start date &lt;= Today and End date &gt;= Today, Status = Active
If Start date &gt; Today, then Status = Inactive
If End date &lt; Today and Cancelled Flag is False, then Status = Expired</description>
    <formula>IF(CWS_Cancelled__c=TRUE, &apos;Terminated&apos;,
IF(SBQQ__Evergreen__c=TRUE,
IF(CWS_Master__c=true,IF(CWS_Legacy_Formula_Key__c!=null,&apos;Expired&apos;,IF(StartDate&lt;=TODAY(),&apos;Active&apos;,&apos;Inactive&apos;)),IF(StartDate&lt;=TODAY(),&apos;Active&apos;,&apos;Inactive&apos;)),
IF(AND(StartDate&lt;=TODAY(), EndDate&gt;=TODAY()), &apos;Active&apos;,
IF(StartDate&gt;TODAY(), &apos;Inactive&apos;,
IF(EndDate&lt;TODAY(), &apos;Expired&apos;,&apos;&apos;)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If Cancelled flag = TRUE, then Status = Terminated
If Start date &lt;= Today and End date &gt;= Today, Status = Active
If Start date &gt; Today, then Status = Inactive
If End date &lt; Today and Cancelled Flag is False, then Status = Expired</inlineHelpText>
    <label>Contract Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Transaction_Reason__c.field-meta.xml
<CustomField>
    <fullName>CWS_Transaction_Reason__c</fullName>
    <description>This field determines the transaction reason of the quote which is realted to this contract.</description>
    <label>Transaction Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Transaction_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Add_On_SKU__c.field-meta.xml
<CustomField>
    <fullName>CWS_Add_On_SKU__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates that the product can&apos;t be added in a New Business quote</inlineHelpText>
    <label>Add-On SKU</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Category__c.field-meta.xml
<CustomField>
    <fullName>CWS_Category__c</fullName>
    <inlineHelpText>Indicates the Category of the product</inlineHelpText>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Currencies__c.field-meta.xml
<CustomField>
    <fullName>CWS_Currencies__c</fullName>
    <inlineHelpText>Indicates the applicable currencies for the product</inlineHelpText>
    <label>Currencies</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Currencies_Billing_Only__c.field-meta.xml
<CustomField>
    <fullName>CWS_Currencies_Billing_Only__c</fullName>
    <inlineHelpText>Indicates the currencies from which a Active/Billing Only product behave as an Billing Only Product</inlineHelpText>
    <label>Currencies (Billing Only)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_NetSuite_Product_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_NetSuite_Product_Sync_Status__c</fullName>
    <defaultValue>&apos;New&apos;</defaultValue>
    <description>Product Sync status fields for netsuite : - Pick list field having values New,Not synced, Synced, Error.</description>
    <inlineHelpText>Indicates if the product is synced to NetSuite</inlineHelpText>
    <label>NetSuite Product Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
            <value>
                <fullName>Not Synced</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_ProductCode__c.field-meta.xml
<CustomField>
    <fullName>CWS_ProductCode__c</fullName>
    <description>Unique Field created for the Product Code.</description>
    <externalId>true</externalId>
    <inlineHelpText>Captures the unique identifier for the product</inlineHelpText>
    <label>Product Code</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_Renewal_Type__c</fullName>
    <inlineHelpText>Indicates if the product is an Opt-In or Opt-Out product</inlineHelpText>
    <label>Renewal Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opt-out</fullName>
            </value>
            <value>
                <fullName>Opt-in</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <inlineHelpText>Indicates the applicable Route to Market for the product</inlineHelpText>
    <label>Route to Market</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Marketplace</fullName>
            </value>
            <value>
                <fullName>Marketplace Only</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Route_to_Market_Billing_Only__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market_Billing_Only__c</fullName>
    <inlineHelpText>Indicates Route to Market where a Active/Billing Only product behaves as a Billing Only product</inlineHelpText>
    <label>Route to Market Billing Only</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IIT</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Marketplace Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Source__c.field-meta.xml
<CustomField>
    <fullName>CWS_Source__c</fullName>
    <description>to differenciate the CT and CW  products</description>
    <inlineHelpText>Indicates if the product is legacy CMS, CW or R1Soft product</inlineHelpText>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CW</fullName>
            </value>
            <value>
                <fullName>CMS</fullName>
            </value>
            <value>
                <fullName>R1Soft</fullName>
            </value>
            <value>
                <fullName>Marketplace</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_Status__c</fullName>
    <inlineHelpText>Indicates the Status of the product</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Zuora_Product_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_Zuora_Product_Sync_Status__c</fullName>
    <defaultValue>&apos;New&apos;</defaultValue>
    <description>Product Sync status fields for Zuora : - Pick list field having values New,Not synced, Synced, Error.</description>
    <inlineHelpText>Indicates if the product is synced to Zuora</inlineHelpText>
    <label>Zuora Product Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
            <value>
                <fullName>Not Synced</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/SBQQ__SubscriptionType__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionType__c</fullName>
    <description>Renewable Subscriptions will transfer to Renewal Quotes. One-time Subscriptions will not.</description>
    <inlineHelpText>Indicates if the product is One-Time, Renewable or Evergreen</inlineHelpText>
    <label>Subscription Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Renewable</fullName>
                <default>true</default>
                <label>Renewable</label>
            </value>
            <value>
                <fullName>One-time</fullName>
            </value>
            <value>
                <fullName>Renewable/Evergreen</fullName>
            </value>
            <value>
                <fullName>Evergreen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CWS_ProductSearchPlugin.cls
/*Class Name: CWS_ProductSearchPlugin
*Description: Product search plugin used to add additional filters on the Quoteline editor page. 
*Created By: Naresh
*Created On: 4/6/2020
*Modification Log
*------------------------------------------------------------------------------------------
*Developer              Date            User Story              Description
*------------------------------------------------------------------------------------------
*Naresh                4/6/2020          BED-5716               Product search plugin 

*/
Global class CWS_ProductSearchPlugin implements SBQQ.ProductSearchPlugin
{

    global CWS_ProductSearchPlugin()
    {
        // Constructor
    }
    
    global static Boolean isFilterHidden(SObject quote, String fieldName)
    {
        
        return fieldName == 'CWS_Add_On_SKU__c' || fieldName == 'CWS_Status__c' || fieldName =='CWS_Route_to_Market__c' || fieldName =='CWS_NetSuite_Product_Sync_Status__c' || fieldName == 'CWS_Zuora_Product_Sync_Status__c' ;  
       //return true;
    }
    
    global static String getAdditionalSuggestFilters(SObject s, Map<String,Object> m)
    {
        return null;
    }
    
    global static List<PricebookEntry> suggest(SObject s, Map<String,Object> m)
    {
        return null;
    }
    
    global static String getFilterDefaultValue(SObject quote, String fieldName)
    {
        System.debug('METHOD CALLED: getFilterDefaultValue');
       
        return NULL;
    }
    
    global static Boolean isSearchCustom(SObject quote, Map<String,Object> fieldValuesMap)
    {
        System.debug('METHOD CALLED: isSearchCustom');
       
        return false;
    }

    global static String getInputDefaultValue(SObject quote, String input)
    {
        System.debug('METHOD CALLED: getInputDefaultValue');
        return NULL;
    }
    
    global static Boolean isSuggestCustom(SObject quote, Map<String,Object> inputValuesMap)
    {
        return false;
    }
    
        
    global static String getAdditionalSearchFilters(SObject quote, Map<String,Object> fieldValuesMap)
    { 
        // Start of BED-5716 AND BED-3168
        System.debug('METHOD CALLED: getAdditionalSearchFilters');
        String additionalFilter = null;
        String[] applicableQuoteDistiCategories;
        String routeToMarket;
        String quoteDistiCategories;        
        String quoteType=quote.get('CWS_Quote_Type__c')!=null ? String.valueOf(quote.get('CWS_Quote_Type__c')): null;
        //Start BED-6434
        String quoteRenewalCategory;
        //End BED- 6434
        //Start BED-13278
        String quoteTransactionReason;
        //End BEd-13278
        Boolean master=false;
        try{
            List<Id> BillingOnlyProductIDList = new List<Id>();
            Set<Id> billingOnlyProductCodeSet = new Set<Id>();
            Set<Id> activebillingOnlyProductCodeSet = new Set<Id>();
            List<Id> activebillingOnlyProductCodeList = new List<Id>();
            String quoteId = String.valueOf(quote.get('Id'));
            String currIsoCode;
            
            
            if(quoteId != null){
                SBQQ__Quote__c quoteRecord = [SELECT Id, CWS_Renewal_Category__c, CWS_Transaction_Reason__c, CWS_Master__c from SBQQ__Quote__c where Id =:quoteId];
                master=quoteRecord.CWS_Master__c;
                routeToMarket = quote.get('CWS_Route_to_Market__c')!=null ? String.valueOf(quote.get('CWS_Route_to_Market__c')): null;
                quoteDistiCategories = quote.get('CWS_Distributor_Category__c')!=null ? String.valueOf(quote.get('CWS_Distributor_Category__c')): null;
                System.debug('quoteDistiCategories'+quoteDistiCategories);
                currIsoCode = quote.get('CurrencyIsoCode')!=null ? String.valueOf(quote.get('CurrencyIsoCode')): null;
                quoteRenewalCategory = (String.isNotBlank(quoteRecord.CWS_Renewal_Category__c)&&String.valueOf(quoteRecord.CWS_Renewal_Category__c)!=CWS_ConstantClass.Renewal_Category_SplitPending)?String.valueOf(quoteRecord.CWS_Renewal_Category__c):null;
                 quoteTransactionReason = String.isNotBlank(quoteRecord.CWS_Transaction_Reason__c)?String.valueOf(quoteRecord.CWS_Transaction_Reason__c):null;

                if(master){
                    additionalFilter=' Product2.CWS_Source__c= \''+ CWS_ConstantClass.PRODUCT_SOURCE_CMS + '\'';
                }
                if(quoteType == CWS_ConstantClass.QUOTE_TYPE_AMENDMENT ){
                List<SBQQ__QuoteLine__c> QlList=  new List<SBQQ__QuoteLine__c>([Select Id,SBQQ__EndDate__c,SBQQ__EffectiveEndDate__c, SBQQ__ProductCode__c,SBQQ__PriorQuantity__c,SBQQ__SubscriptionType__c, SBQQ__Product__c,SBQQ__Product__r.CWS_ProductCode__c,SBQQ__Product__r.CWS_Status__c,SBQQ__Quote__c,
                SBQQ__Quote__r.CWS_Quote_Type__c, SBQQ__Quote__r.CWS_Route_to_Market__c,SBQQ__Quote__r.CWS_Distributor_Category__c from SBQQ__QuoteLine__c Where SBQQ__Quote__c =:quoteId ]);
                
                if(!QlList.isEmpty()){
                   For(SBQQ__QuoteLine__c QL :QlList){
                       // Checking if product status is Billing-Only and is active in the contract            
                       if(QL.SBQQ__Product__r.CWS_Status__c == 'Billing Only' && QL.SBQQ__PriorQuantity__c > 0 && QL.SBQQ__Quote__r.CWS_Quote_Type__c == CWS_ConstantClass.QUOTE_TYPE_AMENDMENT && (QL.SBQQ__EffectiveEndDate__c >= Date.Today() || QL.SBQQ__SubscriptionType__c == CWS_ConstantClass.Subscription_Type_Evergreen) ){
                        billingOnlyProductCodeSet.add(ql.SBQQ__Product__c);
                            }

                        if(QL.SBQQ__Product__r.CWS_Status__c == 'Active\\Billing Only' && QL.SBQQ__PriorQuantity__c > 0 && QL.SBQQ__Quote__r.CWS_Quote_Type__c == CWS_ConstantClass.QUOTE_TYPE_AMENDMENT && (QL.SBQQ__EffectiveEndDate__c >= Date.Today() || QL.SBQQ__SubscriptionType__c == CWS_ConstantClass.Subscription_Type_Evergreen)){
                        activebillingOnlyProductCodeSet.add(ql.SBQQ__Product__c);
                            }    
                        }
                    }
                }   
               applicableQuoteDistiCategories=quoteDistiCategories!=null? quoteDistiCategories.split(';') : new List<String>();  
                system.debug('applicableQuoteDistiCategories'+applicableQuoteDistiCategories);
                if(!(quoteType == CWS_ConstantClass.QUOTE_TYPE_NEW_BUSINESS && (quoteTransactionReason==CWS_ConstantClass.TRANSACTION_REASON_CREDIT_REBILL || quoteTransactionReason==CWS_ConstantClass.TRANSACTION_REASON_RECOMMIT))){
                //Adding logic for 7385 to only allow products with Status:Active/Billing satisying below condition
               if(!activebillingOnlyProductCodeSet.isEmpty()){
                    activebillingOnlyProductCodeList.addall(activebillingOnlyProductCodeSet);
               }
                if(additionalFilter==''  || additionalFilter==null){
                    if(activebillingOnlyProductCodeList.isEmpty()){
                        additionalFilter = '((Product2.CWS_Status__c != \'Active\\\\Billing Only\') OR (Product2.CWS_Status__c = \'Active\\\\Billing Only\' AND Product2.CWS_Route_to_Market__c includes (\'' + +routeToMarket + '\') AND Product2.CWS_Currencies__c includes (\'' + currIsoCode + '\') AND (Product2.CWS_Route_to_Market_Billing_Only__c excludes (\'' + routeToMarket + '\') OR Product2.CWS_Currencies_Billing_Only__c excludes (\'' + currIsoCode + '\'))))';
                    }
                    else{
                        additionalFilter = '((Product2.CWS_Status__c != \'Active\\\\Billing Only\') OR ((Product2.CWS_Status__c = \'Active\\\\Billing Only\' AND Product2.CWS_Route_to_Market__c includes (\'' + +routeToMarket + '\') AND Product2.CWS_Currencies__c includes (\'' + currIsoCode + '\') AND (Product2.CWS_Route_to_Market_Billing_Only__c excludes (\'' + routeToMarket + '\') OR Product2.CWS_Currencies_Billing_Only__c excludes (\'' + currIsoCode + '\'))) OR (Product2.Id in (\''+String.join(activebillingOnlyProductCodeList,'\', \'') +'\'))))';
                    }
                              }
               else{
                   if(activebillingOnlyProductCodeList.isEmpty()){
                    additionalFilter =additionalFilter + ' AND ((Product2.CWS_Status__c != \'Active\\\\Billing Only\') OR (Product2.CWS_Status__c = \'Active\\\\Billing Only\' AND Product2.CWS_Route_to_Market__c includes (\'' + +routeToMarket + '\') AND Product2.CWS_Currencies__c includes (\'' + currIsoCode + '\') AND (Product2.CWS_Route_to_Market_Billing_Only__c excludes (\'' + routeToMarket + '\') OR Product2.CWS_Currencies_Billing_Only__c excludes (\'' + currIsoCode + '\'))))';
                   }
                   else{
                    additionalFilter = additionalFilter + ' AND ((Product2.CWS_Status__c != \'Active\\\\Billing Only\') OR ((Product2.CWS_Status__c = \'Active\\\\Billing Only\' AND Product2.CWS_Route_to_Market__c includes (\'' + +routeToMarket + '\') AND Product2.CWS_Currencies__c includes (\'' + currIsoCode + '\') AND (Product2.CWS_Route_to_Market_Billing_Only__c excludes (\'' + routeToMarket + '\') OR Product2.CWS_Currencies_Billing_Only__c excludes (\'' + currIsoCode + '\'))) OR (Product2.Id in (\''+String.join(activebillingOnlyProductCodeList,'\', \'') +'\'))))';
                   }
                               }
            }
               System.debug ('Initial additionalFilter '+additionalFilter);
           //Adding conditions based on Quote type and checking Billing only condition            
            if(quoteType == CWS_ConstantClass.QUOTE_TYPE_NEW_BUSINESS){
                If(quoteTransactionReason!=CWS_ConstantClass.TRANSACTION_REASON_CREDIT_REBILL && quoteTransactionReason!=CWS_ConstantClass.TRANSACTION_REASON_RECOMMIT){
                additionalFilter = '' + ( additionalFilter==null? '':additionalFilter+' AND ') +   ' Product2.CWS_Add_On_SKU__c = FALSE  AND Product2.CWS_Status__c != \'Billing Only\'' ;
                }   
                if(routeToMarket==CWS_ConstantClass.RTM_Value_Channel && !applicableQuoteDistiCategories.isEmpty()){
                    additionalFilter=''+ ( additionalFilter==null? '':additionalFilter+' AND ') + 
                        ' Product2.CWS_Category__c in (\''+String.join(applicableQuoteDistiCategories,'\', \'') +'\')';
                    }
               }        
                //Adding conditions based on Quote type and checking Billing only condition
               else if (quoteType == CWS_ConstantClass.QUOTE_TYPE_AMENDMENT && !billingOnlyProductCodeSet.isEmpty()){
                                    BillingOnlyProductIDList.addall(billingOnlyProductCodeSet);
                               if(quoteRenewalCategory!=null){
                                   additionalFilter = additionalFilter + ' AND Product2.CWS_Renewal_Type__c = \'' + quoteRenewalCategory + '\''; 
                               }     
                               additionalFilter = additionalFilter + ' AND ( Product2.CWS_Status__c != \'Billing Only\' OR '+
                               ' Product2.Id in (\''+String.join(BillingOnlyProductIDList,'\', \'') +'\') )'; //SHOW ONLY THESE PRODUCTS SCENARIO
                          if(routeToMarket==CWS_ConstantClass.RTM_Value_Channel && !applicableQuoteDistiCategories.isEmpty()){
                               additionalFilter=''+ ( additionalFilter==null? '':additionalFilter+' AND ') + 
                                   ' Product2.CWS_Category__c in (\''+String.join(applicableQuoteDistiCategories,'\', \'') +'\')';
                               }
               }
               //Adding conditions based on Quote type and checking Billing only condition
               else if (quoteType == CWS_ConstantClass.QUOTE_TYPE_AMENDMENT && billingOnlyProductCodeSet.isEmpty()){
                                if(quoteRenewalCategory!=null){
                                   additionalFilter = additionalFilter + ' AND Product2.CWS_Renewal_Type__c = \'' + quoteRenewalCategory + '\''; 
                               }  
                                additionalFilter = additionalFilter + ' AND Product2.CWS_Status__c != \'Billing Only\' ' ;
                               if(routeToMarket==CWS_ConstantClass.RTM_Value_Channel && !applicableQuoteDistiCategories.isEmpty()){
                               additionalFilter=''+ ( additionalFilter==null? '':additionalFilter+' AND ') + 
                                   ' Product2.CWS_Category__c in (\''+String.join(applicableQuoteDistiCategories,'\', \'') +'\')';
                               }   
               }
               //Adding conditions based on Quote type and checking Billing only condition
               else if (quoteType == CWS_ConstantClass.QUOTE_TYPE_RENEWALWC ){
                            if(quoteRenewalCategory!=null){
                                   additionalFilter = additionalFilter + ' AND Product2.CWS_Renewal_Type__c = \'' + quoteRenewalCategory + '\''; 
                               }  
                            additionalFilter = additionalFilter + ' AND Product2.CWS_Status__c != \'Billing Only\' ' ;
                               if(routeToMarket==CWS_ConstantClass.RTM_Value_Channel && !applicableQuoteDistiCategories.isEmpty()){
                               additionalFilter=''+ ( additionalFilter==null? '':additionalFilter+' AND ') + 
                                   ' Product2.CWS_Category__c in (\''+String.join(applicableQuoteDistiCategories,'\', \'') +'\')';
                               }  
                    }       
               }
              
               System.debug ('Final additionalFilter '+additionalFilter);                  
     }catch(Exception e){
        CWS_ExceptionHandler.logException( e,'SBQQ__Quote__c' , 'CWS_ProductSearchPlugin', 'getAdditionalSearchFilters' , '', null, null , 'get Additional Search Filters' , null);
                      }
        return additionalFilter;
        // Start of BED-5716 AND BED-3168
    }
    
    global static Boolean isInputHidden(SObject quote, String input)
    {
       
        return false;
    }
    
    global static List<PriceBookEntry> search(SObject quote, Map<String,Object> fieldValuesMap)
    {
        return null;
    }
}