force-app/main/default/objects/CWS_Error_Log__c/CWS_Error_Log__c.object-meta.xml
<CustomObject>
    <description>Used to log the details of the application exception</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{000000000}</displayFormat>
        <label>Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>CWS_Class_Name__c</fullName>
    <description>Class name from which the exception is invoked</description>
    <inlineHelpText>Class name from which the exception is invoked</inlineHelpText>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>CWS_Error_Message__c</fullName>
    <description>Error Message</description>
    <inlineHelpText>Error Message</inlineHelpText>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_Error_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_Error_Type__c</fullName>
    <description>Error Type</description>
    <inlineHelpText>Error Type</inlineHelpText>
    <label>Error Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>CWS_Record_Id__c</fullName>
    <description>Record Id</description>
    <inlineHelpText>Record Id</inlineHelpText>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CWS_RenewalFlexQueueSchedulableTest.cls
/*Class Name: CWS_RenewalFlexQueueSchedulableTest
*Description: Test class
*Created By: mahak bansal
*Created On:  12/2/2021 
*Ticket no :- 14276942 
*Modification Log
*------------------------------------------------------------------------------------------
*Developer              Date            User Story              Description
*------------------------------------------------------------------------------------------
*mahak bansal          12/2/2021            -                  Initial Version
*mahak bansal          24/2/2021            -                  Updated
*/
@isTest
public class CWS_RenewalFlexQueueSchedulableTest {
	
    @testsetup
    public static void setup(){
         Account accObj = new Account(Name = 'Continuum');
        insert accObj;
      // System.debug('Account object'+accObj);
       
        Order order = new Order();
        order.status ='DRAFT';
        order.Type='Renewal';
        order.AccountId = accObj.Id;
		order.EffectiveDate=Date.newInstance(2021, 09, 01);
        insert order;
       // System.debug('order object'+order);
        
        CWS_Error_Log__c errorRec = new CWS_Error_Log__c();
        errorRec.CWS_Error_Message__c ='TEXT___EEE'+'exceeded the limit of 100 jobs in the flex queue for org';
        errorRec.CWS_Class_Name__c='CWS_OrderTriggerHelper';
        errorRec.CWS_Error_Type__c='System.AsyncException';
        errorRec.CWS_Record_Id__c = order.Id;
        insert errorRec;
    }
    
    @isTest
    public static void testBatchCLass(){
        Test.startTest();
        String CRON_EXP = '0 0 0 3 9 ? 2022';
  
        String jobId = System.schedule('testScheduledApex',CRON_EXP,new CWS_RenewalFlexQueueSchedulable());
        
        // Get the information from the CronTrigger API object
      	CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, 
                                 NextFireTime
                                 FROM CronTrigger WHERE id = :jobId];
 
      // Verify the expressions are the same
     	 System.assertEquals(CRON_EXP, ct.CronExpression);                            
     //  System.schedule(new CWS_RenewalFlexQueueSchedulable())
      //   Database.executeBatch(new CWS_ProcessFlexQueueExcRecords(), 100);
        Test.stopTest();    
    }
    
}