force-app/main/default/objects/CWS_Error_Log__c/CWS_Error_Log__c.object-meta.xml
<CustomObject>
    <description>Used to log the details of the application exception</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{000000000}</displayFormat>
        <label>Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>CWS_Class_Name__c</fullName>
    <description>Class name from which the exception is invoked</description>
    <inlineHelpText>Class name from which the exception is invoked</inlineHelpText>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_Context__c.field-meta.xml
<CustomField>
    <fullName>CWS_Context__c</fullName>
    <label>Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_Error_Cause__c.field-meta.xml
<CustomField>
    <fullName>CWS_Error_Cause__c</fullName>
    <description>Cause extracted from the exception</description>
    <inlineHelpText>Cause extracted from the exception</inlineHelpText>
    <label>Error Cause</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_Error_Description__c.field-meta.xml
<CustomField>
    <fullName>CWS_Error_Description__c</fullName>
    <description>Error Description</description>
    <inlineHelpText>Error Description</inlineHelpText>
    <label>Error Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_Error_Line_Number__c.field-meta.xml
<CustomField>
    <fullName>CWS_Error_Line_Number__c</fullName>
    <description>Error line number</description>
    <label>Error Line Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>CWS_Error_Message__c</fullName>
    <description>Error Message</description>
    <inlineHelpText>Error Message</inlineHelpText>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_Error_Source__c.field-meta.xml
<CustomField>
    <fullName>CWS_Error_Source__c</fullName>
    <description>Error Source</description>
    <inlineHelpText>Error Source</inlineHelpText>
    <label>Error Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>CPQ</fullName>
            </value>
            <value>
                <fullName>Exception Handler</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>CLM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_Error_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_Error_Type__c</fullName>
    <description>Error Type</description>
    <inlineHelpText>Error Type</inlineHelpText>
    <label>Error Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_Integration_Error_Code__c.field-meta.xml
<CustomField>
    <fullName>CWS_Integration_Error_Code__c</fullName>
    <description>Integration Error Code</description>
    <inlineHelpText>Integration Error Code</inlineHelpText>
    <label>Integration Error Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_Integration_Name__c.field-meta.xml
<CustomField>
    <fullName>CWS_Integration_Name__c</fullName>
    <description>Integration Name</description>
    <inlineHelpText>Integration Name</inlineHelpText>
    <label>Integration Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_List_of_Records_Error__c.field-meta.xml
<CustomField>
    <fullName>CWS_List_of_Records_Error__c</fullName>
    <description>This field is created to capture the ID of the list of records that have failed..</description>
    <label>List of Records Error</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>CWS_Method_Name__c</fullName>
    <description>Method Name</description>
    <inlineHelpText>Method Name</inlineHelpText>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>CWS_Object_Name__c</fullName>
    <description>Object Name</description>
    <inlineHelpText>Object Name</inlineHelpText>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>CWS_Record_Id__c</fullName>
    <description>Record Id</description>
    <inlineHelpText>Record Id</inlineHelpText>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CWS_ExceptionHandler.cls
/*
Class Name : CWS_ExceptionHandler
Description : Utility class to insert error log records.
Developer : 
Date : 04/05/2020
*Modification Logs
*----------------------------------------------------------------------------------------------------------------------------
* Date                           Developer                User Story             Description
*----------------------------------------------------------------------------------------------------------------------------
*25/5/2020                      Ankit Bobde               BED-6479               Added a method which returns Error log Instance
*/
public class CWS_ExceptionHandler {

    //Start: BED- 6479
    /*
    Method Name : initializeAndReturnDMLErrorLogs
    Returns : CWS_Error_Log__c
    Description : Method to initialize and return error log records which can be used for Exception handling for DML Errors.
    Test Coverage : This method covers by Test Class : CWS_ShareRecordsCtrl_Test
    */
    
    public static CWS_Error_Log__c initializeAndReturnDMLErrorLogs(String className , 
                                            String methodName ,String errSrc, String errMsg, String recordId ,
                                            String context , String intgrtName){
        CWS_Error_Log__c errorLog = new CWS_Error_Log__c();
        errorLog.CWS_Class_Name__c = className;
        errorLog.CWS_Method_Name__c = methodName;
        errorLog.CWS_Error_Source__c = errSrc;
        errorLog.CWS_Error_Message__c = errMsg;
        errorLog.CWS_Record_Id__c = recordId;
        errorLog.CWS_Context__c = context;
        errorLog.CWS_Integration_Name__c = intgrtName;
        return errorLog;
    }
    //BED-6479
    

    /*
    Method Name : insertException
    Parameters : Object Name (String), Class Name(String) , Method Name (String), Error Cause (String), Error Source(String) , 
                 Error Message (String) , Error Line Number (String) , Error Type (String) , Integration Error Code (String),
                 Record Id (String) , Context (String) , Integration Name (String)
    Returns : void
    Description : Method to insert error log records for normal database operations.
    */

    public static void insertException( String objName , String className , 
                                        String methodName , String errCause , String errSrc ,
                                        String errMsg , String errLineNo , String errType , 
                                        String intgrtErrCode, String recordId ,
                                        String context , String intgrtName){
        try{
            System.debug('Exception on Class : ' + className + ' - ' + methodName +  
                            + ', Error : ' 
                            + errMsg 
                            + ' Line Number : ' 
                            + errLineNo
                            + ' Cause : '
                            + errCause
                            + ' Type : '
                            + errType);
            
            CWS_Error_Log__c errorLog = new CWS_Error_Log__c();
            
            errorLog.CWS_Object_Name__c = objName;
            errorLog.CWS_Class_Name__c = className;
            errorLog.CWS_Method_Name__c = methodName;
            errorLog.CWS_Error_Cause__c = errCause;
            errorLog.CWS_Error_Source__c = errSrc;
            errorLog.CWS_Error_Message__c = errMsg;
            errorLog.CWS_Error_Line_Number__c = errLineNo;
            errorLog.CWS_Error_Type__c = errType;
            errorLog.CWS_Error_Description__c = errType;
            errorLog.CWS_Integration_Error_Code__c = intgrtErrCode;
            errorLog.CWS_Record_Id__c = recordId;
            errorLog.CWS_Context__c = context;
            errorLog.CWS_Integration_Name__c = intgrtName;
            
            if(errorLog != NULL){
                insert errorLog;            
            }
               
                
        }
        catch(Exception e){
            insertException('CWS_Error_Log__c' , 'CWS_ExceptionHandler' , 'insertException Method' , e.getCause().getMessage(), 'Exception Handler', e.getMessage() , String.valueOf(e.getLineNumber()) , e.getTypeName() , '' , '' , 'While inserting error log record on handler class' , '');
        }
        
    }

     /*
    Method Name : logException
    Parameters : Exception,Object Name (String), Class Name(String) , Method Name (String)
                , Integration Error Code (String),
                 Record Id (String) , Context (String) , Integration Name (String)
    Returns : void
    Description : Method to insert error log records for normal database operations.
    */

    public static void logException( Exception objEx,String objName , String className , 
                                        String methodName ,String errSrc, String intgrtErrCode, String recordId ,
                                        String context , String intgrtName){
        try{
            
            CWS_Error_Log__c errorLog = new CWS_Error_Log__c();
            
            errorLog.CWS_Object_Name__c = objName;
            errorLog.CWS_Class_Name__c = className;
            errorLog.CWS_Method_Name__c = methodName;
            errorLog.CWS_Error_Source__c = errSrc;
            errorLog.CWS_Error_Message__c = objEx.getMessage();
            errorLog.CWS_Error_Line_Number__c = String.valueOf(objEx.getLineNumber());
            errorLog.CWS_Error_Type__c = objEx.getTypeName();
            errorLog.CWS_Integration_Error_Code__c = intgrtErrCode;
            errorLog.CWS_Record_Id__c = recordId;
            errorLog.CWS_Context__c = context;
            errorLog.CWS_Integration_Name__c = intgrtName;
            
            if(errorLog != NULL){
                insert errorLog;
            }
                
        }
        catch(Exception e){
            logException(e,'CWS_Error_Log__c' , 'CWS_ExceptionHandler' , 'insertException Method' , 
                                    'Exception Handler', '','' , 'While inserting error log record on handler class' , '');
        }
        
    }

    
     /*
    Method Name : logListException
    Parameters : Exception,Object Name (String), Class Name(String) , Method Name (String)
                , Integration Error Code (String),
                 recordIdList(String) , Context (String) , Integration Name (String)
    Returns : void
    Description : Method to insert error log records for list of records failed- basically in case of batch 
    */

    public static void logListException( Exception objEx,String objName , String className , 
                                        String methodName ,String errSrc, String intgrtErrCode, List<String> recordIdList ,
                                        String context , String intgrtName){
        try{
            
            CWS_Error_Log__c errorLog = new CWS_Error_Log__c();
            
            errorLog.CWS_Object_Name__c = objName;
            errorLog.CWS_Class_Name__c = className;
            errorLog.CWS_Method_Name__c = methodName;
            errorLog.CWS_Error_Source__c = errSrc;
            errorLog.CWS_Error_Message__c = objEx.getMessage();
            errorLog.CWS_Error_Line_Number__c = String.valueOf(objEx.getLineNumber());
            errorLog.CWS_Error_Type__c = objEx.getTypeName();
            errorLog.CWS_Integration_Error_Code__c = intgrtErrCode;
            errorLog.CWS_List_of_Records_Error__c = String.join(recordIdList, '\n');
            errorLog.CWS_Context__c = context;
            errorLog.CWS_Integration_Name__c = intgrtName;
            
            if(errorLog != NULL){
                insert errorLog;
            }
                
        }
        catch(Exception e){
            logException(e,'CWS_Error_Log__c' , 'CWS_ExceptionHandler' , 'insertException Method' , 
                                    'Exception Handler', '','' , 'While inserting error log record on handler class' , '');
        }
        
    }
    /*
    Method Name : logDMLSaveResults
    Parameters : SaveResult , Class Name (String) , Method Name (String) , Object Name (String) , Error Source (String), Context (String)
    Returns : void
    Description : Method to insert error log records for Database insert
    */
    public static void logDMLSaveResults( List< Database.SaveResult> saveresults , String className , String methodName,
                                     String objName , String errSrc , String context ){
        Boolean hasErrors = false;
        List<CWS_Error_Log__c> lstErrorLog = new List<CWS_Error_Log__c>();
        /*CWS_Error_Log__c errorLog = new CWS_Error_Log__c(CWS_Class_Name__c = className , CWS_Error_Source__c = errSrc , 
                                                    CWS_Method_Name__c = methodName , CWS_Object_Name__c = objName , 
                                                    CWS_Context__c = context
                                                    );*/
            
        for( Database.SaveResult res : saveresults ){
            if( !res.isSuccess() ){
                if( !hasErrors ){
                    hasErrors = true;
                }
                CWS_Error_Log__c errorLog = new CWS_Error_Log__c(CWS_Class_Name__c = className , CWS_Error_Source__c = errSrc , 
                                                    CWS_Method_Name__c = methodName, CWS_Object_Name__c = objName , 
                                                    CWS_Context__c = context, CWS_Error_Message__c=JSON.serialize( res.getErrors( ) ));
                //errorLog.CWS_Error_Message__c += JSON.serialize( res.getErrors( ) ) + '\n' ;
				if(res.getId() != Null){
                    errorLog.CWS_Record_Id__c=res.getId(); 
                }
                lstErrorLog.add(errorLog);
            }
                    
        }
           
        if( hasErrors ){
            try{
                if(lstErrorLog != NULL){
                    insert lstErrorLog;
                }
                
            }
            catch(DMLException e){
                insertException('CWS_Error_Log__c' , 'CWS_ExceptionHandler' , 'logDMLResults' , e.getCause().getMessage() , 'Exception Handler', e.getMessage() , String.valueOf(e.getLineNumber()) , e.getTypeName() , '' , '' , 'While inserting error log record on handler class' , '');    
            }
        }
    }
        
    /*
    Method Name : logDMLUpsertResults
    Parameters : UpsertResult , Class Name (String) , Method Name (String) , Object Name (String) , Error Source (String), Context (String)
    Returns : void
    Description : Method to insert error log records for Database upsert
    */

    public static void logDMLUpsertResults(List< Database.UpsertResult> saveresults , String className , String methodName,
                                          String objName , String errSrc , String context){
        Boolean hasErrors=false;
        List<CWS_Error_Log__c> lstErrorLog = new List<CWS_Error_Log__c>();
        /*CWS_Error_Log__c errorLog = new CWS_Error_Log__c(CWS_Class_Name__c = className , CWS_Error_Source__c = errSrc , 
                                                         CWS_Method_Name__c = methodName , CWS_Object_Name__c = objName , 
                                                         CWS_Context__c = context
                                                        );*/
        
        for( Database.UpsertResult res : saveresults ){
            if( !res.isSuccess() ){
                if( !hasErrors ){
                    hasErrors = true;
                }
                 CWS_Error_Log__c errorLog = new CWS_Error_Log__c(CWS_Class_Name__c = className , CWS_Error_Source__c = errSrc , 
                                                         CWS_Method_Name__c = methodName , CWS_Object_Name__c = objName , 
                                                         CWS_Context__c = context,CWS_Error_Message__c=JSON.serialize( res.getErrors( ) )
                                                        );
                lstErrorLog.add(errorLog);
                //errorLog.CWS_Error_Message__c += JSON.serialize( res.getErrors() ) + '\n';
            }
                
        }
        
        if( hasErrors ){
            try{
                if(lstErrorLog != NULL){
                    insert lstErrorLog;
                }
            }
            catch(DMLException e){
                insertException('CWS_Error_Log__c' , 'CWS_ExceptionHandler' , 'logDMLUpsertResults' , e.getCause().getMessage() , 'Exception Handler', e.getMessage() , String.valueOf(e.getLineNumber()) , e.getTypeName() , '' , '' , 'While inserting error log record on handler class' , '');    
            }
        }
    }

    /*
    Method Name : logDMLDelResults
    Parameters : DeleteResult , Class Name (String) , Method Name (String) , Object Name (String) , Error Source (String), Context (String)
    Returns : void
    Description : Method to insert error log records for Database delete
    */  

    public static void logDMLDelResults(List< Database.DeleteResult> deleteresults , String className , String methodName,
                                        String objName , String errSrc , String context ){
        Boolean hasErrors=false;
        List<CWS_Error_Log__c> lstErrorLog = new List<CWS_Error_Log__c>();
        /*CWS_Error_Log__c errorLog = new CWS_Error_Log__c(CWS_Class_Name__c = className , CWS_Error_Source__c = errSrc , 
                                                        CWS_Method_Name__c = methodName , CWS_Object_Name__c = objName , 
                                                        CWS_Context__c = context
                                                        );*/
        
        for( Database.DeleteResult res : deleteresults ){
            if( !res.isSuccess() ){
                if( !hasErrors ){
                    hasErrors = true;
                }
                CWS_Error_Log__c errorLog = new CWS_Error_Log__c(CWS_Class_Name__c = className , CWS_Error_Source__c = errSrc , 
                                                                 CWS_Method_Name__c = methodName , CWS_Object_Name__c = objName , 
                                                                 CWS_Context__c = context, CWS_Error_Message__c=JSON.serialize( res.getErrors( ) )
                                                                );
                lstErrorLog.add(errorLog);
                //errorLog.CWS_Error_Message__c += JSON.serialize( res.getErrors() ) + '\n' ;
            }
                
        }
            
            
        if( hasErrors ){
            try{
                if(lstErrorLog != NULL){
                    insert lstErrorLog;
                }
                
            }
            catch(DMLException e){
               insertException('CWS_Error_Log__c' , 'CWS_ExceptionHandler' , 'logDMLDelResults' , e.getCause().getMessage() , 'Exception Handler', e.getMessage() , String.valueOf(e.getLineNumber()) , e.getTypeName() , '' , '' , 'While inserting error log record on handler class' , '');    
            }
        }
    }

    /*
    Method Name : logGenericErrors
    Parameters : Class Name(String) , Method Name (String), 
                 err Source (String) , err message (String), recordId (String), Context (String) , Integration Name (String)
    Returns : void
    Description : Method to insert error log records.
    */

    public static void logErrors(String className , 
                                        String methodName ,String errSrc, String errMsg, String recordId ,
                                        String context , String intgrtName){
        try{
            
            CWS_Error_Log__c errorLog = new CWS_Error_Log__c();
            
            errorLog.CWS_Class_Name__c = className;
            errorLog.CWS_Method_Name__c = methodName;
            errorLog.CWS_Error_Source__c = errSrc;
            errorLog.CWS_Error_Message__c = errMsg;
            errorLog.CWS_Record_Id__c = recordId;
            errorLog.CWS_Context__c = context;
            errorLog.CWS_Integration_Name__c = intgrtName;
            
            if(errorLog != NULL){
                insert errorLog;
            }
                
        }
        catch(Exception e){
            logException(e,'CWS_Error_Log__c' , 'CWS_ExceptionHandler' , 'insertException Method' , 
                                    'Exception Handler', '','' , 'While inserting error log record on handler class' , '');
        }
        
    }
}