force-app/main/default/objects/Product2/fields/CW_Product_Type__c.field-meta.xml
<CustomField>
    <fullName>CW_Product_Type__c</fullName>
    <inlineHelpText>Indicates the type of the product</inlineHelpText>
    <label>Product Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Packaging</fullName>
            </value>
            <value>
                <fullName>Base</fullName>
            </value>
            <value>
                <fullName>Charge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Billing_Term__c.field-meta.xml
<CustomField>
    <fullName>CWS_Billing_Term__c</fullName>
    <inlineHelpText>Indicates the applicable billing term for the product</inlineHelpText>
    <label>Billing Term</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Bi-Annual</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Tri-Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Category__c.field-meta.xml
<CustomField>
    <fullName>CWS_Category__c</fullName>
    <inlineHelpText>Indicates the Category of the product</inlineHelpText>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Charge_Model__c.field-meta.xml
<CustomField>
    <fullName>CWS_Charge_Model__c</fullName>
    <description>Depicts Zuora charge Model</description>
    <inlineHelpText>Indicates the Charge Model of the product</inlineHelpText>
    <label>Charge Model</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discount-Fixed Amount</fullName>
            </value>
            <value>
                <fullName>Discount-Percentage</fullName>
            </value>
            <value>
                <fullName>Flat Fee Pricing</fullName>
            </value>
            <value>
                <fullName>Per Unit Pricing</fullName>
            </value>
            <value>
                <fullName>Overage Pricing</fullName>
            </value>
            <value>
                <fullName>Tiered Pricing</fullName>
            </value>
            <value>
                <fullName>Tiered with Overage Pricing</fullName>
            </value>
            <value>
                <fullName>Volume Pricing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Currencies__c.field-meta.xml
<CustomField>
    <fullName>CWS_Currencies__c</fullName>
    <inlineHelpText>Indicates the applicable currencies for the product</inlineHelpText>
    <label>Currencies</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Description__c.field-meta.xml
<CustomField>
    <fullName>CWS_Description__c</fullName>
    <description>This field captures the long description of the product</description>
    <inlineHelpText>Captures the description of the product</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_License_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_License_Type__c</fullName>
    <inlineHelpText>Indicates the License Type of the product</inlineHelpText>
    <label>License Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_LicenseType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Product_Family__c.field-meta.xml
<CustomField>
    <fullName>CWS_Product_Family__c</fullName>
    <inlineHelpText>Indicates Product Family of the product</inlineHelpText>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Product_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Product_Line__c.field-meta.xml
<CustomField>
    <fullName>CWS_Product_Line__c</fullName>
    <description>Used for Netsuite integration</description>
    <inlineHelpText>Used for Netsuite integration</inlineHelpText>
    <label>Product Line</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BDR</fullName>
            </value>
            <value>
                <fullName>BDR : BDR - Other</fullName>
            </value>
            <value>
                <fullName>BDR : Recover</fullName>
            </value>
            <value>
                <fullName>BDR : Solution Partners</fullName>
            </value>
            <value>
                <fullName>Business Automation</fullName>
            </value>
            <value>
                <fullName>Business Automation : BrightGauge</fullName>
            </value>
            <value>
                <fullName>Business Automation : Business Automation - Other</fullName>
            </value>
            <value>
                <fullName>Business Automation : Business Management Packages</fullName>
            </value>
            <value>
                <fullName>Business Automation : Engage</fullName>
            </value>
            <value>
                <fullName>Business Automation : ITBoost</fullName>
            </value>
            <value>
                <fullName>Business Automation : Manage</fullName>
            </value>
            <value>
                <fullName>Business Automation : Sell</fullName>
            </value>
            <value>
                <fullName>Business Automation : Service Leadership</fullName>
            </value>
            <value>
                <fullName>Business Automation : Service Leadership - Peer Groups</fullName>
                <isActive>false</isActive>
                <label>Business Automation : Service Leadership - Peer Groups</label>
            </value>
            <value>
                <fullName>Business Automation : Smileback</fullName>
            </value>
            <value>
                <fullName>Business Automation : Solution Partners</fullName>
            </value>
            <value>
                <fullName>Business Automation : Unite (fka CloudConsole)</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Cybersecurity</fullName>
            </value>
            <value>
                <fullName>Cybersecurity : Cybersecurity - Other</fullName>
                <isActive>false</isActive>
                <label>Cybersecurity : Cybersecurity - Other</label>
            </value>
            <value>
                <fullName>Cybersecurity : EDR – ConnectWise</fullName>
            </value>
            <value>
                <fullName>Cybersecurity : Endpoint Policy Mgmt</fullName>
            </value>
            <value>
                <fullName>Cybersecurity : Fortify</fullName>
            </value>
            <value>
                <fullName>Cybersecurity : Identify</fullName>
            </value>
            <value>
                <fullName>Cybersecurity : Incident Response Service</fullName>
            </value>
            <value>
                <fullName>Cybersecurity : Legacy Security Mgmt</fullName>
            </value>
            <value>
                <fullName>Cybersecurity : Managed SIEM</fullName>
            </value>
            <value>
                <fullName>Cybersecurity : MDR – Bitdefender</fullName>
            </value>
            <value>
                <fullName>Cybersecurity : MDR – SentinelOne</fullName>
            </value>
            <value>
                <fullName>Cybersecurity : Network Sensor</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_ProductCode__c.field-meta.xml
<CustomField>
    <fullName>CWS_ProductCode__c</fullName>
    <description>Unique Field created for the Product Code.</description>
    <externalId>true</externalId>
    <inlineHelpText>Captures the unique identifier for the product</inlineHelpText>
    <label>Product Code</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_Renewal_Type__c</fullName>
    <inlineHelpText>Indicates if the product is an Opt-In or Opt-Out product</inlineHelpText>
    <label>Renewal Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opt-out</fullName>
            </value>
            <value>
                <fullName>Opt-in</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <inlineHelpText>Indicates the applicable Route to Market for the product</inlineHelpText>
    <label>Route to Market</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Marketplace</fullName>
            </value>
            <value>
                <fullName>Marketplace Only</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_SKU_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_SKU_Type__c</fullName>
    <inlineHelpText>Indicates the SKU Type of the product</inlineHelpText>
    <label>SKU Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_SKU_TYPE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_Status__c</fullName>
    <inlineHelpText>Indicates the Status of the product</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>CWS_Sub_Category__c</fullName>
    <inlineHelpText>Indicates the Sub Category of the product</inlineHelpText>
    <label>Sub Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Sub_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/SBQQ__BillingType__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__BillingType__c</fullName>
    <description>The billing type that defines when the billing occurs. Billing in advance lets you bill your customers for products or services before you provide them; Billing in arrears lets you bill your customers after the products or services are provided.</description>
    <inlineHelpText>Indicates if the customer will be charged In-Advance or in Arrears for the product</inlineHelpText>
    <label>Billing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__BillingType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/SBQQ__PricingMethod__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PricingMethod__c</fullName>
    <description>Pricing method that should be applied to this product.</description>
    <inlineHelpText>Indicates the pricing method for this product</inlineHelpText>
    <label>Pricing Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>List</fullName>
                <default>true</default>
                <label>List</label>
            </value>
            <value>
                <fullName>Cost</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
            <value>
                <fullName>Percent Of Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Term length of this subscription. Only applicable if the product is a subscription.</description>
    <inlineHelpText>Indicates the term (in months) for which the price has been listed for the product</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CWS_ProductSyncPBEBatchTest.cls
/*Class Name: CWS_DiscountTierHelperTest
*Description: Test Class for CWS_DiscountTierTriggerHelper
*Created By: Indra Ganesan
*Created On: 31-07-2020
*Modification Log
*------------------------------------------------------------------------------------------
*Developer              Date            Description
*------------------------------------------------------------------------------------------
*Indra Ganesan         31-07-2020       Test Class for CWS_DiscountTierTriggerHelper             
*/
@isTest(SeeAllData=false)
public with Sharing class CWS_ProductSyncPBEBatchTest {
    @TestSetup
    static void init(){
        List<Product2> lstProduct= new List<Product2>();        
        Product2 p = new Product2(
            Name='Demo Test Product',
            CWS_ProductCode__c='DEMQ9009',
            CWS_Category__c='Sell',
            SBQQ__BillingType__c='Advance',
            SBQQ__PricingMethod__c='Cost',
            SBQQ__SubscriptionTerm__c=12,
            CWS_Description__c='Cloud Access DW Security',     
            CWS_Charge_Model__c='Per Unit Pricing',
            CWS_Product_Family__c='Other',
            CWS_License_Type__c='SaaS',
            CWS_Product_Line__c='Corporate',
            CWS_Status__c='Active',
            CWS_Sub_Category__c='License',
            CW_Product_Type__c='Product',
            CWS_SKU_Type__c='Other',
            CWS_Renewal_Type__c='Opt-out',
            CWS_Route_to_Market__c='Direct',
            CWS_Currencies__c='USD',
            CWS_Billing_Term__c='Monthly',
            CWS_ChargeType__c='Recurring',
            CWS_Item_Revenue_Category__c='Services',
            IsActive= True,
            SBQQ__SubscriptionPricing__c='Fixed Pricing',
            CWS_UOM__c='Cost'     
        );
        
        insert P;       
        PricebookEntry standardPBE = new PricebookEntry(Pricebook2Id=Test.getStandardPricebookId(), Product2Id = p.Id, UnitPrice = 1000, IsActive = true);
        insert standardPBE;
        Pricebook2 pbCW =CWS_UTLDataFactory.createCustomPB('ConnectWise Standard PriceBook', true);     
        PricebookEntry pbe=CWS_UTLDataFactory.createPBEwithPricebookId(pbCW.Id,p.id,1000.00,'USD', true);      
    }
    
    @isTest 
    static void testProductSyncBatch() 
    {
        Test.startTest();
		Pricebook2 pb = [SELECT Id, Name , isActive from Pricebook2 where name='ConnectWise Standard PriceBook'];
		List<PricebookEntry> lstPriceBookEntry = [Select Id,Product2.IsActive, Pricebook2.Name,Product2Id,CWS_Price_Modified__c,pricebook2Id,CurrencyIsoCode, UnitPrice, CWS_CostPrice__c, IsActive from PricebookEntry where IsActive = True  and Product2.IsActive = True and CWS_Price_Modified__c= True and Pricebook2.Name = 'System.Label.CWS_ConnectwisePricebook' limit 1];       
		CWS_ProductSyncPBEBatch tstBatch = new CWS_ProductSyncPBEBatch();
		DataBase.executeBatch(tstBatch);
		System.assertEquals(true,lstPriceBookEntry.size() !=null);
        Test.stopTest();
    }

}