force-app/main/default/objects/Account/fields/CWS_Additional_Emails_for_Invoice__c.field-meta.xml
<CustomField>
    <fullName>CWS_Additional_Emails_for_Invoice__c</fullName>
    <inlineHelpText>Captures email addresses that can be added to invoices involving this Account record.</inlineHelpText>
    <label>Additional Emails for Invoice</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <inlineHelpText>Captures the Contact&apos;s route to market; used for routing to BDR and PSE/SE pools.</inlineHelpText>
    <label>Route to Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
                <default>true</default>
                <label>Direct</label>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_75_Days_Sent__c.field-meta.xml
<CustomField>
    <fullName>CWS_75_Days_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>75 Days Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>CWS_Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Bill To Account for the Contract</description>
    <inlineHelpText>Bill To Account for the Contract</inlineHelpText>
    <label>Bill To (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Bill_To_Contact__c.field-meta.xml
<CustomField>
    <fullName>CWS_Bill_To_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Bill To Contact associated with this contract.</description>
    <inlineHelpText>Bill To Contact associated with this contract.</inlineHelpText>
    <label>Bill To Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Add Bill To Contact associated with Bill To Accounts.</errorMessage>
        <filterItems>
            <field>$Source.CWS_Bill_To_Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <infoMessage>Add Bill To Contact associated with Bill To Accounts.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>CWS_Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Cancelled Flag indicates all the subscriptions under a contract got terminated.</description>
    <inlineHelpText>Indicates that all the Subscriptions in this contract got terminated.</inlineHelpText>
    <label>Canceled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Days_Remaining__c.field-meta.xml
<CustomField>
    <fullName>CWS_Days_Remaining__c</fullName>
    <description>New Field to capture the Days From Expiration of Contract.</description>
    <formula>IF(SBQQ__ExpirationDate__c!=TODAY()&amp;&amp; NOT(ISNULL(SBQQ__ExpirationDate__c)),(SBQQ__ExpirationDate__c-TODAY()),0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>CWS_Error_Message__c</fullName>
    <description>Error Message when updating the Contract.</description>
    <inlineHelpText>Error Message when updating the Contract.</inlineHelpText>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Master__c.field-meta.xml
<CustomField>
    <fullName>CWS_Master__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Contracts with Master? as TRUE, indicates only legacy records with $value for commitment.</description>
    <inlineHelpText>Contracts with Master? as TRUE, indicates only legacy records with $value for commitment.</inlineHelpText>
    <label>Master</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Renewal_Category__c.field-meta.xml
<CustomField>
    <fullName>CWS_Renewal_Category__c</fullName>
    <label>Renewal Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Renewal_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_Renewal_Type__c</fullName>
    <description>Renewal Type of Contract. Picklist values - Opt-Out, Opt-In and Non-Renewable</description>
    <inlineHelpText>Renewal Type of Contract. Picklist values - Opt-Out, Opt-In and Non-Renewable</inlineHelpText>
    <label>Renewal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Renewal_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <description>Route to market of the Contract.</description>
    <label>Route to Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Sold_To_Contact__c.field-meta.xml
<CustomField>
    <fullName>CWS_Sold_To_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Sold To Contact associated with this contract.</description>
    <inlineHelpText>Sold To Contact associated with this contract.</inlineHelpText>
    <label>Sold To Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Select contact which are associated to this Sold To Account.</errorMessage>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <infoMessage>Select contact which are associated to this Sold To Account.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts (Sold To Contact)</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Source__c.field-meta.xml
<CustomField>
    <fullName>CWS_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Source Contract from which this contract is cloned.</description>
    <inlineHelpText>Source Contract from which this contract is cloned.</inlineHelpText>
    <label>Source</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SBQQ__RenewalForecast__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewalForecast__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Select to trigger the generation of a renewal opportunity for forecasting purposes. Does not automatically generate a renewal quote.</description>
    <inlineHelpText>Select to trigger the generation of a renewal opportunity for forecasting purposes. Does not automatically generate a renewal quote.</inlineHelpText>
    <label>Renewal Forecast</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SBQQ__RenewalQuoted__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RenewalQuoted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Select this option to automatically generate a renewal quote on renewal opportunities.</description>
    <inlineHelpText>Select this option to automatically generate a renewal quote on renewal opportunities.</inlineHelpText>
    <label>Renewal Quoted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CWS_Error_Log__c/CWS_Error_Log__c.object-meta.xml
<CustomObject>
    <description>Used to log the details of the application exception</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{000000000}</displayFormat>
        <label>Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>CWS_Class_Name__c</fullName>
    <description>Class name from which the exception is invoked</description>
    <inlineHelpText>Class name from which the exception is invoked</inlineHelpText>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>CWS_Error_Message__c</fullName>
    <description>Error Message</description>
    <inlineHelpText>Error Message</inlineHelpText>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>CWS_Method_Name__c</fullName>
    <description>Method Name</description>
    <inlineHelpText>Method Name</inlineHelpText>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CWS_Error_Log__c/fields/CWS_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>CWS_Record_Id__c</fullName>
    <description>Record Id</description>
    <inlineHelpText>Record Id</inlineHelpText>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/CWS_Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>CWS_Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order (Bill-To Account)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/CWS_Bill_To_Contact__c.field-meta.xml
<CustomField>
    <fullName>CWS_Bill_To_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Order (Bill To Contact)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/CWS_Master__c.field-meta.xml
<CustomField>
    <fullName>CWS_Master__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Order with Master? as TRUE, indicates only legacy records with $value for commitment.</description>
    <inlineHelpText>Order with Master? as TRUE, indicates only legacy records with $value for commitment.</inlineHelpText>
    <label>Master</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/CWS_Renewal_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_Renewal_Type__c</fullName>
    <formula>TEXT(SBQQ__Quote__r.CWS_Renewal_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <description>The route to market information copied from Quote</description>
    <inlineHelpText>The route to market information copied from Quote</inlineHelpText>
    <label>Route to Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CWS_75daysRenewalReminderEmailsBatch.cls
/**
* Description  : Renewal Notification Batch : 75 days 
* User Story   : Service Ticket #14292767 
**/ 

public class CWS_75daysRenewalReminderEmailsBatch implements Database.Batchable<sObject>, Database.stateful {    
    public Map<String,EmailTemplate> emailTemplateMap;
    public List<CWS_Error_Log__c> errRecsToInsert = new List<CWS_Error_Log__c>();
    public String headerValue = 'Contract Id, Error Message \n';
    public string csvBody = '';
    public String finalCsv = '';
        
    public CWS_75daysRenewalReminderEmailsBatch(){
        Set<String> emailTemplateNames = new Set<String>{'CWS_CW_75_Day_Communication_Auto_renew',
                                                         'CWS_Continuum_75_Day_Comm_Auto_renew','CWS_CMS_CW_75_Day_Reminder_Opt_In'};
            emailTemplateMap = new Map<String,EmailTemplate>();
        for(EmailTemplate et : [SELECT Id, Name, DeveloperName, Markup FROM EmailTemplate where developername IN: emailTemplateNames]){
            emailTemplateMap.put(et.DeveloperName,et);
        }
    }    
    
    public Database.QueryLocator start(Database.BatchableContext bc){
        String queryString = ' SELECT Id , endDate'
            + ',SBQQ__RenewalForecast__c '
            + ',SBQQ__RenewalQuoted__c '
            + ',SBQQ__RenewalOpportunity__r.CWS_Sold_To_Contact__r.email '
            + ',SBQQ__RenewalOpportunity__c '
            + ',SBQQ__RenewalOpportunity__r.Type '
            + ',SBQQ__RenewalOpportunity__r.CWS_Sold_To_Contact__c '
            + ',SBQQ__RenewalOpportunity__r.SBQQ__PrimaryQuote__c '
            + ',SBQQ__RenewalOpportunity__r.CreatedDate '
            + ',SBQQ__RenewalOpportunity__r.SBQQ__PrimaryQuote__r.CreatedDate '
            + ',CWS_Days_Remaining__c '
            + ',SBQQ__Quote__c '
            + ',CWS_Route_to_Market__c '
            + ',CWS_Renewal_Category__c '
            + ',CWS_Bill_To_Contact__c '
            + ',CWS_Bill_To_Account__c '
            + ',CWS_Bill_To_Account__r.CWS_Additional_Emails_for_Invoice__c '
            + ',SBQQ__Opportunity__c '
            + ',SBQQ__Opportunity__r.Type '
            + ',SBQQ__RenewalOpportunity__r.SBQQ__RenewedContract__c '
            + ',SBQQ__RenewalOpportunity__r.SBQQ__RenewedContract__r.CWS_Days_Remaining__c '
            + ',SBQQ__RenewalOpportunity__r.SBQQ__RenewedContract__r.SBQQ__ExpirationDate__c '
            + ',CWS_75_Days_Sent__c'
            + ', (SELECT id, CWS_Product_Source__c, SBQQ__Product__r.CWS_Source__c FROM SBQQ__Subscriptions__r)'
            + ' FROM '
            + ' Contract '
            + ' WHERE '
            + ' CWS_Days_Remaining__c='+ Label.CWS_75_Days_Renewal
            + ' AND CWS_75_Days_Sent__c = false'
            + ' AND EndDate >=TODAY '
            + ' AND SBQQ__RenewalForecast__c = true '
            + ' AND CWS_Cancelled__c = false '
            + ' AND CWS_Renewal_Type__c != \'Non-Renewable\''
            + ' AND SBQQ__RenewalOpportunity__c !=null '
            + ' AND SBQQ__RenewalOpportunity__r.StageName!=\''+ CWS_ConstantClass.OpportunityClosedLose_Stage +'\' '
            + ' AND SBQQ__RenewalOpportunity__r.StageName!=\''+ CWS_ConstantClass.OpportunityClosedWon_Stage  +'\' '
            + ' AND (CWS_Master__c=TRUE OR (CWS_Master__c=FALSE AND SBQQ__RenewalOpportunity__r.CWS_On_Hold__c=FALSE ))'
            + ' AND (CWS_Renewal_Category__c = \'Opt-Out\' OR CWS_Renewal_Category__c = \'Opt-In\')';
        
        if(!Label.CWS_75_Days_Renewal_Batch_Switch.equalsIgnoreCase('ON')){ // to terminate the batch processing, change the label to any value other than 'on'
            queryString = queryString +  ' Limit 0';
        }
        
        return Database.getQueryLocator(queryString);
    }
    
    public void execute(Database.BatchableContext bc, List<Contract> contracts){
        List<Contract> contractsToUpdate = new List<Contract>();
        List<Messaging.SingleEmailMessage> seventyFiveDaysNotificationEmails = new List<Messaging.SingleEmailMessage>();
        SBQQ__Subscription__c subscriptionTempInstance;
        Map<Id,Id> mapOfCPrimaryQuoteandDocumentId = new Map<Id,Id>();
        Set<Id> renewalOpportunityIds = new Set<Id>();
        
        for(Contract con : contracts){
            renewalOpportunityIds.add(con.SBQQ__RenewalOpportunity__c);
        }
        
        for(Contract con : contracts){
            Messaging.SingleEmailMessage tempInstance = new Messaging.SingleEmailMessage();
            List<String> additionalEmailIdsTempList = new List<String>();
            List<Id> tempDocIds = new List<Id>();
            if(String.isNotBlank(con.CWS_Bill_To_Account__r.CWS_Additional_Emails_for_Invoice__c)){
                if(con.CWS_Bill_To_Account__r.CWS_Additional_Emails_for_Invoice__c.contains(',')){
                    additionalEmailIdsTempList = con.CWS_Bill_To_Account__r.CWS_Additional_Emails_for_Invoice__c.split(',');
                }
                else{
                    additionalEmailIdsTempList.add(con.CWS_Bill_To_Account__r.CWS_Additional_Emails_for_Invoice__c);
                }
            }
            
            if(con.SBQQ__Subscriptions__r.size() > 0){
                subscriptionTempInstance = new SBQQ__Subscription__c();
                subscriptionTempInstance = con.SBQQ__Subscriptions__r[0];
            }
            
            if(String.isNotBlank(con.SBQQ__RenewalOpportunity__r.Type) 
               && (con.SBQQ__RenewalOpportunity__r.Type == CWS_ConstantClass.Opportunity_Type_Renewal || con.SBQQ__RenewalOpportunity__r.Type == CWS_ConstantClass.Opportunity_Type_RenewalWithChange)
               && subscriptionTempInstance != null
               && subscriptionTempInstance.SBQQ__Product__r.CWS_Source__c == CWS_ConstantClass.PRODUCT_SOURCE_CMS
               && emailTemplateMap.containsKey('CWS_Continuum_75_Day_Comm_Auto_renew')
               && con.CWS_Renewal_Category__c == 'Opt-Out'){
                   
                   tempInstance = createEmailMessage(emailTemplateMap.get('CWS_Continuum_75_Day_Comm_Auto_renew').Id,con,additionalEmailIdsTempList,null);//tempInstance = (emailTemplateMap.get('CWS_Continuum_75_Day_Comm_Auto_renew').Markup.containsIgnoreCase('attached Order Form') ? createEmailMessage(emailTemplateMap.get('CWS_Continuum_75_Day_Comm_Auto_renew').Id,con,additionalEmailIdsTempList,tempDocIds) : createEmailMessage(emailTemplateMap.get('CWS_Continuum_75_Day_Comm_Auto_renew').Id,con,additionalEmailIdsTempList,null));
                   seventyFiveDaysNotificationEmails.add(tempInstance);
                   con.CWS_75_Days_Sent__c = true;
                   contractsToUpdate.add(con);
               }
            else if(String.isNotBlank(con.SBQQ__RenewalOpportunity__r.Type) 
                   && (con.SBQQ__RenewalOpportunity__r.Type == CWS_ConstantClass.Opportunity_Type_Renewal || con.SBQQ__RenewalOpportunity__r.Type == CWS_ConstantClass.Opportunity_Type_RenewalWithChange)
                   && subscriptionTempInstance != null
                   && subscriptionTempInstance.SBQQ__Product__r.CWS_Source__c == CWS_ConstantClass.PRODUCT_SOURCE_CW
                   && emailTemplateMap.containsKey('CWS_CW_75_Day_Communication_Auto_renew')
                   && con.CWS_Renewal_Category__c == 'Opt-Out'){
                       
                        tempInstance = createEmailMessage(emailTemplateMap.get('CWS_CW_75_Day_Communication_Auto_renew').Id,con,additionalEmailIdsTempList,null);//(emailTemplateMap.get('CWS_CW_75_Day_Communication_Auto_renew').Markup.containsIgnoreCase('attached Order Form') ? createEmailMessage(emailTemplateMap.get('CWS_CW_75_Day_Communication_Auto_renew').Id,con,additionalEmailIdsTempList,tempDocIds) : createEmailMessage(emailTemplateMap.get('CWS_CW_75_Day_Communication_Auto_renew').Id,con,additionalEmailIdsTempList,null));
                        seventyFiveDaysNotificationEmails.add(tempInstance);
                        con.CWS_75_Days_Sent__c = true;
                        contractsToUpdate.add(con);
                    }
            else if(String.isNotBlank(con.SBQQ__RenewalOpportunity__r.Type) 
                   && (con.SBQQ__RenewalOpportunity__r.Type == CWS_ConstantClass.Opportunity_Type_RenewalWithChange)
                   && subscriptionTempInstance != null
                   && (subscriptionTempInstance.SBQQ__Product__r.CWS_Source__c == CWS_ConstantClass.PRODUCT_SOURCE_CW)
                   && emailTemplateMap.containsKey('CWS_CMS_CW_75_Day_Reminder_Opt_In')
                   && con.CWS_Renewal_Category__c == 'Opt-In'){
                       
                        tempInstance = createEmailMessage(emailTemplateMap.get('CWS_CMS_CW_75_Day_Reminder_Opt_In').Id,con,additionalEmailIdsTempList,null);//(emailTemplateMap.get('CWS_CMS_CW_75_Day_Reminder_Opt_In').Markup.containsIgnoreCase('attached Order Form') ? createEmailMessage(emailTemplateMap.get('CWS_CMS_CW_75_Day_Reminder_Opt_In').Id,con,additionalEmailIdsTempList,tempDocIds) : createEmailMessage(emailTemplateMap.get('CWS_CMS_CW_75_Day_Reminder_Opt_In').Id,con,additionalEmailIdsTempList,null));
                        seventyFiveDaysNotificationEmails.add(tempInstance);
                        con.CWS_75_Days_Sent__c = true;
                        contractsToUpdate.add(con);
                    }
        }//End of scope for loop
        if(seventyFiveDaysNotificationEmails.size() > 0){
            //Messaging.sendEmail(seventyFiveDaysNotificationEmails);
            Messaging.SendEmailResult[] emailResult = Messaging.sendEmail(seventyFiveDaysNotificationEmails, false);
            Database.saveResult[] srList = Database.update(contractsToUpdate,false);
            if(srList != null && !srList.isEmpty()){
                String errorString = '';
                for(Integer index = 0 ; index < srList.size() ; index ++){
                    if(!srList[index].isSuccess()){
                        csvBody += contractsToUpdate.get( index ).Id + ',';                        
                        string errorMsg = '';
                        for(Database.Error error : srList[index].getErrors()){
                            errorMsg += error.getMessage() + ',';
                        }
                        errorMsg = errorMsg.removeEnd(',');
                        csvBody += '"'+errorMsg + '"' + ','; 
                        csvBody += '\n';
                        buildErrorRecord(errorMsg,contractsToUpdate.get( index ).Id);
                    }
                }
                
                if(csvBody != null && csvBody != ''){
                    finalCsv = headerValue + csvBody;
                }
            }
        }
    }
    
    public void finish(Database.BatchableContext bc){
        if( finalCsv != null && finalCsv != ''){
            Set<Id> toUserSet = new Set<Id>();
            for(GroupMember groupMembers : [SELECT UserOrGroupId, GroupId, Id FROM GroupMember WHERE group.DeveloperName ='CWS_75_days_renewal_notification']){
                toUserSet.add(groupMembers.UserOrGroupId);
            }
            list<string> toAddresses = new list<string>();
            for(User userRecord : [SELECT id, Email FROM User WHERE Id IN: toUserSet]){
                toAddresses.add(userRecord.Email);
            }
            String csvname= 'Contract_Update_Errors.csv';
            Messaging.EmailFileAttachment csvAttc = new Messaging.EmailFileAttachment();
            csvAttc.setFileName(csvname);
            csvAttc.setBody(Blob.valueOf(finalCsv));    
            Messaging.SingleEmailMessage email =new Messaging.SingleEmailMessage();
            email.setSubject('Renewal Notification Error Logs');
            email.setToAddresses(toAddresses);
            email.setPlainTextBody('Find attached the error records for 75 days Renewal notification batch.' );
            email.setFileAttachments(new Messaging.EmailFileAttachment[]{csvAttc});
            try{
                Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
            }catch(Exception e){
                
            }
        }
    }
    
    public void buildErrorRecord(String errMessage, String recId){
        CWS_Error_Log__c err  = new CWS_Error_Log__c();
        err.CWS_Class_Name__c = 'CWS_75daysRenewalReminderEmailsBatch';
        err.CWS_Method_Name__c = 'execute';
        err.CWS_Error_Message__c = errMessage;
        err.CWS_Record_Id__c = recId;
        errRecsToInsert.add(err);
    }
    
    @TestVisible
    private Messaging.SingleEmailMessage createEmailMessage(String templateId, Contract conRecord, List<String> ccAddresses, List<Id> documentIds){
        OrgWideEmailAddress[] owea = [SELECT id FROM OrgWideEmailAddress WHERE  Address = 'renewals@connectwise.com'];
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.setTargetObjectId(conRecord.CWS_Bill_To_Contact__c);
        message.setSaveAsActivity(true);
        message.setTemplateID(templateId);
        message.setWhatId(conRecord.Id);  
        if(ccAddresses != null && ccAddresses.size() > 0){
            message.setCcAddresses(ccAddresses);    
        }
        if(documentIds != null && documentIds.size() > 0){
            message.setEntityAttachments(documentIds);
        }
        
        if(owea.size() > 0){
            message.setOrgWideEmailAddressId(owea.get(0).id);
        }
        return message;
    }
}