force-app/main/default/objects/Account/fields/CWS_Account_Restriction_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_Account_Restriction_Status__c</fullName>
    <inlineHelpText>Identifies if the Account requires additional validations or review. Reasons requiring restriction could be due to payment issues, lack of business, or other concerns.</inlineHelpText>
    <label>Account Restriction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Restriction</fullName>
                <default>true</default>
                <label>No Restriction</label>
            </value>
            <value>
                <fullName>Delinquent</fullName>
            </value>
            <value>
                <fullName>Payment Workout</fullName>
            </value>
            <value>
                <fullName>Credit Hold</fullName>
            </value>
            <value>
                <fullName>Shut Off</fullName>
            </value>
            <value>
                <fullName>Collection</fullName>
            </value>
            <value>
                <fullName>Blacklisted</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Suspect</fullName>
            </value>
            <value>
                <fullName>Out of Business</fullName>
            </value>
            <value>
                <fullName>Inactive Acquired</fullName>
            </value>
            <value>
                <fullName>Inactive Gone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>CWS_Payment_Terms__c</fullName>
    <inlineHelpText>Indicates the timeframe in which the Account is expected to pay for purchased items.</inlineHelpText>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due Upon Receipt</fullName>
            </value>
            <value>
                <fullName>Net 30</fullName>
            </value>
            <value>
                <fullName>Net 40</fullName>
            </value>
            <value>
                <fullName>Net 5</fullName>
            </value>
            <value>
                <fullName>Net 75</fullName>
            </value>
            <value>
                <fullName>Net 15</fullName>
            </value>
            <value>
                <fullName>Net 45</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Net 90</fullName>
            </value>
            <value>
                <fullName>Net 10</fullName>
            </value>
            <value>
                <fullName>Net 120</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CWS_Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>CWS_Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CWS_ManageIntegrationCallout_Test.cls
/* Class Name   : CWS_ManageIntegrationCallout_Test
 * Description  : Test Class for CWS_ManageIntegrationCallout Class
 * Created By   : Megha Shetty
 * Created On   : 8/10/2020
 *Modification Log
*------------------------------------------------------------------------------------------
*Developer                          Date            User Story              Description
*------------------------------------------------------------------------------------------
*/
@isTest(SeeAllData=false)
public class CWS_ManageIntegrationCallout_Test {
    @testSetup
    static void createTestData(){
        
        // Create Account
        Map<String, Object> accountFieldValues=new Map<String, Object>{
            'CWS_Payment_Terms__c'=>'Due Upon Receipt',
            'currencyIsoCode'=>'USD',
            'CWS_Account_Restriction_Status__c'=>'No Restriction'
            };
        Map<String, Object> accountFieldValues1=new Map<String, Object>{
            'CWS_Payment_Terms__c'=>'Due Upon Receipt',
            'currencyIsoCode'=>'USD',
            'SBQQ__PriceHoldEnd__c'=>Date.ValueOf('2020-01-01')
            };
        Account account1=CWS_UTLDataFactory.createAccount('TestAccount', accountFieldValues,true);
        //Account account2=CWS_UTLDataFactory.createAccount('TestAccount1', accountFieldValues1,true);
        
        Map<String, Object> contactFieldValues=new Map<String, Object>{
            'CWS_Primary_Contact__c'=>true
           
            };
        Contact primaryContact = CWS_UTLDataFactory.createContact('Mark', 'Anthony', account1.Id, contactFieldValues, true);
        //Contact primaryContact2 = CWS_UTLDataFactory.createContact('Mark', 'Gonzalase', account2.Id, contactFieldValues, true);
        
    }
    
    @isTest
    static void testQuoteCategorySearch(){
        
        Test.startTest();
        List<Contact> contactIds = [Select id from Contact];
        List<Id> Ids = new List<Id>();
        for(Contact c: contactIds){
            Ids.add(c.Id);
        }
        ID jobID = System.enqueueJob(new CWS_ManageIntegrationCallout(Ids,'Contact Id'));
        //CWS_ManageIntegrationCallout instance = new CWS_ManageIntegrationCallout();
        //CWS_ManageIntegrationCallout.manageIntegrationCallout(Ids,'Contact Id');
        //CWS_ManageIntegrationCallout.CWS_ManageIntegrationRequest.Id = String.valueOf(contactIds[0]);
        
        Test.stopTest();
    }

}