force-app/main/default/objects/Account/fields/CWS_Is_Distributor__c.field-meta.xml
<CustomField>
    <fullName>CWS_Is_Distributor__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies if the Account is a Distributor. If the field is checked as &quot;true&quot; then the Account is considered a Distributor.</inlineHelpText>
    <label>Is Distributor?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Is_Partner__c.field-meta.xml
<CustomField>
    <fullName>CWS_Is_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies if the Account has accepted a Quote from ConnectWise. If the field is checked as &quot;true&quot; then the Account has accepted a Quote and is considered a ConnectWise Partner.</inlineHelpText>
    <label>Is Partner?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Purchase_Order_Required__c.field-meta.xml
<CustomField>
    <fullName>CWS_Purchase_Order_Required__c</fullName>
    <inlineHelpText>Indicates if the Account needs a PO to process an invoice.</inlineHelpText>
    <label>PO Required?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CWS_Economic_Factor__c/CWS_Economic_Factor__c.object-meta.xml
<CustomObject>
    <description>Economic Factor used as a Lookup Object. Economic Factor will be multiplied with Product&apos;s List Price to get the Target Price.</description>
    <label>Economic Factor</label>
    <nameField>
        <displayFormat>EF-{0000}</displayFormat>
        <label>Economic Factor Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Economic Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CWS_Economic_Factor__c/fields/CWS_Category__c.field-meta.xml
<CustomField>
    <fullName>CWS_Category__c</fullName>
    <description>Category</description>
    <inlineHelpText>Category</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>CWS_Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Captures the Bill To Account associated to this Opportunity.</inlineHelpText>
    <label>Bill To (Account)</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>$Source.CWS_Route_to_Market__c</field>
            <operation>equals</operation>
            <value>Channel</value>
        </filterItems>
        <filterItems>
            <field>Account.CWS_Is_Distributor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Bill - To Account)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Distributor__c.field-meta.xml
<CustomField>
    <fullName>CWS_Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Captures the prospect&apos;s distributor Account.</inlineHelpText>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.CWS_Is_Distributor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Distributor)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>CWS_Legal_Entity__c</fullName>
    <inlineHelpText>Indicates the Legal Entity for this Opportunity based on the Bill To Account country.</inlineHelpText>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CW-AU</fullName>
                <label>ConnectWise Australia PTY LTD</label>
            </value>
            <value>
                <fullName>CW-CAD</fullName>
                <label>ConnectWise Canada Company</label>
            </value>
            <value>
                <fullName>CW-IN</fullName>
            </value>
            <value>
                <fullName>CW-UK</fullName>
                <label>ConnectWise LTD</label>
            </value>
            <value>
                <fullName>CW-US</fullName>
                <label>ConnectWise, LLC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <inlineHelpText>Captures the prospect&apos;s route to market; used for routing to BDR and PSE/SE pools.</inlineHelpText>
    <label>Route to Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/CWS_License_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_License_Type__c</fullName>
    <label>License Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/CWS_SKU_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_SKU_Type__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.CWS_SKU_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SKU Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Billing_Term__c.field-meta.xml
<CustomField>
    <fullName>CWS_Billing_Term__c</fullName>
    <inlineHelpText>Indicates the applicable billing term for the product</inlineHelpText>
    <label>Billing Term</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Bi-Annual</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Tri-Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Category__c.field-meta.xml
<CustomField>
    <fullName>CWS_Category__c</fullName>
    <inlineHelpText>Indicates the Category of the product</inlineHelpText>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Charge_Model__c.field-meta.xml
<CustomField>
    <fullName>CWS_Charge_Model__c</fullName>
    <description>Depicts Zuora charge Model</description>
    <inlineHelpText>Indicates the Charge Model of the product</inlineHelpText>
    <label>Charge Model</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discount-Fixed Amount</fullName>
            </value>
            <value>
                <fullName>Discount-Percentage</fullName>
            </value>
            <value>
                <fullName>Flat Fee Pricing</fullName>
            </value>
            <value>
                <fullName>Per Unit Pricing</fullName>
            </value>
            <value>
                <fullName>Overage Pricing</fullName>
            </value>
            <value>
                <fullName>Tiered Pricing</fullName>
            </value>
            <value>
                <fullName>Tiered with Overage Pricing</fullName>
            </value>
            <value>
                <fullName>Volume Pricing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Currencies__c.field-meta.xml
<CustomField>
    <fullName>CWS_Currencies__c</fullName>
    <inlineHelpText>Indicates the applicable currencies for the product</inlineHelpText>
    <label>Currencies</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_License_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_License_Type__c</fullName>
    <inlineHelpText>Indicates the License Type of the product</inlineHelpText>
    <label>License Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_LicenseType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Product_Family__c.field-meta.xml
<CustomField>
    <fullName>CWS_Product_Family__c</fullName>
    <inlineHelpText>Indicates Product Family of the product</inlineHelpText>
    <label>Product Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Product_Family</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <inlineHelpText>Indicates the applicable Route to Market for the product</inlineHelpText>
    <label>Route to Market</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Marketplace</fullName>
            </value>
            <value>
                <fullName>Marketplace Only</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_SKU_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_SKU_Type__c</fullName>
    <inlineHelpText>Indicates the SKU Type of the product</inlineHelpText>
    <label>SKU Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_SKU_TYPE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_Status__c</fullName>
    <inlineHelpText>Indicates the Status of the product</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>CWS_Sub_Category__c</fullName>
    <inlineHelpText>Indicates the Sub Category of the product</inlineHelpText>
    <label>Sub Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Sub_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_UOM__c.field-meta.xml
<CustomField>
    <fullName>CWS_UOM__c</fullName>
    <inlineHelpText>Indicates Unit of Measure for the product</inlineHelpText>
    <label>Unit of Measure</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_UOM_valueset</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/SBQQ__SubscriptionPricing__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionPricing__c</fullName>
    <description>Type of pricing to use for this subscription. &quot;None&quot; means this product is not a subscription.</description>
    <inlineHelpText>Indicates if it is fixed pricing or percentage of total pricing</inlineHelpText>
    <label>Subscription Pricing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Price</fullName>
            </value>
            <value>
                <fullName>Percent Of Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Term length of this subscription. Only applicable if the product is a subscription.</description>
    <inlineHelpText>Indicates the term (in months) for which the price has been listed for the product</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CWS_oliTriggerHelperTest.cls
/*Class Name: CWS_oliTriggerHelperTest
*Description: Test Class for OpportunityLineItem trigger
*Created By: Aditya
*Created On: 8/4/2020
*Modification Log
*------------------------------------------------------------------------------------------
*Developer              Date            User Story              Description
*------------------------------------------------------------------------------------------
*Aditya             8/4/2020                       
*/
@isTest
public class CWS_oliTriggerHelperTest {
	 @TestSetup
    static void makeData(){
        // Activate the Triggers
        CWS_UTLDataFactory.insertTriggerSwitch(new List<String>{'Account','Opportunity','OpportunityLineItem'}); 
       
        //Create Sold TO Account
        Map<String, Object> soldtoaccountFieldValues=new Map<String, Object>{
            'SBQQ__PriceHoldEnd__c'=>Date.ValueOf('2020-01-01'),
            'currencyIsoCode'=>'EUR',
            'CWS_Purchase_Order_Required__c'=>'Yes'
            };
        Account soldtoaccount=CWS_UTLDataFactory.createAccount('TestAccount', soldtoaccountFieldValues,true);

        //Create Distributor Account
        Map<String, Object> distributorAccountFieldValues=new Map<String, Object>{
            'SBQQ__PriceHoldEnd__c'=>Date.ValueOf('2020-01-01'),
            'currencyIsoCode'=>'EUR','CWS_Is_Partner__c'=>true,'CWS_Is_Distributor__c'=>true};
        Account[] distiAccounts=CWS_UTLDataFactory.createBulkAccounts('DistributorAccount{!i}', distributorAccountFieldValues,2,true);        
   
        // Create Distributr Reseller Records 
        CWS_UTLDataFactory.createDistributorReseller(soldtoaccount.Id,distiaccounts[0].Id, 'Distributor','Fulfillment', null, null, true);
        
        // Create Opportunity
        Map<String, Object> opportunityFields=new Map<String, Object>{
              'CWS_Route_to_Market__c'=>'Direct', 
                'CloseDate'=> Date.today(),
                'CWS_Bill_To_Account__c'=> distiaccounts[0].Id,
              'Type'=>'Commission Only',
                'CurrencyIsoCode'=>'USD',
                'CWS_Distributor__c'=>distiaccounts[0].Id,
                    'CWS_Legal_Entity__c'=>'CW-US',
                  'Pricebook2Id'=>Test.getStandardPricebookId(),
                  'RecordTypeId'=>CWS_ConstantClass.Opportunity_CommissionOnly
        }; 
        Opportunity opty=CWS_UTLDataFactory.createOpportunity('New Business Opty',soldtoaccount.Id,opportunityFields,true);
         // Create Products
        Map<String, Object> productFields=new Map<String, Object>{
              'CWS_Category__c'=>'Automate', 'SBQQ__SubscriptionPricing__c'=>'Fixed Price', 'SBQQ__SubscriptionTerm__c'=>12,
              'CWS_Charge_Model__c'=>'Per Unit Pricing', 
              'CWS_License_Type__c'=>'SaaS', 
              'CWS_Route_to_Market__c'=>'Direct', 
              'CWS_SKU_Type__c'=>'Package', 
              'CWS_UOM__c'=>'Each', 
              'CWS_Sub_Category__c'=>'License', 
              'CWS_Currencies__c'=>'USD;CAD;AUD;EUR;GBP', 
              'CWS_Status__c'=>'Active', 
              'CWS_Billing_Term__c'=>'Monthly', 
              'CWS_Product_Family__c'=>'BDR', 
              'CW_Product_Type__c'=>'Product', 
              'CWS_ChargeType__c'=>'Usage', 
              'CWS_Item_Revenue_Category__c'=>'Saas-Billing', 
              'CWS_Renewal_Type__c'=>'Opt-out', 
              'CWS_Product_Line__c'=>'None' ,
           	  'SBQQ__BillingType__c'=>'Advance',
              'SBQQ__PricingMethod__c'=>'List',
              'Description'=>'Test',
              'CWS_Description__c'=>'Test'
              
        };  
        List<Product2> lstProducts = new List<Product2>();
        Product2 product1=CWS_UTLDataFactory.createProduct('TestProduct1', 'SKU123',productFields,false);
        product1.SBQQ__SubscriptionType__c='Renewable';
        product1.SBQQ__SubscriptionBase__c='List';
        product1.CWS_Avg_Number_of_Days__c=10;
        product1.CWS_ChargeType__c='One-Time';
        product1.CWS_Provisioning_Eligibility__c='Immediate';
        lstProducts.add(product1); 
        insert lstProducts;
    	// Create Pricebook Entry
    	Pricebook2 pb = CWS_UTLDataFactory.createCustomPB(System.Label.CWS_ConnectwisePricebook,true);
        PricebookEntry Stdpbe1 = CWS_UTLDataFactory.createPBEwithPricebookId(Test.getStandardPricebookId(),product1.Id,1000.00,'USD', true);
        PricebookEntry pbe1 = CWS_UTLDataFactory.createPBEwithPricebookId(pb.id,product1.Id,1000.00,'USD', true);
        CWS_Economic_Factor__c ef = CWS_UTLDataFactory.createEconomicFactor('Automate', 'Product', 1, 'USD');
	    Map<String, Object> addFields01 = new Map<String,Object>{
           'CWS_Bill_To_Account__c'=>soldtoaccount.id, 
           'CWS_Route_to_Market__c'=>'Direct',
           'CWS_Quote_Type__c'=> CWS_ConstantClass.QUOTE_TYPE_RENEWAL
        };  
        SBQQ__Quote__c quote02 = CWS_UTLDataFactory.createQuote(soldtoaccount.id,opty.id,addFields01,true);       
	}
	
      @isTest
    static void testOLIAfterInsert(){
     	Test.startTest(); 
        Opportunity opp = [Select id, Pricebook2Id from Opportunity limit 1];
        Pricebook2 pb = [Select id from Pricebook2 where name =: System.Label.CWS_ConnectwisePricebook];
        PricebookEntry pbe = [Select id,UnitPrice from PricebookEntry where Pricebook2Id =: pb.id];   
       	opp.Pricebook2Id = pb.id;
        update opp;
        Product2 prod = [Select id from Product2 limit 1];
        prod.CWS_License_Type__c ='SaaS';
        prod.CWS_EF_Attribute__c  = 'Service';
        update prod;
        OpportunityLineItem oliObj = new OpportunityLineItem();
        oliObj.OpportunityId = opp.id;
        oliObj.PricebookEntryId = pbe.Id;
        //oliObj.Product2Id = prod.id;
        oliObj.UnitPrice = 0;
        oliObj.Quantity = 1;
        //oliObj.UnitPrice = pbe.UnitPrice;
        //oliObj.TotalPrice = 1000;
        oliObj.CWS_Commission_Only__c = true;
        oliObj.CWS_Transaction_Type__c = CWS_ConstantClass.QUOTE_TYPE_RENEWAL;
        insert oliObj;
        
        system.assertEquals(true, oliObj !=null);
        Test.stopTest();
    }
    
	  @isTest
    static void testOLI(){
      Test.startTest();  
        Opportunity opp = [Select id,Pricebook2Id from Opportunity limit 1];
     
        Product2 prod = [Select id from Product2 limit 1];
        Pricebook2 pb = [Select id from Pricebook2 where name =: System.Label.CWS_ConnectwisePricebook];
       	opp.Pricebook2Id = pb.id;
        update opp;
        PricebookEntry pbe = [Select id,UnitPrice from PricebookEntry where Pricebook2Id =: pb.id];   
        OpportunityLineItem oliObj = new OpportunityLineItem();
        oliObj.OpportunityId = opp.id;
        //oliObj.Product2Id = prod.id;
        oliObj.Quantity = 1;
        //oliObj.TotalPrice = 1000;
        oliObj.PricebookEntryId = pbe.Id;
        oliObj.UnitPrice = pbe.UnitPrice;
        oliObj.CWS_Commission_Only__c = true;
        insert oliObj;
        oliObj.Quantity = 2;
        oliObj.CWS_ACVLine__c = 20;
        oliObj.CWS_NetTotal__c =30;
        update oliObj;
      Test.stopTest();
        CWS_OpportunityLineItemTriggerHandler obj = new CWS_OpportunityLineItemTriggerHandler();
        Map<Id, OpportunityLineItem> newItems = new Map<Id, OpportunityLineItem>();
        obj.BeforeDelete(newItems);
        obj.AfterInsert(newItems);
        obj.AfterUpdate(newItems , newItems);
        obj.AfterDelete(newItems);
        obj.AfterUndelete(newItems);
    }
      @isTest
    static void testOLI2(){
      Test.startTest();  
        Opportunity opp = [Select id from Opportunity limit 1];
        Product2 prod = [Select id from Product2 limit 1];
        prod.CWS_License_Type__c ='SaaS';
        prod.CWS_EF_Attribute__c  = 'Service';
        update prod;
        OpportunityLineItem oliObj = new OpportunityLineItem();
        oliObj.OpportunityId = opp.id;
        oliObj.Product2Id = prod.id;
        oliObj.Quantity = 1;
        oliObj.TotalPrice = 1000;
        oliObj.CWS_Commission_Only__c = true;
        insert oliObj;
      Test.stopTest();
    }
    
}