force-app/main/default/objects/Account/fields/CWS_Access_to_CW_University__c.field-meta.xml
<CustomField>
    <fullName>CWS_Access_to_CW_University__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates that Account is to be provided access to CW University.</inlineHelpText>
    <label>Access to CW University?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Is_Partner__c.field-meta.xml
<CustomField>
    <fullName>CWS_Is_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies if the Account has accepted a Quote from ConnectWise. If the field is checked as &quot;true&quot; then the Account has accepted a Quote and is considered a ConnectWise Partner.</inlineHelpText>
    <label>Is Partner?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_SSO_GUID__c.field-meta.xml
<CustomField>
    <fullName>CWS_SSO_GUID__c</fullName>
    <description>Field for storing comma-delimited SSO Partner IDs.</description>
    <inlineHelpText>Supports Single Sign-On integration with Manage</inlineHelpText>
    <label>SSO Tenant (Partner) ID</label>
    <length>2600</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CWS_Access_to_CW_University__c.field-meta.xml
<CustomField>
    <fullName>CWS_Access_to_CW_University__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Access to CW University?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CWS_Active__c.field-meta.xml
<CustomField>
    <fullName>CWS_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CWS_Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>CWS_Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CWS_SSO_Endpoints__c/CWS_SSO_Endpoints__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom endpoint settings for CWS_SSOUpdatedAccountContacts class</description>
    <label>SSO Endpoints</label>
</CustomObject>

force-app/main/default/objects/CWS_SSO_Endpoints__c/fields/CWS_SSO_Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>CWS_SSO_Client_Secret__c</fullName>
    <defaultValue>&quot;gWl*GFqCgzGiJAu*936znh$gT0ro*n&quot;</defaultValue>
    <description>SSO client secret for OAuth with STS server.</description>
    <label>SSO Client Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CWS_SSO_Endpoints__c/fields/CWS_SSO_Error_Notification_Email__c.field-meta.xml
<CustomField>
    <fullName>CWS_SSO_Error_Notification_Email__c</fullName>
    <defaultValue>&quot;masterdata@connectwise.com&quot;</defaultValue>
    <description>SSO error notification email</description>
    <label>SSO Error Notification Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CWS_SSO_Endpoints__c/fields/CWS_SSO_Integration_Active__c.field-meta.xml
<CustomField>
    <fullName>CWS_SSO_Integration_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Boolean switch to turn the SSO integration on and off</description>
    <label>SSO Integration Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CWS_SSO_Endpoints__c/fields/CWS_SSO_SF_Gateway__c.field-meta.xml
<CustomField>
    <fullName>CWS_SSO_SF_Gateway__c</fullName>
    <defaultValue>&quot;https://sf-gateway.myconnectwise.net/v1/connectwise/partners/provision&quot;</defaultValue>
    <description>SSO Salesforce gateway endpoint for retrieving the user SSO Id.</description>
    <label>SSO SF Gateway</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/CWS_SSO_Endpoints__c/fields/CWS_SSO_Token_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>CWS_SSO_Token_Endpoint__c</fullName>
    <defaultValue>&quot;https://auth.connectwise.com/connect/token&quot;</defaultValue>
    <description>URL for SSO OAUTH Token Server</description>
    <label>SSO Token Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/CWS_SSO_Endpoints__c/fields/CWS_SSO_Token_Redirect__c.field-meta.xml
<CustomField>
    <fullName>CWS_SSO_Token_Redirect__c</fullName>
    <defaultValue>&quot;https://connectwise20.my.salesforce.com/apex/oauthv2&quot;</defaultValue>
    <description>SSO redirect URL to pass to Token Server</description>
    <label>SSO Token Redirect</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/CWS_SSOUpdatedAccountContacts_Test.cls
/*Class Name: CWS_SSOUpdatedAccountContacts_Test
*Description: Apex test class to test CW Home SSO account provisioning
*Created By: Carl Shahan
*Created On: 08/13/2020
*Modification Log
*------------------------------------------------------------------------------------------
*Developer   Date       User Story    Description
*------------------------------------------------------------------------------------------
*Carl Shahan 09/13/2020 CWH-996       Apex test class to test CW Home SSO account provisioning
*/

@isTest
private class CWS_SSOUpdatedAccountContacts_Test {

    private class SuccessfulResponse implements HttpCalloutMock {
        /**
        * @description mock http response that returns successful message and status code
        * @param request
        * @return HttpResponse response 
        */
        public HTTPResponse respond(HttpRequest request) {

            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{"partnerId":"5f515856bab09f000172e5cc","userId":"5f515856c8192caeb31b6065"}');
            response.setStatusCode(200);
            return response;
        }
    }

    private class ErrorResponse implements HttpCalloutMock {
        /**
        * @description mock http response that returns error message and status code
        * @param request
        * @return HttpResponse response 
        */
        public HTTPResponse respond(HttpRequest request) {

            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{"code":"InvalidObject","message":"PartnerProvisioningRequest object is invalid","errors":[{"code":"InvalidField","message":"Partner 60c25cbd08ddf80001c0cace already exists and is linked to a Salesforce account.","resource":"PartnerProvisioningRequest","field":null}]}');
            response.setStatusCode(400);
            return response;
        }
    }
       
    private static Account createAccountWithContact() {

        CWS_SSO_Endpoints__c customSettings = new CWS_SSO_Endpoints__c();

        customSettings.CWS_SSO_Client_Secret__c = '12345678910zWcVuxdyOfVoXuPxJiyxo';
        customSettings.CWS_SSO_Error_Notification_Email__c = 'cshahan@connectwise.com';
        customSettings.CWS_SSO_Integration_Active__c = true;
        customSettings.CWS_SSO_SF_Gateway__c = 'https://dev-na-latest.sf-gateway.connectwisedev.com/v1/connectwise/partners/provision';
        customSettings.CWS_SSO_Token_Endpoint__c = 'https://sts.connectwisedev.com/connect/token';
        customSettings.CWS_SSO_Token_Redirect__c = 'https://connectwise20--csdev.lightning.force.com/apex/oauthv2';

        insert customSettings;
           
        Account account = new Account(

            Name = 'AIOITS Test Account',
            Phone = '727 777 3625',
            BillingCountry = 'United States',
            BillingState = 'Florida',
            BillingPostalCode = '33715',
            CWS_SSO_GUID__c = null,
            CWS_Is_Partner__c = true,
            CWS_Access_to_CW_University__c = false
        );

        insert account;

        List<Contact> contactList = new List<Contact>();
        contactList.add(new Contact(
            AccountId = account.Id,
            CWS_Active__c = true,
            CWS_Primary_Contact__c = true,
            FirstName = 'Roger',
            LastName = 'Rogers',
            Phone = '727 777 3625',
            Email = 'roger.rogers@aioitssystems.com.invalid'
        ));

        insert contactList;

        return account;
    }

    @isTest static void postAccountContactData() {
        
        // Create the Account and Contact needed for the SOQL query 
        Account account = createAccountWithContact();
        Integer statusCode = 404;
        
        Test.setMock(HttpCalloutMock.class, new SuccessfulResponse());

        Test.startTest();
            CWS_SSOUpdatedAccountContacts.postContactData(account.Id);
            statusCode = 200;
        Test.stopTest();

        System.assertEquals(200, statusCode);
    }
    
    @isTest static void postAccountContactDataError() {
        
        // Create the Account and Contact needed for the SOQL query 
        Account account = createAccountWithContact();
        Integer statusCode = 404;

        Test.setMock(HttpCalloutMock.class, new ErrorResponse());

        Test.startTest();
            CWS_SSOUpdatedAccountContacts.postContactData(account.Id);
            statusCode = 400;
        Test.stopTest();

        System.assertEquals(400, statusCode);
    }
}