force-app/main/default/objects/Account/fields/CWS_Is_Partner__c.field-meta.xml
<CustomField>
    <fullName>CWS_Is_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies if the Account has accepted a Quote from ConnectWise. If the field is checked as &quot;true&quot; then the Account has accepted a Quote and is considered a ConnectWise Partner.</inlineHelpText>
    <label>Is Partner?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>CWS_Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Bill To Account for the Contract</description>
    <inlineHelpText>Bill To Account for the Contract</inlineHelpText>
    <label>Bill To (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>CWS_Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Cancelled Flag indicates all the subscriptions under a contract got terminated.</description>
    <inlineHelpText>Indicates that all the Subscriptions in this contract got terminated.</inlineHelpText>
    <label>Canceled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Contract_ACV__c.field-meta.xml
<CustomField>
    <fullName>CWS_Contract_ACV__c</fullName>
    <description>Contract ACV value which will be a Roll-up of all the subscriptions present within the Contract.</description>
    <label>Contract ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Master__c.field-meta.xml
<CustomField>
    <fullName>CWS_Master__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Contracts with Master? as TRUE, indicates only legacy records with $value for commitment.</description>
    <inlineHelpText>Contracts with Master? as TRUE, indicates only legacy records with $value for commitment.</inlineHelpText>
    <label>Master</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <description>Route to market of the Contract.</description>
    <label>Route to Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_Status__c</fullName>
    <description>Contract Status
If Cancelled flag = TRUE, then Status = Terminated
If Start date &lt;= Today and End date &gt;= Today, Status = Active
If Start date &gt; Today, then Status = Inactive
If End date &lt; Today and Cancelled Flag is False, then Status = Expired</description>
    <formula>IF(CWS_Cancelled__c=TRUE, &apos;Terminated&apos;,
IF(SBQQ__Evergreen__c=TRUE,
IF(CWS_Master__c=true,IF(CWS_Legacy_Formula_Key__c!=null,&apos;Expired&apos;,IF(StartDate&lt;=TODAY(),&apos;Active&apos;,&apos;Inactive&apos;)),IF(StartDate&lt;=TODAY(),&apos;Active&apos;,&apos;Inactive&apos;)),
IF(AND(StartDate&lt;=TODAY(), EndDate&gt;=TODAY()), &apos;Active&apos;,
IF(StartDate&gt;TODAY(), &apos;Inactive&apos;,
IF(EndDate&lt;TODAY(), &apos;Expired&apos;,&apos;&apos;)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If Cancelled flag = TRUE, then Status = Terminated
If Start date &lt;= Today and End date &gt;= Today, Status = Active
If Start date &gt; Today, then Status = Inactive
If End date &lt; Today and Cancelled Flag is False, then Status = Expired</inlineHelpText>
    <label>Contract Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CWS_Distributor_Reseller__c/CWS_Distributor_Reseller__c.object-meta.xml
<CustomObject>
    <description>This is the Object to maintain the Relationship between the Distributor/Reseller and the End Customer Account.</description>
    <label>Distributor/Reseller</label>
    <nameField>
        <label>Distributor/Reseller  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributors/Resellers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CWS_Distributor_Reseller__c/fields/CWS_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Partially Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>CWS_Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Captures the Bill To Account associated to this Opportunity.</inlineHelpText>
    <label>Bill To (Account)</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>$Source.CWS_Route_to_Market__c</field>
            <operation>equals</operation>
            <value>Channel</value>
        </filterItems>
        <filterItems>
            <field>Account.CWS_Is_Distributor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Bill - To Account)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Master__c.field-meta.xml
<CustomField>
    <fullName>CWS_Master__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This indicates that the opportunity will have the legacy model of minimum commitment maintained as $value at Account level. This is not recommended; please contact System Administrator for help.</inlineHelpText>
    <label>Master?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <inlineHelpText>Captures the prospect&apos;s route to market; used for routing to BDR and PSE/SE pools.</inlineHelpText>
    <label>Route to Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Store_Bill_To_Id__c.field-meta.xml
<CustomField>
    <fullName>CWS_Store_Bill_To_Id__c</fullName>
    <inlineHelpText>Captures the Bill To ID for this Opportunity.</inlineHelpText>
    <label>Store Bill To Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CWS_AccountMRRBatch_Test.cls
/*Class Name: CWS_AccountMRRBatch_Test
*Description: Batch Class to Calculate MRR
*Created By: Abhishek
*Created On: 06/29/2020
*Modification Log
*------------------------------------------------------------------------------------------
*Developer              Date            User Story              Description
*------------------------------------------------------------------------------------------
*Abhishek               06/25/2020      BED-5141              Calculate MRR
*/
@isTest(SeeAllData=false)
public class CWS_AccountMRRBatch_Test {
    
   @testSetup static void createTestData(){
        //create custom setting data
        CWS_UTLDataFactory.insertTriggerSwitch(new List<String>{'CWS_Distributor_Reseller__c','Quote','SBQQ__QuoteDocument__c'});    
        
        //Create Sold TO Account
        Map<String, Object> soldtoaccountFieldValues=new Map<String, Object>{
            'SBQQ__PriceHoldEnd__c'=>Date.ValueOf('2020-01-01'),
            'currencyIsoCode'=>'EUR',
            'CWS_Is_Partner__c'=>TRUE};
        Account soldtoaccount=CWS_UTLDataFactory.createAccount('TestAccount', soldtoaccountFieldValues,true);
        
        
        Opportunity opp = CWS_UTLDataFactory.createOpportunity('optyName',soldtoaccount.Id, new Map<String, Object>{'StageName'=>'Closed Won','CloseDate'=>System.today(),'CWS_Bill_To_Account__c'=>soldtoaccount.Id,'CWS_Route_to_Market__c'=>'Direct','CWS_Store_Bill_To_Id__c' => soldtoaccount.Id,'CWS_Master__c' => true}, true);
    
       Map<String, Object> contractFieldsDefaultValues = new Map<String, Object>{
            'StartDate' => date.today() - 1,
            'ContractTerm' => 12,
            'CurrencyIsoCode' => 'USD',
            'status' => 'Draft'};
       Contract Cntr = CWS_UTLDataFactory.createContract(soldtoaccount.Id,contractFieldsDefaultValues, true);
       
    }

    @isTest static void MRRCalculation(){

        Test.starttest();
        
        list<Opportunity> oppObj = [Select id from opportunity limit 1];
        list<Account> accObj = [Select id from Account limit 1];
        List<id> accids = new List<id>();
        accids.add(accObj[0].ID);
       // system.debug('test1--');
        List<Contract> Cntr = [SELECT Id, currencyISOCode,CWS_Cancelled__c,CWS_Status__c,StartDate,AccountId,SBQQ__Opportunity__c,EndDate,CWS_Contract_ACV__c from Contract]; 
         
        Cntr[0].AccountId = accObj[0].id;
        Cntr[0].SBQQ__Opportunity__c = oppObj[0].id;
        Cntr[0].CWS_Contract_ACV__c = 1000;
        Cntr[0].CWS_Cancelled__c = FALSE;
        //system.debug('test3--' + Cntr[0].CWS_Status__c+' '+Cntr[0].StartDate+' __ '+Cntr[0].CWS_Cancelled__c+ ' __ '+Cntr[0].EndDate);
        
        update Cntr;
        //system.debug('test2--');
        
        Id batchId = Database.executeBatch(new CWS_AccountMRRCalculationBatch(accids), 50);
        Id batchId2 = Database.executeBatch(new CWS_AccountMRRCalculationBatch(), 50);
    
        Test.stopTest();
    }
}