force-app/main/default/objects/Account/fields/CWS_Is_Distributor__c.field-meta.xml
<CustomField>
    <fullName>CWS_Is_Distributor__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies if the Account is a Distributor. If the field is checked as &quot;true&quot; then the Account is considered a Distributor.</inlineHelpText>
    <label>Is Distributor?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Is_Partner__c.field-meta.xml
<CustomField>
    <fullName>CWS_Is_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies if the Account has accepted a Quote from ConnectWise. If the field is checked as &quot;true&quot; then the Account has accepted a Quote and is considered a ConnectWise Partner.</inlineHelpText>
    <label>Is Partner?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Purchase_Order_Required__c.field-meta.xml
<CustomField>
    <fullName>CWS_Purchase_Order_Required__c</fullName>
    <inlineHelpText>Indicates if the Account needs a PO to process an invoice.</inlineHelpText>
    <label>PO Required?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>CWS_Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Captures the Bill To Account associated to this Opportunity.</inlineHelpText>
    <label>Bill To (Account)</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>$Source.CWS_Route_to_Market__c</field>
            <operation>equals</operation>
            <value>Channel</value>
        </filterItems>
        <filterItems>
            <field>Account.CWS_Is_Distributor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Bill - To Account)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Distributor__c.field-meta.xml
<CustomField>
    <fullName>CWS_Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Captures the prospect&apos;s distributor Account.</inlineHelpText>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.CWS_Is_Distributor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Distributor)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>CWS_Legal_Entity__c</fullName>
    <inlineHelpText>Indicates the Legal Entity for this Opportunity based on the Bill To Account country.</inlineHelpText>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CW-AU</fullName>
                <label>ConnectWise Australia PTY LTD</label>
            </value>
            <value>
                <fullName>CW-CAD</fullName>
                <label>ConnectWise Canada Company</label>
            </value>
            <value>
                <fullName>CW-IN</fullName>
            </value>
            <value>
                <fullName>CW-UK</fullName>
                <label>ConnectWise LTD</label>
            </value>
            <value>
                <fullName>CW-US</fullName>
                <label>ConnectWise, LLC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <inlineHelpText>Captures the prospect&apos;s route to market; used for routing to BDR and PSE/SE pools.</inlineHelpText>
    <label>Route to Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Ship_To_Account__c.field-meta.xml
<CustomField>
    <fullName>CWS_Ship_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Captures the Ship To Account associated to this Opportunity.</inlineHelpText>
    <label>Ship To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Ship To Account)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/CWS_Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>CWS_Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Order (Bill-To Account)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/CWS_LegacyKey__c.field-meta.xml
<CustomField>
    <fullName>CWS_LegacyKey__c</fullName>
    <description>Legacy Key copied from the related quote</description>
    <externalId>true</externalId>
    <label>Legacy Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/CWS_Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>CWS_Legal_Entity__c</fullName>
    <label>Legal Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Legal_Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/CWS_Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_Quote_Type__c</fullName>
    <description>Quote type value twinned from the Quote record - to be used for backend purposes only</description>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Renewal with Change</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <description>The route to market information copied from Quote</description>
    <inlineHelpText>The route to market information copied from Quote</inlineHelpText>
    <label>Route to Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/CWS_Ship_To_Account__c.field-meta.xml
<CustomField>
    <fullName>CWS_Ship_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Ship To Account)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CWS_legacyQuoteOrderCreationBatchTest.cls
/*Class Name: CWS_legacyQuoteOrderCreationBatchTest
*Description: Test Class for legacy Quote and Order creation batch
*Created By: Aditya
*Created On: 8/3/2020
*Modification Log
*------------------------------------------------------------------------------------------
*Developer              Date            User Story              Description
*------------------------------------------------------------------------------------------
*Aditya             8/3/2020                       
*/
@isTest
public class CWS_legacyQuoteOrderCreationBatchTest {
	 @TestSetup
    static void makeData(){
        // Activate the Triggers
        CWS_UTLDataFactory.insertTriggerSwitch(new List<String>{'Account','Opportunity','Quote','Order'}); 
       
        //Create Sold TO Account
        Map<String, Object> soldtoaccountFieldValues=new Map<String, Object>{
            'SBQQ__PriceHoldEnd__c'=>Date.ValueOf('2020-01-01'),
            'currencyIsoCode'=>'EUR',
            'CWS_Purchase_Order_Required__c'=>'Yes'
            };
        Account soldtoaccount=CWS_UTLDataFactory.createAccount('TestAccount', soldtoaccountFieldValues,true);

        //Create Distributor Account
        Map<String, Object> distributorAccountFieldValues=new Map<String, Object>{
            'SBQQ__PriceHoldEnd__c'=>Date.ValueOf('2020-01-01'),
            'currencyIsoCode'=>'EUR','CWS_Is_Partner__c'=>true,'CWS_Is_Distributor__c'=>true};
        Account[] distiAccounts=CWS_UTLDataFactory.createBulkAccounts('DistributorAccount{!i}', distributorAccountFieldValues,2,true);        
   
        // Create Distributr Reseller Records 
        CWS_UTLDataFactory.createDistributorReseller(soldtoaccount.Id,distiaccounts[0].Id, 'Distributor','Fulfillment', null, null, true);
        
        // Create Opportunity
        Map<String, Object> opportunityFields=new Map<String, Object>{
              'CWS_Route_to_Market__c'=>'Direct', 
                'CloseDate'=> Date.today(),
                'CWS_Bill_To_Account__c'=> distiaccounts[0].Id,
              'Type'=>'New',
                'CurrencyIsoCode'=>'USD',
                'CWS_Distributor__c'=>distiaccounts[0].Id,
                 'CWS_Route_to_Market__c'=>'Channel',
                    'CWS_Legal_Entity__c'=>'CW-US'
        }; 
        Opportunity opty=CWS_UTLDataFactory.createOpportunity('New Business Opty',soldtoaccount.Id,opportunityFields,true);
                
        //Create New business Quote record
        Map<String, Object> quoteFields=new Map<String,Object>{
            'SBQQ__Status__c'=>'Approved', 
            'CWS_Quote_Type__c'=>'New Business', 
            'SBQQ__Distributor__c'=>distiAccounts[0].Id,
            'CWS_Bill_To_Account__c'=> soldtoaccount.Id,
            'CWS_Ship_To_Account__c'=>soldtoaccount.Id
        };
        SBQQ__Quote__c quote1=CWS_UTLDataFactory.createQuote(soldtoaccount.Id,opty.Id, quoteFields, true);

    }
    @istest
    static void testBatch(){
        List<SBQQ__Quote__c> quoteList = new List<SBQQ__Quote__c>();
        
        SBQQ__Quote__c quoteObj = [Select id,SBQQ__Primary__c,SBQQ__PricebookId__c,SBQQ__Ordered__c, CWS_LegacyKey__c from SBQQ__Quote__c limit 1];
            quoteObj.SBQQ__Primary__c=true;
            quoteObj.SBQQ__PricebookId__c=Test.getStandardPricebookId();
			quoteObj.SBQQ__Status__c='Accepted';
        	quoteObj.CWS_LegacyKey__c='test1245';
        	quoteObj.SBQQ__ExpirationDate__c = System.today();
        
        	quoteObj.SBQQ__LastCalculatedOn__c = System.Today();
        quoteObj.CWS_Recalculation_DateTime__c = System.Today() - 1;
        quoteList.add(quoteObj);
        update quoteList;
        Test.startTest();
        CWS_LegacyOrderCreationBatch batch = new CWS_LegacyOrderCreationBatch();
        Database.QueryLocator ql = batch.start(null);
		batch.execute(null,quoteList);
		batch.Finish(null);
        //Database.executeBatch(batch);
        Test.stopTest();
    } 
	    
    @istest
    static void testBatch2(){
        List<Id> quoteList = new List<Id>();
        List<SBQQ__Quote__c> quote = new List<SBQQ__Quote__c>();
        SBQQ__Quote__c quoteObj = [Select id,SBQQ__Primary__c,SBQQ__PricebookId__c,SBQQ__Ordered__c, CWS_LegacyKey__c from SBQQ__Quote__c limit 1];
            quoteObj.SBQQ__Primary__c=true;
            quoteObj.SBQQ__PricebookId__c=Test.getStandardPricebookId();
			quoteObj.SBQQ__Status__c='Accepted';
        	quoteObj.CWS_LegacyKey__c='test1245';
        	quoteObj.SBQQ__ExpirationDate__c = System.today();
        	quoteObj.SBQQ__LastCalculatedOn__c = System.Today();
        quoteObj.CWS_Recalculation_DateTime__c = System.Today() - 1;
        update quoteObj;
      	quoteList.add(quoteObj.id);
        quote.add(quoteObj);
        Test.startTest();
        CWS_LegacyOrderCreationBatch batch = new CWS_LegacyOrderCreationBatch(quoteList);
        Database.QueryLocator ql = batch.start(null);
		batch.execute(null,quote);
		batch.Finish(null);
        //Database.executeBatch(batch);
        Test.stopTest();
    }
     @istest
    static void testBatch3(){
        List<Id> quoteList = new List<Id>();
        List<SBQQ__Quote__c> quote = new List<SBQQ__Quote__c>();
        SBQQ__Quote__c quoteObj = [Select id,SBQQ__Primary__c,SBQQ__PricebookId__c,SBQQ__Ordered__c, CWS_LegacyKey__c from SBQQ__Quote__c limit 1];
            quoteObj.SBQQ__Primary__c=true;
            quoteObj.SBQQ__PricebookId__c=Test.getStandardPricebookId();
			quoteObj.SBQQ__Status__c='Accepted';
        	quoteObj.CWS_LegacyKey__c='test1245';
        	quoteObj.SBQQ__ExpirationDate__c = System.today();
        update quoteObj;
      	quoteList.add(quoteObj.id);
        quote.add(quoteObj);
        Test.startTest();
        CWS_LegacyQuoteSync batch = new CWS_LegacyQuoteSync();
        Database.QueryLocator ql = batch.start(null);
		batch.execute(null,quote);
		batch.Finish(null);
        //Database.executeBatch(batch);
        Test.stopTest();
    }
    
    
     @istest
    static void testBatch4(){
        List<Id> quoteList = new List<Id>();
        List<SBQQ__Quote__c> quote = new List<SBQQ__Quote__c>();
        SBQQ__Quote__c quoteObj = [Select id,SBQQ__Primary__c,SBQQ__PricebookId__c,SBQQ__Ordered__c, CWS_LegacyKey__c from SBQQ__Quote__c limit 1];
            quoteObj.SBQQ__Primary__c=true;
            quoteObj.SBQQ__PricebookId__c=Test.getStandardPricebookId();
			quoteObj.SBQQ__Status__c='Accepted';
        	quoteObj.CWS_LegacyKey__c='test1245';
        	quoteObj.SBQQ__ExpirationDate__c = System.today();
        update quoteObj;
      	quoteList.add(quoteObj.id);
        quote.add(quoteObj);
        Test.startTest();
        CWS_LegacyQuoteSync batch = new CWS_LegacyQuoteSync(quoteList);
        Database.QueryLocator ql = batch.start(null);
		batch.execute(null,quote);
		batch.Finish(null);
        //Database.executeBatch(batch);
        Test.stopTest();
    }
}