force-app/main/default/objects/Account/fields/CWS_BA_Agreement_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_BA_Agreement_Status__c</fullName>
    <label>BA Agreement Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Is_Distributor__c.field-meta.xml
<CustomField>
    <fullName>CWS_Is_Distributor__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies if the Account is a Distributor. If the field is checked as &quot;true&quot; then the Account is considered a Distributor.</inlineHelpText>
    <label>Is Distributor?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Is_Partner__c.field-meta.xml
<CustomField>
    <fullName>CWS_Is_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies if the Account has accepted a Quote from ConnectWise. If the field is checked as &quot;true&quot; then the Account has accepted a Quote and is considered a ConnectWise Partner.</inlineHelpText>
    <label>Is Partner?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_MSA_Agreement_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_MSA_Agreement_Status__c</fullName>
    <label>MSA Agreement Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_NDA_Agreement__c.field-meta.xml
<CustomField>
    <fullName>CWS_NDA_Agreement__c</fullName>
    <label>NDA Agreement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_NDA_Agreement_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_NDA_Agreement_Status__c</fullName>
    <label>NDA Agreement Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Need_Recurring__c.field-meta.xml
<CustomField>
    <fullName>CWS_Need_Recurring__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates if the Account needs a PO every month to process recurring invoices.</inlineHelpText>
    <label>Need Recurring PO</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_BA_Agreement__c.field-meta.xml
<CustomField>
    <fullName>CWS_BA_Agreement__c</fullName>
    <label>BA Agreement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>CWS_Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Bill To Account for the Contract</description>
    <inlineHelpText>Bill To Account for the Contract</inlineHelpText>
    <label>Bill To (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_MSA_Agreement__c.field-meta.xml
<CustomField>
    <fullName>CWS_MSA_Agreement__c</fullName>
    <label>MSA Agreement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_OF_Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>CWS_OF_Signed_Date__c</fullName>
    <description>OF Signed Date</description>
    <inlineHelpText>OF Signed Date</inlineHelpText>
    <label>OF Signed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Quote_SubType__c.field-meta.xml
<CustomField>
    <fullName>CWS_Quote_SubType__c</fullName>
    <description>This field is mandatory for selection if the transaction reason is credit/rebill</description>
    <label>Amend Quote SubType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Rebill</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_Quote_Type__c</fullName>
    <description>Quote Type</description>
    <inlineHelpText>Quote Type</inlineHelpText>
    <label>Quote Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Renewal with Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Reseller_Account__c.field-meta.xml
<CustomField>
    <fullName>CWS_Reseller_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Reseller Account)</relationshipLabel>
    <relationshipName>Contracts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <description>Route to market of the Contract.</description>
    <label>Route to Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Transaction_Reason__c.field-meta.xml
<CustomField>
    <fullName>CWS_Transaction_Reason__c</fullName>
    <description>This field determines the transaction reason of the quote which is realted to this contract.</description>
    <label>Transaction Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Transaction_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CWS_Bypass_Settings__c/CWS_Bypass_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to bypass Workflow Rules, Validation Rules, Process Builder Flows, Triggers etc.</description>
    <label>Bypass Settings</label>
</CustomObject>

force-app/main/default/objects/CWS_Bypass_Settings__c/fields/CWS_Bypass_Objects__c.field-meta.xml
<CustomField>
    <fullName>CWS_Bypass_Objects__c</fullName>
    <description>The names of the meta data are captured here.</description>
    <inlineHelpText>Full API names followed by &apos;;&apos; including the managed package prefix if applicable of objects you need to bypass WF rules, Validation Rules, Process Builders. If you need to bypass multiple objects, concatenate one after another. Eg: Account;Contact;</inlineHelpText>
    <label>Bypass Objects</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CWS_Bypass_Settings__c/fields/CWS_Validation_Rules_Disabled__c.field-meta.xml
<CustomField>
    <fullName>CWS_Validation_Rules_Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Please check this box if you would like to disable validation rules for the objects in the Bypass Objects field.</inlineHelpText>
    <label>Validation Rules Disabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>CWS_Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Captures the Bill To Account associated to this Opportunity.</inlineHelpText>
    <label>Bill To (Account)</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>$Source.CWS_Route_to_Market__c</field>
            <operation>equals</operation>
            <value>Channel</value>
        </filterItems>
        <filterItems>
            <field>Account.CWS_Is_Distributor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Bill - To Account)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <inlineHelpText>Captures the prospect&apos;s route to market; used for routing to BDR and PSE/SE pools.</inlineHelpText>
    <label>Route to Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Transaction_Reason__c.field-meta.xml
<CustomField>
    <fullName>CWS_Transaction_Reason__c</fullName>
    <label>Transaction Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Transaction_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CWS_QueueableAcceptRenewalQuotes_Test.cls
/*Class Name: CWS_QueueableAcceptRenewalQuotes_Test
*Description: Test Class for CWS_QueueableAcceptRenewalQuotes
*Created By: Manoj
*Created On: 4/7/2020
*Modification Log
*------------------------------------------------------------------------------------------
*Developer              Date            User Story              Description
*------------------------------------------------------------------------------------------
*Manoj                 24/08/2020        BED-3696              Quote Cloning
*/
@istest(seealldata = false)
public class CWS_QueueableAcceptRenewalQuotes_Test {
		
    	@testsetup
        static void createTestData(){
      //create custom setting data
        CWS_UTLDataFactory.insertTriggerSwitch(new List<String>{'Opportunity','Quote','SBQQ__QuoteDocument__c','CWS_Approval_Trigger__c'});   
            CWS_Bypass_Settings__c  bypassValidate = new CWS_Bypass_Settings__c  ();
        bypassValidate.CWS_Validation_Rules_Disabled__c = true;
        bypassValidate.CWS_Bypass_Objects__c  = 'SBQQ__QuoteDocument__c;SBQQ__Quote__c;';
        insert bypassValidate;         
        //Create Sold TO Account
        Map<String, Object> soldtoaccountFieldValues=new Map<String, Object>{
            'SBQQ__PriceHoldEnd__c'=>Date.ValueOf('2020-01-01'),
            'currencyIsoCode'=>'EUR',
             'CWS_Is_Distributor__c'=>true,
             'CWS_BA_Agreement__c'=>'TestBA',
             'CWS_BA_Agreement_Status__c'=>'Request',
             'CWS_MSA_Agreement__c'=>'TestMSA',
             'CWS_MSA_Agreement_Status__c'=>'Request',
             'CWS_NDA_Agreement__c'=>'NDAStatus',
             'CWS_NDA_Agreement_Status__c' =>'Request',
              'CWS_Need_Recurring__c'=>true
                };
        Account soldtoaccount=CWS_UTLDataFactory.createAccount('TestAccount', soldtoaccountFieldValues,true);
        
        Map<String, Object> contAdditionalFieldValues = new Map<String, Object>{
          'CWS_Transaction_Reason__c' => CWS_ConstantClass.TRANSACTION_REASON_CREDIT_REBILL,
         'CWS_Quote_SubType__c' => 'Credit',
          'CWS_OF_Signed_Date__c'=>System.today(),
           'StartDate' => System.today()
          //'EndDate' =>System.today()+ 2
        };
        Contract cont = CWS_UTLDataFactory.createContract(soldtoaccount.id, contAdditionalFieldValues, true);
 
        
        //Create Distributor Account
        Map<String, Object> distributorAccountFieldValues=new Map<String, Object>{
            'SBQQ__PriceHoldEnd__c'=>Date.ValueOf('2020-01-01'),
            'currencyIsoCode'=>'EUR',
             'CWS_Is_Partner__c'=>true,
             'CWS_Is_Distributor__c'=>true,
             'CWS_Need_Recurring__c'=>true
              };
        Account[] distiAccounts=CWS_UTLDataFactory.createBulkAccounts('DistributorAccount{!i}', distributorAccountFieldValues,3,true);        
              
        // Create Distributr Reseller Records 
        CWS_UTLDataFactory.createDistributorReseller(soldtoaccount.Id,distiaccounts[0].Id, CWS_ConstantClass.DISTRIBUTOR_TYPE,'Deal Reg', null, null, true);
        CWS_UTLDataFactory.createDistributorReseller(soldtoaccount.Id,distiaccounts[1].Id, 'Distributor','Fulfillment', null, null, true);
        //CWS_UTLDataFactory.createDistributorReseller(soldtoaccount.Id,distiaccounts[2].Id, CWS_ConstantClass.RESELLER_TYPE,'Deal Reg', null, null, true);
        
        // Create Opportunity1
        Map<String, Object> opportunityFields=new Map<String, Object>{
            'CWS_Route_to_Market__c'=>'Channel', 'CloseDate'=> Date.today(),'CWS_Bill_To_Account__c'=> soldtoaccount.Id,
            'Type'=>'New','CurrencyIsoCode'=>'USD', 'StageName' =>'Prospecting'
        };
        Opportunity opty=CWS_UTLDataFactory.createOpportunity('New Business Opty',soldtoaccount.Id,opportunityFields,true);
        
       
        //Create Quote record
        Map<String, Object> quoteFields=new Map<String,Object>{
            'SBQQ__Status__c'=>'Approved', 'CWS_Quote_Type__c'=>'Renewal', 
            'CWS_Bill_to_Account__c'=> distiaccounts[0].Id,
            'CWS_Agreement_Numbers__c'=> 'ABC123456',
            'CWS_Route_to_Market__c'=>'IIT',
            'CWS_Reseller_Account__c'=>distiaccounts[2].Id
        };
        SBQQ__Quote__c quote=CWS_UTLDataFactory.createQuote(soldtoaccount.Id,opty.Id, quoteFields, true);
        List<SBQQ__Quote__c> quotes  = [SELECT ID,SBQQ__Primary__c from SBQQ__Quote__c ];
            system.debug('quote--'+quotes);
        }
        
    @istest static void renewalQuotes(){
        
        Map<Id,SBQQ__Quote__c> quoteMap = new Map<Id,SBQQ__Quote__c>( [SELECT ID,SBQQ__Primary__c from SBQQ__Quote__c ]);
		List<SBQQ__Quote__c> quotelist = new List<SBQQ__Quote__c>();
        quotelist.addAll(quoteMap.values());
        quotelist[0].SBQQ__Primary__c = true;
        update  quotelist[0];
        List<SBQQ__Quote__c> quotes =[select id, SBQQ__Primary__c from SBQQ__Quote__c];
        system.debug('quotes--'+quotes);
        if(quoteMap != null){
            System.enqueueJob( new CWS_QueueableAcceptRenewalQuotes(quoteMap.keyset()));
        }
        
        
    } 
    

}