force-app/main/default/objects/Account/fields/CWS_Account_Restriction_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_Account_Restriction_Status__c</fullName>
    <inlineHelpText>Identifies if the Account requires additional validations or review. Reasons requiring restriction could be due to payment issues, lack of business, or other concerns.</inlineHelpText>
    <label>Account Restriction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Restriction</fullName>
                <default>true</default>
                <label>No Restriction</label>
            </value>
            <value>
                <fullName>Delinquent</fullName>
            </value>
            <value>
                <fullName>Payment Workout</fullName>
            </value>
            <value>
                <fullName>Credit Hold</fullName>
            </value>
            <value>
                <fullName>Shut Off</fullName>
            </value>
            <value>
                <fullName>Collection</fullName>
            </value>
            <value>
                <fullName>Blacklisted</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Suspect</fullName>
            </value>
            <value>
                <fullName>Out of Business</fullName>
            </value>
            <value>
                <fullName>Inactive Acquired</fullName>
            </value>
            <value>
                <fullName>Inactive Gone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Account_Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>CWS_Account_Unique_Identifier__c</fullName>
    <description>Used as unique identifier for all the Accounts</description>
    <displayFormat>ACT-{00000000}</displayFormat>
    <externalId>true</externalId>
    <label>Account Unique Identifier</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Additional_Emails_for_Invoice__c.field-meta.xml
<CustomField>
    <fullName>CWS_Additional_Emails_for_Invoice__c</fullName>
    <inlineHelpText>Captures email addresses that can be added to invoices involving this Account record.</inlineHelpText>
    <label>Additional Emails for Invoice</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Is_Distributor__c.field-meta.xml
<CustomField>
    <fullName>CWS_Is_Distributor__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies if the Account is a Distributor. If the field is checked as &quot;true&quot; then the Account is considered a Distributor.</inlineHelpText>
    <label>Is Distributor?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Is_Partner__c.field-meta.xml
<CustomField>
    <fullName>CWS_Is_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies if the Account has accepted a Quote from ConnectWise. If the field is checked as &quot;true&quot; then the Account has accepted a Quote and is considered a ConnectWise Partner.</inlineHelpText>
    <label>Is Partner?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Need_Recurring__c.field-meta.xml
<CustomField>
    <fullName>CWS_Need_Recurring__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates if the Account needs a PO every month to process recurring invoices.</inlineHelpText>
    <label>Need Recurring PO</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Products_Owned__c.field-meta.xml
<CustomField>
    <fullName>CWS_Products_Owned__c</fullName>
    <label>Products Owned</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3rd Party Patching</fullName>
                <isActive>false</isActive>
                <label>3rd Party Patching</label>
            </value>
            <value>
                <fullName>Acronis</fullName>
                <isActive>false</isActive>
                <label>Acronis</label>
            </value>
            <value>
                <fullName>Assist</fullName>
            </value>
            <value>
                <fullName>Automate</fullName>
            </value>
            <value>
                <fullName>Auvik</fullName>
                <isActive>false</isActive>
                <label>Auvik</label>
            </value>
            <value>
                <fullName>Avalara</fullName>
                <isActive>false</isActive>
                <label>Avalara</label>
            </value>
            <value>
                <fullName>BDR Solution Partners</fullName>
            </value>
            <value>
                <fullName>Bitdefender</fullName>
                <isActive>false</isActive>
                <label>Bitdefender</label>
            </value>
            <value>
                <fullName>BrightGauge</fullName>
            </value>
            <value>
                <fullName>Business Mgmt Solution Partners</fullName>
            </value>
            <value>
                <fullName>Campaign Director</fullName>
                <isActive>false</isActive>
                <label>Campaign Director</label>
            </value>
            <value>
                <fullName>CCleaner</fullName>
                <isActive>false</isActive>
                <label>CCleaner</label>
            </value>
            <value>
                <fullName>Centrestack</fullName>
                <isActive>false</isActive>
                <label>Centrestack</label>
            </value>
            <value>
                <fullName>ChatAssist</fullName>
                <isActive>false</isActive>
                <label>ChatAssist</label>
            </value>
            <value>
                <fullName>Cloud Data Access (Manage)</fullName>
                <isActive>false</isActive>
                <label>Cloud Data Access (Manage)</label>
            </value>
            <value>
                <fullName>Comand</fullName>
                <isActive>false</isActive>
                <label>Comand</label>
            </value>
            <value>
                <fullName>Command</fullName>
            </value>
            <value>
                <fullName>Control</fullName>
            </value>
            <value>
                <fullName>Control Remote Support</fullName>
                <isActive>false</isActive>
                <label>Control Remote Support</label>
            </value>
            <value>
                <fullName>Control Stand alone product</fullName>
                <isActive>false</isActive>
                <label>Control Stand alone product</label>
            </value>
            <value>
                <fullName>CW RMM</fullName>
            </value>
            <value>
                <fullName>Cylance</fullName>
                <isActive>false</isActive>
                <label>Cylance</label>
            </value>
            <value>
                <fullName>Dedicated Tech</fullName>
            </value>
            <value>
                <fullName>ESET</fullName>
                <isActive>false</isActive>
                <label>ESET</label>
            </value>
            <value>
                <fullName>ESET Encryption (DESLock)</fullName>
                <isActive>false</isActive>
                <label>ESET Encryption (DESLock)</label>
            </value>
            <value>
                <fullName>Foresite</fullName>
                <isActive>false</isActive>
                <label>Foresite</label>
            </value>
            <value>
                <fullName>Fortify</fullName>
            </value>
            <value>
                <fullName>Greencloud</fullName>
                <isActive>false</isActive>
                <label>Greencloud</label>
            </value>
            <value>
                <fullName>Help Desk</fullName>
            </value>
            <value>
                <fullName>HitmanPro</fullName>
                <isActive>false</isActive>
                <label>HitmanPro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_SSO_GUID__c.field-meta.xml
<CustomField>
    <fullName>CWS_SSO_GUID__c</fullName>
    <description>Field for storing comma-delimited SSO Partner IDs.</description>
    <inlineHelpText>Supports Single Sign-On integration with Manage</inlineHelpText>
    <label>SSO Tenant (Partner) ID</label>
    <length>2600</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Sub_Industry__c.field-meta.xml
<CustomField>
    <fullName>CWS_Sub_Industry__c</fullName>
    <inlineHelpText>Dependent based upon the value selected in the Industry field.</inlineHelpText>
    <label>Sub-Industry</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Industry</controllingField>
        <restricted>true</restricted>
        <valueSetName>CWS_Sub_Industry</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CWS_SiteDetailReportCallOut_Test.cls
/*Class Name: CWS_SiteDetailReportCallOut_Test
*Description: Test Class for CWS_SiteDetailReportCallOut
*Created By: Mahak Bansal
*Created On: 30/6/2021
*Modification Log
*------------------------------------------------------------------------------------------
*Developer              Date            User Story              Description
*------------------------------------------------------------------------------------------
*Mahak Bansal		    30/6/2021		OBD-154		           Initial Version
*/
@isTest
public class CWS_SiteDetailReportCallOut_Test {
    
    /* @description: Test Setup for CWS_SiteDetailReportCallOutTest
    * @return: void  */
    @TestSetup
    public static void setup() 
    {        
        Account testAccountOne = new Account(
            Name = 'BB8 Test Account',
            Phone = '727 777 3625',
            BillingStreet = '8800 Bay Pines Boulevard',
            BillingCity = 'St. Petersburg',
            BillingCountry = 'United States',
            BillingState = 'Florida',
            BillingPostalCode = '33715',
            CWS_Account_Restriction_Status__c = 'No Restriction',
            CWS_Products_Owned__c = 'Automate',
            CWS_Is_Partner__c = true,
            CWS_Is_Distributor__c = true,
            CWS_Need_Recurring__c = true,
            CWS_SSO_GUID__c = '5f6d07a5e6426900017a3ad5',
            CurrencyIsoCode = 'USD',
            Industry = 'MSP',
            CWS_Sub_Industry__c = 'N/A',
            SBQQ__PriceHoldEnd__c = System.today().addMonths(6),
            CWS_Additional_Emails_for_Invoice__c = 'bmarly@gmail.com.invalid, jcochran@gmail.com.invalid'
        );
        insert testAccountOne;
        Contact contact = new Contact(LastName = 'hello',FirstName = 'World',Email = 'a@dolby.com',AccountId =  testAccountOne.Id);
        insert contact;


        Zuora__ZInvoice__c zInvoice = new Zuora__ZInvoice__c();
        zInvoice.Zuora__Account__c=testAccountOne.Id;
        zInvoice.Name='INV-123';
        zInvoice.Zuora__InvoiceDate__c=System.today()-20;
        zInvoice.CWS_CMS_Invoice__c='FALSE';
        insert zInvoice;

        Zuora__ZInvoice__c zInvoice1 = new Zuora__ZInvoice__c();
        zInvoice1.Zuora__Account__c=testAccountOne.Id;
        zInvoice1.Name='INV-432';
        zInvoice1.Zuora__InvoiceDate__c=System.today()-10;
        zInvoice1.CWS_CMS_Invoice__c='TRUE';
        insert zInvoice1;
    }

      /**
    * @description API test for negative scenario
    */ 
    @isTest static void showSiteDetailReportNegative() {
        Zuora__ZInvoice__c invoice =[SELECT ID,Name,CWS_CMS_Invoice__c,Zuora__InvoiceDate__c,Zuora__Account__r.CWS_Account_Unique_Identifier__c  FROM Zuora__ZInvoice__c where name='INV-123'];
        CWS_SiteDetailReportCallOut.SiteDetailResponse resp=CWS_SiteDetailReportCallOut.showSiteDetailReport(invoice.ID);
        System.assertEquals(false,resp.showSiteDetailButton,'SiteDetailReport response is not visible');
    }

    /**
    * @description API test for positive scenario
    */ 
    @isTest static void succesRes() {

        Zuora__ZInvoice__c invoice2 =[SELECT ID,Name,CWS_CMS_Invoice__c,Zuora__InvoiceDate__c,Zuora__Account__r.CWS_Account_Unique_Identifier__c  FROM Zuora__ZInvoice__c where name='INV-432'];
        CWS_SiteDetailReportCallOut.SiteDetailResponse resp2=CWS_SiteDetailReportCallOut.showSiteDetailReport(invoice2.ID);
        System.assertEquals(true, resp2.showSiteDetailButton,'SiteDetailReport button is visible');

        Test.setMock(HttpCalloutMock.class, new SuccessfulResponse());
        if(resp2!=null &&resp2.showSiteDetailButton){
            Test.startTest();
            CWS_SiteDetailReportCallOut.GetSiteDetailResponse response=CWS_SiteDetailReportCallOut.getSiteDetailReport(invoice2.Id);
            System.assert(response.isSuccess == true,'SiteDetailReport response is success');
            Test.stopTest();
        }
    }

    /**
    * @description API test if the ID is not a valid invoice record in Salesforce 
    */ 
    @isTest static void noInvoiceRecord() {
        //Have to test  using a hardcode value to test the breaking scenarios
        String invoiceId='a3n6t000000GmyjAAC';
        CWS_SiteDetailReportCallOut.SiteDetailResponse showSiteDetailResp=CWS_SiteDetailReportCallOut.showSiteDetailReport(invoiceId);
        System.assertEquals(false, showSiteDetailResp.showSiteDetailButton,'SiteDetailReport button should not be visible');
        
        Test.setMock(HttpCalloutMock.class, new SuccessfulResponse());
        Test.startTest();
        CWS_SiteDetailReportCallOut.GetSiteDetailResponse response=CWS_SiteDetailReportCallOut.getSiteDetailReport(invoiceId);
		System.assert(response.isSuccess == false, 'SiteDetailReport response is false');
        Test.stopTest();
    }

    /**
    * @description Test if the profile is not able to access the Invoice Record.
    */ 
    @isTest static void testPofileInAccessible() {
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Read Only' LIMIT 1];
        UserRole userRoleRec= [SELECT Id FROM userRole WHERE Name = 'Sales Operations' LIMIT 1];
		
        User user = new User(alias = 'standt', email='a@dolby.com',emailencodingkey='UTF-8',FirstName = 'hello',
                    lastname='Testing',languagelocalekey='en_US',
					localesidkey='en_US',profileid = profile.Id,UserRoleId = userRoleRec.id,timezonesidkey='America/Los_Angeles',
					CommunityNickname = 'Tom',isActive = true,username='a@dolby.com');
		insert user;
        //Have to test  using a hardcode value to test the breaking scenarios
        String invoiceId='a3n6t000000GmyjAAC';
 
        Test.startTest();
        System.runAs(user){         
            CWS_SiteDetailReportCallOut.SiteDetailResponse showSiteDetailResp=CWS_SiteDetailReportCallOut.showSiteDetailReport(invoiceId);
            System.assertEquals(false, showSiteDetailResp.showSiteDetailButton,'SiteDetailReport button should not be visible');   
        }
        Test.stopTest();
    }

    /**
    * @description API test for failed, or negative scenario for CWS_SiteDEtailReport
    */ 
    @isTest static void failedRes() {
        Zuora__ZInvoice__c invoice2 =[SELECT ID,Name,CWS_CMS_Invoice__c,Zuora__InvoiceDate__c,Zuora__Account__r.CWS_Account_Unique_Identifier__c  FROM Zuora__ZInvoice__c where name='INV-432'];
        CWS_SiteDetailReportCallOut.SiteDetailResponse resp2=CWS_SiteDetailReportCallOut.showSiteDetailReport(invoice2.ID);
        System.assertEquals(true, resp2.showSiteDetailButton,'SiteDetailReport button should be visible');
        if(resp2.showSiteDetailButton){
            CWS_SiteDetailReportCallOut.getSiteDetailReport(invoice2.Id);            
        }
    }

    /**
    * @description Mock Response class for the success of the API 
    */ 
    public class SuccessfulResponse implements HttpCalloutMock {

        /**
        * @description Method to generate Mock reposnse of the API
        */ 
        public HTTPResponse respond(HttpRequest request) {

            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            Attachment attach=new Attachment();   	
            attach.Name='Unit Test Attachment';
            Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
            attach.body=bodyBlob;
            String bodyRES='{"body":'+ bodyBlob+'}';
            response.setBody(bodyRES);
            //response.setBody('{"SiteDetail":"testtest","Error":""}');
            response.setStatusCode(200);
            return response;
        }        
    }   
}