force-app/main/default/objects/Account/fields/CWS_Account_Restriction_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_Account_Restriction_Status__c</fullName>
    <inlineHelpText>Identifies if the Account requires additional validations or review. Reasons requiring restriction could be due to payment issues, lack of business, or other concerns.</inlineHelpText>
    <label>Account Restriction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Restriction</fullName>
                <default>true</default>
                <label>No Restriction</label>
            </value>
            <value>
                <fullName>Delinquent</fullName>
            </value>
            <value>
                <fullName>Payment Workout</fullName>
            </value>
            <value>
                <fullName>Credit Hold</fullName>
            </value>
            <value>
                <fullName>Shut Off</fullName>
            </value>
            <value>
                <fullName>Collection</fullName>
            </value>
            <value>
                <fullName>Blacklisted</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Suspect</fullName>
            </value>
            <value>
                <fullName>Out of Business</fullName>
            </value>
            <value>
                <fullName>Inactive Acquired</fullName>
            </value>
            <value>
                <fullName>Inactive Gone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Is_Partner__c.field-meta.xml
<CustomField>
    <fullName>CWS_Is_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies if the Account has accepted a Quote from ConnectWise. If the field is checked as &quot;true&quot; then the Account has accepted a Quote and is considered a ConnectWise Partner.</inlineHelpText>
    <label>Is Partner?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Products_Owned__c.field-meta.xml
<CustomField>
    <fullName>CWS_Products_Owned__c</fullName>
    <label>Products Owned</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3rd Party Patching</fullName>
                <isActive>false</isActive>
                <label>3rd Party Patching</label>
            </value>
            <value>
                <fullName>Acronis</fullName>
                <isActive>false</isActive>
                <label>Acronis</label>
            </value>
            <value>
                <fullName>Assist</fullName>
            </value>
            <value>
                <fullName>Automate</fullName>
            </value>
            <value>
                <fullName>Auvik</fullName>
                <isActive>false</isActive>
                <label>Auvik</label>
            </value>
            <value>
                <fullName>Avalara</fullName>
                <isActive>false</isActive>
                <label>Avalara</label>
            </value>
            <value>
                <fullName>BDR Solution Partners</fullName>
            </value>
            <value>
                <fullName>Bitdefender</fullName>
                <isActive>false</isActive>
                <label>Bitdefender</label>
            </value>
            <value>
                <fullName>BrightGauge</fullName>
            </value>
            <value>
                <fullName>Business Mgmt Solution Partners</fullName>
            </value>
            <value>
                <fullName>Campaign Director</fullName>
                <isActive>false</isActive>
                <label>Campaign Director</label>
            </value>
            <value>
                <fullName>CCleaner</fullName>
                <isActive>false</isActive>
                <label>CCleaner</label>
            </value>
            <value>
                <fullName>Centrestack</fullName>
                <isActive>false</isActive>
                <label>Centrestack</label>
            </value>
            <value>
                <fullName>ChatAssist</fullName>
                <isActive>false</isActive>
                <label>ChatAssist</label>
            </value>
            <value>
                <fullName>Cloud Data Access (Manage)</fullName>
                <isActive>false</isActive>
                <label>Cloud Data Access (Manage)</label>
            </value>
            <value>
                <fullName>Comand</fullName>
                <isActive>false</isActive>
                <label>Comand</label>
            </value>
            <value>
                <fullName>Command</fullName>
            </value>
            <value>
                <fullName>Control</fullName>
            </value>
            <value>
                <fullName>Control Remote Support</fullName>
                <isActive>false</isActive>
                <label>Control Remote Support</label>
            </value>
            <value>
                <fullName>Control Stand alone product</fullName>
                <isActive>false</isActive>
                <label>Control Stand alone product</label>
            </value>
            <value>
                <fullName>CW RMM</fullName>
            </value>
            <value>
                <fullName>Cylance</fullName>
                <isActive>false</isActive>
                <label>Cylance</label>
            </value>
            <value>
                <fullName>Dedicated Tech</fullName>
            </value>
            <value>
                <fullName>ESET</fullName>
                <isActive>false</isActive>
                <label>ESET</label>
            </value>
            <value>
                <fullName>ESET Encryption (DESLock)</fullName>
                <isActive>false</isActive>
                <label>ESET Encryption (DESLock)</label>
            </value>
            <value>
                <fullName>Foresite</fullName>
                <isActive>false</isActive>
                <label>Foresite</label>
            </value>
            <value>
                <fullName>Fortify</fullName>
            </value>
            <value>
                <fullName>Greencloud</fullName>
                <isActive>false</isActive>
                <label>Greencloud</label>
            </value>
            <value>
                <fullName>Help Desk</fullName>
            </value>
            <value>
                <fullName>HitmanPro</fullName>
                <isActive>false</isActive>
                <label>HitmanPro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_SSO_GUID__c.field-meta.xml
<CustomField>
    <fullName>CWS_SSO_GUID__c</fullName>
    <description>Field for storing comma-delimited SSO Partner IDs.</description>
    <inlineHelpText>Supports Single Sign-On integration with Manage</inlineHelpText>
    <label>SSO Tenant (Partner) ID</label>
    <length>2600</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CWS_Active__c.field-meta.xml
<CustomField>
    <fullName>CWS_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CWS_CW_Login_Email__c.field-meta.xml
<CustomField>
    <fullName>CWS_CW_Login_Email__c</fullName>
    <description>Captures the user email from CW Home</description>
    <inlineHelpText>Captures the user email from CW Home</inlineHelpText>
    <label>CW Login Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CWS_Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>CWS_Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CWS_SSO_User_ID__c.field-meta.xml
<CustomField>
    <fullName>CWS_SSO_User_ID__c</fullName>
    <externalId>true</externalId>
    <label>SSO User ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Account_Restriction_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_Account_Restriction_Status__c</fullName>
    <formula>Text(Account.CWS_Account_Restriction_Status__c)</formula>
    <label>Account Restriction Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CWS_SSOAccountContactIntegration_Test.cls
/*Class Name: CWS_SSOAccountContactIntegration_Test
*Description: Test class for SSO Integration to provide Account and Contract data
*Created By: Carl Shahan
*Created On: 10/03/2020
*Modification Log
*------------------------------------------------------------------------------------------
*Developer   Date       User Story    Description
*------------------------------------------------------------------------------------------
*Carl Shahan 10/03/2020 CWH-996       Test class for SSO Integration to provide Account and Contract data
*/
@isTest
public with sharing class CWS_SSOAccountContactIntegration_Test {
    private static Account createAccountWithContact() {

        Account account = new Account(

            Name = 'AIOITS Test Account',
            Phone = '727 777 3625',
            BillingStreet = '8800 Bay Pines Boulevard',
            BillingCity = 'St. Petersburg',
            BillingCountry = 'United States',
            BillingState = 'Florida',
            BillingPostalCode = '33715',
            CWS_Account_Restriction_Status__c = 'No Restriction',
            CWS_Products_Owned__c = 'Automate',
            CWS_Is_Partner__c = true,
            CWS_SSO_GUID__c = '5f6d07a5e6426900017a3ad5'
        );

        insert account;

        List<Contact> contactList = new List<Contact>();
        contactList.add(new Contact(
            AccountId = account.Id,
            CWS_Active__c = true,
            CWS_Primary_Contact__c = true,
            FirstName = 'Roger',
            LastName = 'Rabbit',
            Phone = '727 777 3625',
            Email = 'roger.rabbit@aioits.com.invalid',
            CWS_SSO_User_ID__c = '5f6d07a5ba60dafc65b47f92',
            CWS_CW_Login_Email__c = 'lskywalker@bb8fptecc.com.invalid'
        ));

        insert contactList;

        return account;
    }

    @isTest static void getAccountFoundTest() {

        // Create the Account and Contact needed for the SOQL query 
        Account account = createAccountWithContact();

        System.debug('Account Id ' + account.Id);

        Test.startTest();

            RestRequest getRequest = new RestRequest();
            getRequest.requestURI = '/services/apexrest/sso/account/' + account.Id;
            getRequest.httpMethod = 'GET';
            RestContext.request = getRequest;
            Account record = CWS_SSOAccountContactIntegration.getAccountContact();
 
        Test.stopTest();

        System.debug('>>>>>>>>> getAccountFoundTest record = ' + record);

        System.assertEquals(account.Id, record.Id);
    }
}