force-app/main/default/objects/Account/fields/CWS_Account_Restriction_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_Account_Restriction_Status__c</fullName>
    <inlineHelpText>Identifies if the Account requires additional validations or review. Reasons requiring restriction could be due to payment issues, lack of business, or other concerns.</inlineHelpText>
    <label>Account Restriction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Restriction</fullName>
                <default>true</default>
                <label>No Restriction</label>
            </value>
            <value>
                <fullName>Delinquent</fullName>
            </value>
            <value>
                <fullName>Payment Workout</fullName>
            </value>
            <value>
                <fullName>Credit Hold</fullName>
            </value>
            <value>
                <fullName>Shut Off</fullName>
            </value>
            <value>
                <fullName>Collection</fullName>
            </value>
            <value>
                <fullName>Blacklisted</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Suspect</fullName>
            </value>
            <value>
                <fullName>Out of Business</fullName>
            </value>
            <value>
                <fullName>Inactive Acquired</fullName>
            </value>
            <value>
                <fullName>Inactive Gone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Account_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_Account_Review_Status__c</fullName>
    <inlineHelpText>Indicates if an Account has been reviewed by the Master Data Team. &quot;Prospect&quot; Accounts have not been reviewed. &quot;In Review&quot; Accounts are actively being reviewed. &quot;Active&quot; Accounts have been reviewed and specific fields have been locked to prevent changes.</inlineHelpText>
    <label>Account Review Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_BA_Agreement_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_BA_Agreement_Status__c</fullName>
    <label>BA Agreement Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_Integration_Status__c</fullName>
    <description>Field will be used to capture integration status, Will be marked for ready in case of changes in certain fields.</description>
    <inlineHelpText>Captures integration status and the field value will be &quot;Ready For Sync&quot; if there are changes to certain fields on the Account.</inlineHelpText>
    <label>Integration Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready For Sync</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Is_Partner__c.field-meta.xml
<CustomField>
    <fullName>CWS_Is_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies if the Account has accepted a Quote from ConnectWise. If the field is checked as &quot;true&quot; then the Account has accepted a Quote and is considered a ConnectWise Partner.</inlineHelpText>
    <label>Is Partner?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Manage_Company_Rec_Id__c.field-meta.xml
<CustomField>
    <fullName>CWS_Manage_Company_Rec_Id__c</fullName>
    <description>to hold Manage Reference Ids</description>
    <label>Manage Company Rec Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Manage_Integration_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_Manage_Integration_Sync_Status__c</fullName>
    <label>Manage Integration Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready for Sync</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Minimum_Commit_Amount__c.field-meta.xml
<CustomField>
    <fullName>CWS_Minimum_Commit_Amount__c</fullName>
    <label>Minimum Commit Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Region__c.field-meta.xml
<CustomField>
    <fullName>CWS_Region__c</fullName>
    <description>Use to capture the Region for the Account on which CWS_Territory __c is dependent.</description>
    <inlineHelpText>Populates based on the Account address and is used to help assign the Territory.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_SSO_GUID__c.field-meta.xml
<CustomField>
    <fullName>CWS_SSO_GUID__c</fullName>
    <description>Field for storing comma-delimited SSO Partner IDs.</description>
    <inlineHelpText>Supports Single Sign-On integration with Manage</inlineHelpText>
    <label>SSO Tenant (Partner) ID</label>
    <length>2600</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CWS_Country_Territory_Region_Mapping__mdt/CWS_Country_Territory_Region_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Mapping will be used to Populated Territory and Region based on Country/State/ZipCode.</description>
    <label>Country Territory Region Mapping</label>
    <pluralLabel>Country Territory Region Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/CWS_Country_Territory_Region_Mapping__mdt/fields/CWS_Region__c.field-meta.xml
<CustomField>
    <fullName>CWS_Region__c</fullName>
    <label>Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>CWS_Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Captures the Bill To Account associated to this Opportunity.</inlineHelpText>
    <label>Bill To (Account)</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>$Source.CWS_Route_to_Market__c</field>
            <operation>equals</operation>
            <value>Channel</value>
        </filterItems>
        <filterItems>
            <field>Account.CWS_Is_Distributor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Bill - To Account)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Region__c.field-meta.xml
<CustomField>
    <fullName>CWS_Region__c</fullName>
    <description>Region from the Account.</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <inlineHelpText>Captures the prospect&apos;s route to market; used for routing to BDR and PSE/SE pools.</inlineHelpText>
    <label>Route to Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/CWS_Region__c.field-meta.xml
<CustomField>
    <fullName>CWS_Region__c</fullName>
    <description>Region from the User Belong as it is being used for the Different Functionalities based on different flows of business.</description>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CWS_AccountTriggerHelper_Test.cls
/*Class Name: CWS_AccountTriggerHelper_Test
*Description: Test Class for CWS_AccountTriggerHelper
*Created By: Ankit
*Created On: 4/7/2020
*Modification Log
*------------------------------------------------------------------------------------------
*Developer              Date            User Story              Description
*------------------------------------------------------------------------------------------
*Nirmal                 04/07/2020        BED-5150            Initial Version(Default Account Currency) 
*Manoj                  08/03/2020                            Account territory updation and field restriction based on quote stage.
*Carl Shahan            09/10/2021        OBD-224             Commented out testCheckRestrictedFields() ~ 161 - 226 becuase it was generating errors and only added 2 lines of code coverage  
*Carl Shahan            09/10/2021        OBD-224             Added added Rec Id and Sync status to accountIntegratonSyncTest() ~ 121 to increase code coverage  
*/

    @isTest(SeeAllData=false)
    public class CWS_AccountTriggerHelper_Test {
    
        @testSetup static void createTestData(){
        //create custom setting data
        CWS_UTLDataFactory.insertTriggerSwitch(new List<String>{'Account'});    
        
        Map<String, Object> endCustomerDetails =new Map<String, Object>{
            'BillingCountry'=>'United States',
                'BillingCountryCode'=>'US',
                'currencyIsoCode'=>'USD',
                'CWS_Minimum_Commit_Amount__c'=>1000,
                'BillingPostalCode' => '12345',
                'CWS_BA_Agreement_Status__c' => 'InProgress' ,
                'BillingPostalCode' => '12111',
                'BillingStreet' => 'street',
                'BillingCity' => 'New York',
                'BillingState' => 'New York',
                'CWS_SSO_GUID__c' => '',
                'CWS_Is_Partner__c' => true   
                };
                    CWS_UTLDataFactory.createAccount('TestAccount', endCustomerDetails,true);       
    }
    // Methd Used to Cover BED-163, BED - 496,BED-5150
    @isTest static void testMethod1(){        
        
        list<Account> accObj = [Select CurrencyISOCode,BillingCountryCode,
                                CWS_Account_Review_Status__c,CWS_Integration_Status__c,
                                CWS_Account_Restriction_Status__c,CWS_Minimum_Commit_Amount__c  from Account];
        
        // Create Opportunity
        Map<String, Object> opportunityFields=new Map<String, Object>{
            'CWS_Route_to_Market__c'=>'Direct', 'CloseDate'=> Date.today(),'CWS_Bill_To_Account__c'=> accObj[0].Id,
                'Type'=>'New','CurrencyIsoCode'=>'USD'
                };
                    Opportunity opty=CWS_UTLDataFactory.createOpportunity('New Business Opty',accObj[0].Id,opportunityFields,true);
        
        //Create Quote record
        Map<String, Object> quoteFields=new Map<String,Object>{
            'SBQQ__Status__c'=>'Approved', 'SBQQ__Type__c'=>'Renewal', 'SBQQ__Distributor__c'=>accObj[0].Id, 'SBQQ__Account__c'=> accObj[0].Id,
                'CWS_Bill_to_Account__c'=> accObj[0].Id, 'CWS_Route_to_Market__c'=>'Direct','CurrencyIsoCode'=>'USD'
                };
                    
                    Test.startTest();       
        SBQQ__Quote__c quote = CWS_UTLDataFactory.createQuote(accObj[0].Id,opty.Id, quoteFields, true);
        system.debug('quoteId--'+quote.ID);
        Map<String, Object> quoteDocFieldsMap = new Map<String, Object>{
            'SBQQ__Opportunity__c' => opty.ID
                };        
                    SBQQ__QuoteDocument__c qDoc = CWS_UTLDataFactory.createQuoteDocument(quote.id,quoteDocFieldsMap, true);        
        
        quote.ApprovalStatus__c = CWS_ConstantClass.QUOTE_Approval_Status_Pending;
        update quote;
        
        Test.stopTest();
        accObj[0].BillingCountryCode = 'US';
        //accObj[0].BillingCountry ='Australia';
        accObj[0].CWS_Account_Review_Status__c = 'In Review';
        accObj[0].CWS_Account_Restriction_Status__c = 'Collection';
        accObj[0].CWS_Minimum_Commit_Amount__c = 15000;
        accObj[0].Name = 'Test Account1';
        accObj[0].BillingPostalCode = '112233';
        accObj[0].CWS_BA_Agreement_Status__c = 'Finalised';
        if(accObj.size()>0){
            update accObj;
        }
        
        accObj[0].CWS_Account_Review_Status__c = 'Active';
        accObj[0].CWS_Account_Restriction_Status__c = CWS_ConstantClass.ACCOUNT_RSTATUS_PAYMENTWORKOUT;
        accObj[0].CWS_Is_Partner__c = true;
        if(accObj.size()>0){
            update accObj;
        }
        
        accObj[0].CWS_Account_Review_Status__c = 'Prospect';
        if(accObj.size()>0){
            update accObj;
        }
        
        system.assertEquals(accObj[0].CurrencyISOCode, 'USD');       
        /* 
        if(accObj.size()>0){
        Delete accObj;
        }*/
        
        //These methods are directly called because of the reason that the trigger context are not firing on them and
        //if we try to save handler removing these context ot throws compile error as its implementing interface
        
        CWS_AccountTriggerHandler handler = new CWS_AccountTriggerHandler();
        map<id,SObject> newRecs = new map<id,SObject>();
        handler.AfterInsert(newRecs);
        handler.BeforeDelete(newRecs);
        handler.AfterDelete(newRecs);
        handler.AfterUndelete(newRecs);
    }
    
    // Methd Used to Cover BED - 496
    @isTest static void accountIntegratonSyncTest(){
        
        Test.starttest();
        
        list<Account> accObj = [Select CurrencyISOCode,BillingCountryCode,
                                CWS_Account_Review_Status__c,CWS_Integration_Status__c,Phone from Account LIMIT 1];
        
        accObj[0].CWS_Account_Review_Status__c = 'In Review';
        accObj[0].Phone ='121212';
        accObj[0].CWS_Integration_Status__c = CWS_ConstantClass.INT_STATUS_ERROR;
        accObj[0].CWS_Manage_Company_Rec_Id__c = '341427';
        accObj[0].CWS_Manage_Integration_Sync_Status__c = CWS_ConstantClass.INT_STATUS_READY;
        // Carl added Rec Id and Sync status to up code coverage 

        
        if(accObj.size()>0){
            update accObj;
        }
        Account acc = [SELECT CWS_Integration_Status__c FROM Account WHERE Id=:accObj[0].Id LIMIT 1];
        system.assertEquals(acc.CWS_Integration_Status__c, CWS_ConstantClass.INT_STATUS_READY);
        
        Test.stoptest();
        if(accObj.size()>0){
            Delete accObj;
        }
    }
    
    //BED-1009 Test Account restriction status 
    @isTest static void testCloseAcctRstOpps(){
        list<Account> objAcct = [Select Id,CWS_Account_Restriction_Status__c from Account];
        Map<String, Object> mapOppDetails=new Map<String, Object>{
            'AccountId' => objAcct[0].Id,
                'CWS_Route_to_Market__c'=>'Direct', 
                'CloseDate'=> Date.today(),
                'CWS_Bill_To_Account__c'=> objAcct[0].Id,
                'Type'=>'New',
                'CurrencyIsoCode'=>'USD'
                };      
                    Opportunity objOpp = CWS_UTLDataFactory.createOpportunity('TestOpp', objAcct[0].Id,mapOppDetails,true);       
        objAcct[0].CWS_Account_Restriction_Status__c = CWS_ConstantClass.ACCOUNT_RSTATUS_CREDITHOLD;
        if(objAcct != null){
            Update objAcct;
        }
        Opportunity objOppAssrt;
        if(objOpp != null){
            objOppAssrt = [select Id,StageName from opportunity where id=:objOpp.Id];
        }
        system.assertEquals(objOppAssrt.StageName, CWS_ConstantClass.OpportunityClosedLose_Stage);
    }
    /*
    //To check feild restriction.
    @isTest static void testCheckRestrictedFields(){
        //Creating sales rep.
        System.runAs(new User(Id = Userinfo.getUserId())) {
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');        
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User salesrep1 = CWS_UTLDataFactory.createUser(uniqueName.substring(18, 23), uniqueName + '@test' + orgId + '.org','lName','CWS_Sales_Rep','CEO',uniqueName + '@test' + orgId + '.org',new Map<String, Object>(),true);
        
         // PermissionSetLicense license = [SELECT Id, DeveloperName  FROM PermissionSetLicense where  DeveloperName ='SalesforceCPQ_CPQStandardPerm'];
            // if(license != null){
                //PermissionSetLicenseAssign  psla = new PermissionSetLicenseAssign();
                //psla.PermissionSetLicenseId = license.id;
                //psla.AssigneeId = salesrep1.Id;
                //insert psla;
            //}
            list<Account> accObj = [Select OwnerId,name,CurrencyISOCode,BillingCountryCode,
                                CWS_Account_Review_Status__c,CWS_Integration_Status__c,
                                CWS_Account_Restriction_Status__c,CWS_Minimum_Commit_Amount__c,BillingCity  from Account];
        //User salesrep1  = [SELECT Id from User where id=:salesrep.Id];
        accObj[0].OwnerId = salesrep1.ID;
        update accObj[0];
        CWS_AccountTriggerHelper.currentUserProfile = null;
        //new
        List<PermissionSetAssignment> psa = new List<PermissionSetAssignment>();
        //List<PermissionSet> ps = [SELECT Id FROM PermissionSet WHERE Name in('CWS_Sales_Rep_CPQ','SteelBrickCPQUser')];
            for(PermissionSet pset:[SELECT Id FROM PermissionSet WHERE Name in('CWS_Sales_Rep_CPQ','SteelBrickCPQUser')] ){
                psa.add(new PermissionSetAssignment(AssigneeId = salesrep1.id, PermissionSetId = pset.Id));
            }
         if(!psa.isEmpty()){
             system.debug('psa--'+psa);
            insert psa;
         }
        
        //new
        System.runAs(salesrep1){
            // Create Opportunity
            Map<String, Object> opportunityFields=new Map<String, Object>{
                'CWS_Route_to_Market__c'=>'Direct', 'CloseDate'=> Date.today(),'CWS_Bill_To_Account__c'=> accObj[0].Id,
                    'Type'=>'New','CurrencyIsoCode'=>'USD'
                    };
                        Opportunity opty=CWS_UTLDataFactory.createOpportunity('New Business Opty',accObj[0].Id,opportunityFields,true);
            
            //Create Quote record
            Map<String, Object> quoteFields=new Map<String,Object>{
                'SBQQ__Status__c'=> CWS_ConstantClass.QUOTE_STATUS_ORDERFORM_GEN, 'SBQQ__Type__c'=>'Renewal', 'SBQQ__Distributor__c'=>accObj[0].Id, 'SBQQ__Account__c'=> accObj[0].Id,
                    'CWS_Bill_to_Account__c'=> accObj[0].Id, 'CWS_Route_to_Market__c'=>'Direct','CurrencyIsoCode'=>'USD'
                    };
                        
                        SBQQ__Quote__c quote = CWS_UTLDataFactory.createQuote(accObj[0].Id,opty.Id, quoteFields, true);
            Test.startTest();
            
            accObj[0].name ='Test Account 2';
            accObj[0].BillingCity ='Alabama';
            try{
                Update accObj[0];
            }
            catch(Exception ex){
                System.assert(ex.getMessage().contains(Label.CWS_Acc_Restr_Fields_Error));
            }
            Test.stopTest();
        }
        }
    } */
    
    @isTest static void testTerritoryDefault(){
        list<Account> accObj = [Select Id,OwnerId,name,BillingCity,billingcountryCode,billingStateCode,BillingPostalCode  from Account];
        //Updating 
        Account acc =  accObj[0];
        acc.billingcountryCode = 'AF';      
        acc.BillingPostalCode ='1001';  
        update acc;
        
        Account accnt =[SELECT ID, CWS_Region__c FROM Account WHERE ID=: acc.ID LIMIT 1];  
        map<String, CWS_Country_Territory_Region_Mapping__mdt> terRegMap = CWS_TerritoryRegionHelper.getTerritoryRegion();        
        system.assertEquals(terRegMap.get(CWS_ConstantClass.NA_KEY).CWS_Region__c, accnt.CWS_Region__c);
    }
}