force-app/main/default/objects/Account/fields/CWS_Established_Disti_Reseller__c.field-meta.xml
<CustomField>
    <fullName>CWS_Established_Disti_Reseller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Validate that when the first Quote is accepted that the Disti/Reseller account is stamped on the End Customer Account in the &quot;Established Disti/Reseller&quot; field</description>
    <label>Established Disti/Reseller</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Is_Distributor__c.field-meta.xml
<CustomField>
    <fullName>CWS_Is_Distributor__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies if the Account is a Distributor. If the field is checked as &quot;true&quot; then the Account is considered a Distributor.</inlineHelpText>
    <label>Is Distributor?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Is_IIT_Reseller__c.field-meta.xml
<CustomField>
    <fullName>CWS_Is_IIT_Reseller__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Identifies if the Account is an IIT Reseller. If the field is checked as &quot;true&quot; then the Account is considered an IIT Reseller.</inlineHelpText>
    <label>Is IIT Reseller?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CWS_Distributor_Reseller__c/CWS_Distributor_Reseller__c.object-meta.xml
<CustomObject>
    <description>This is the Object to maintain the Relationship between the Distributor/Reseller and the End Customer Account.</description>
    <label>Distributor/Reseller</label>
    <nameField>
        <label>Distributor/Reseller  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributors/Resellers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/CWS_Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>CWS_Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Captures the Bill To Account associated to this Opportunity.</inlineHelpText>
    <label>Bill To (Account)</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>$Source.CWS_Route_to_Market__c</field>
            <operation>equals</operation>
            <value>Channel</value>
        </filterItems>
        <filterItems>
            <field>Account.CWS_Is_Distributor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Bill - To Account)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Master__c.field-meta.xml
<CustomField>
    <fullName>CWS_Master__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This indicates that the opportunity will have the legacy model of minimum commitment maintained as $value at Account level. This is not recommended; please contact System Administrator for help.</inlineHelpText>
    <label>Master?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <inlineHelpText>Captures the prospect&apos;s route to market; used for routing to BDR and PSE/SE pools.</inlineHelpText>
    <label>Route to Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Share_with_Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>CWS_Share_with_Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Captures the Share with Bill To Account for this Opportunity.</inlineHelpText>
    <label>Share with Bill To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Share Lookup)</relationshipLabel>
    <relationshipName>Opportunities5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Store_Bill_To_Id__c.field-meta.xml
<CustomField>
    <fullName>CWS_Store_Bill_To_Id__c</fullName>
    <inlineHelpText>Captures the Bill To ID for this Opportunity.</inlineHelpText>
    <label>Store Bill To Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CWS_SingleDitributorStampingBatch_Test.cls
/*Class Name: CWS_SingleDitributorStampingBatch_Test
*Description: test Class for CWS_SingleDitributorStampingBatch
*Created By: Nida
*Created On: 08/06/2020
*Modification Log
*------------------------------------------------------------------------------------------
*Developer              Date            User Story              Description
*------------------------------------------------------------------------------------------
*Nida               08/06/2020     BED-8383              
*/
@isTest(SeeAllData=false)
public class CWS_SingleDitributorStampingBatch_Test {
    
   @testSetup static void createTestData(){
        //create custom setting data
        CWS_UTLDataFactory.insertTriggerSwitch(new List<String>{'CWS_Distributor_Reseller__c','Quote','SBQQ__QuoteDocument__c'});    
        
        //Create Account
        Map<String, Object> accountFieldValues=new Map<String, Object>{
            'CWS_Is_Distributor__c' =>True,
             //   'CWS_Is_IIT_Reseller__c' =>True,
            'currencyIsoCode'=>'EUR'};
        List<Account> acctLst = CWS_UTLDataFactory.createBulkAccounts('Test Account',accountFieldValues , 4, true);
        
        
        Opportunity opp = CWS_UTLDataFactory.createOpportunity('optyName',acctLst[0].Id, new Map<String, Object>{'StageName'=>'Analysis','Type' => 'Amendment' ,'CloseDate'=>System.today()+1,'CWS_Bill_To_Account__c'=>acctLst[0].Id,'CWS_Route_to_Market__c'=>'Direct','CWS_Store_Bill_To_Id__c' => acctLst[0].Id,'CWS_Master__c' => false}, true);
          
       Map<String, Object> QuoteFields=new Map<String, Object>{
            'CWS_Bill_To_Account__c' => acctLst[0].id,
            'SBQQ__Opportunity2__c' => opp.id,
            'CWS_Master__c' => false,
            'SBQQ__Primary__c' => True,
            'SBQQ__Status__c' => 'Accepted',
            'CWS_First_Quote__c' => True,
            'CWS_Sub_Stage__c' => 'Accepted'
        };
            
        SBQQ__Quote__c quote = CWS_UTLDataFactory.createQuote(acctLst[0].id,opp.id,QuoteFields, true);
    }

    @isTest static void DistyStamping(){
     Test.starttest();
        
        list<Account> accObj = [Select id from Account limit 4];
                   
        List<Id> qIds = new List<Id>();       
        Id qId =[Select id from SBQQ__Quote__c limit 1].Id;
        qIds.add(qId);
        
        //testing parameterised constructor
        CWS_SingleDitributorStampingBatch Disty1 = new CWS_SingleDitributorStampingBatch(qIds);
        
        //testing constructor
         CWS_SingleDitributorStampingBatch Disty2 = new CWS_SingleDitributorStampingBatch();
    
        list<SBQQ__Quote__c> Qlist = [Select id, SBQQ__Account__c, SBQQ__Account__r.CWS_Established_Disti_Reseller__c from SBQQ__Quote__c limit 1];
       
        Qlist[0].CWS_Share_with_Bill_To_Account__c = accObj[2].id;
        Qlist[0].SBQQ__ExpirationDate__c = system.today() +1;
        
        update Qlist;
             
        Id batchId = Database.executeBatch(new CWS_SingleDitributorStampingBatch(qIds),50);
    
        Test.stopTest();
    }
}