force-app/main/default/objects/Account/fields/CWS_MRR__c.field-meta.xml
<CustomField>
    <fullName>CWS_MRR__c</fullName>
    <description>Contracted Monthly Recurring Revenue based on active Contracts for which this Account is the Sold To Account. This represents contracted MRR and does not include overages. Contracted MRR will be updated weekly over the weekend.</description>
    <inlineHelpText>Contracted Monthly Recurring Revenue based on active Contracts for which this Account is the Sold To Account. This represents contracted MRR and does not include overages. Contracted MRR will be updated weekly over the weekend.</inlineHelpText>
    <label>Contracted MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/CWS_Multiple_Contract_Currencies__c.field-meta.xml
<CustomField>
    <fullName>CWS_Multiple_Contract_Currencies__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Mark true if there is an associated Contract in a different currency from the Account currency</description>
    <inlineHelpText>Indicates that one or more Contracts associated to this Account has a different currency from the Account currency. To calculate Contracted ARR, all Contracts have been converted to match the Account currency.</inlineHelpText>
    <label>Multiple Contract Currencies</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Contract_ACV__c.field-meta.xml
<CustomField>
    <fullName>CWS_Contract_ACV__c</fullName>
    <description>Contract ACV value which will be a Roll-up of all the subscriptions present within the Contract.</description>
    <label>Contract ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/CWS_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_Status__c</fullName>
    <description>Contract Status
If Cancelled flag = TRUE, then Status = Terminated
If Start date &lt;= Today and End date &gt;= Today, Status = Active
If Start date &gt; Today, then Status = Inactive
If End date &lt; Today and Cancelled Flag is False, then Status = Expired</description>
    <formula>IF(CWS_Cancelled__c=TRUE, &apos;Terminated&apos;,
IF(SBQQ__Evergreen__c=TRUE,
IF(CWS_Master__c=true,IF(CWS_Legacy_Formula_Key__c!=null,&apos;Expired&apos;,IF(StartDate&lt;=TODAY(),&apos;Active&apos;,&apos;Inactive&apos;)),IF(StartDate&lt;=TODAY(),&apos;Active&apos;,&apos;Inactive&apos;)),
IF(AND(StartDate&lt;=TODAY(), EndDate&gt;=TODAY()), &apos;Active&apos;,
IF(StartDate&gt;TODAY(), &apos;Inactive&apos;,
IF(EndDate&lt;TODAY(), &apos;Expired&apos;,&apos;&apos;)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If Cancelled flag = TRUE, then Status = Terminated
If Start date &lt;= Today and End date &gt;= Today, Status = Active
If Start date &gt; Today, then Status = Inactive
If End date &lt; Today and Cancelled Flag is False, then Status = Expired</inlineHelpText>
    <label>Contract Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CWS_AccountMRRCalculationBatch.cls
/*Class Name: CWS_AccountMRRCalculationBatch
*Description: Batch Class to Calculate MRR based on Contract ACV
*Created By: Abhishek
*Created On: 06/24/2020
*Modification Log
*------------------------------------------------------------------------------------------
*Developer              Date            User Story              Description
*------------------------------------------------------------------------------------------
*Abhishek               06/24/2020      BED-5141                Calculate MRR based on Contract ACV
*/
public class CWS_AccountMRRCalculationBatch implements Database.Batchable < sObject >{
    public List<Id> accIds = new List<Id>();
    /* Parameterized cunstructor to run batch for specific Accounts
    */
    Public CWS_AccountMRRCalculationBatch(List<Id> accIds){
        this.accIds = accIds;
    }
    Public CWS_AccountMRRCalculationBatch(){}
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String active = CWS_ConstantClass.PROMOTION_ACTIVE;
        Integer lastNDays = Integer.valueOf(Label.CWS_Account_MRR_Last_N_Days);
        String  query = 'select id,CWS_MRR__c,CWS_Multiple_Contract_Currencies__c,currencyIsoCode, ' ;
                query += ' (Select id,CWS_Status__c,AccountId,CWS_Contract_ACV__c,currencyIsoCode from Contracts where CWS_Status__c =: active AND CWS_Contract_ACV__c !=Null AND CWS_Contract_ACV__c !=0)';// AND LastModifiedDate = LAST_N_DAYS:'+lastNDays;
                query += ' from Account';
                if(accIds.Size()>0){
                    query += ' WHERE Id IN :accIds';
                }
        return Database.getQueryLocator(query);

    }
    public void execute(Database.BatchableContext bc,List<Account> scope) {
        map<String,CurrencyType> convRateMap = new map<String,CurrencyType>();
        decimal convMRR;
        decimal totalMRR;
        boolean multiCurrency=false;
        map<id,Account> cntrAccMap = new map<Id,Account>();
        list<Account> accs = new list<Account>();
        
        try{
            for(CurrencyType convRate : [Select ISOCode, ConversionRate, IsActive from CurrencyType where IsActive = True limit 50]){
                convRateMap.put(convRate.ISOCode,convRate);
            }
            for(Account acc : scope){
                if(acc.contracts.size()>0){
                    totalMRR=0;
                    convMRR=0;
                    for(contract cntr : acc.contracts){
                        // Coverting All Contract ACV in USD
                        convMRR=cntr.CWS_Contract_ACV__c/convRateMap.get(cntr.currencyIsoCode).ConversionRate; 
                        totalMRR= totalMRR+convMRR;
                        //If Contract Currency is diff than Account Currency
                        if(!acc.CWS_Multiple_Contract_Currencies__c && acc.currencyIsoCode != cntr.currencyIsoCode){
                            acc.CWS_Multiple_Contract_Currencies__c=true;
                        }
                    }
                    acc.CWS_MRR__c = (totalMRR/12)*(convRateMap.get(acc.currencyIsoCode).ConversionRate);
                    accs.add(acc);
                }
            }
            if(!accs.isEmpty()){
                system.debug('accs'+accs);
                List<Database.SaveResult> results=Database.update(accs,false);
                CWS_ExceptionHandler.logDMLSaveResults(results, 'CWS_AccountMRRCalculationBatch' , 'BatchJob','Update Account MRR ', null , null );
            }
        }catch(exception ex){
            CWS_ExceptionHandler.logException( ex,'BatchClass' , 'CWS_AccountMRRCalculationBatch' , 'Execute' ,'', null , null ,'update' , null);
        }
    }
    public void finish(Database.BatchableContext bc) {

    }
}