force-app/main/default/objects/Opportunity/fields/CWS_Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>CWS_Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Captures the Bill To Account associated to this Opportunity.</inlineHelpText>
    <label>Bill To (Account)</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>$Source.CWS_Route_to_Market__c</field>
            <operation>equals</operation>
            <value>Channel</value>
        </filterItems>
        <filterItems>
            <field>Account.CWS_Is_Distributor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Bill - To Account)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Bill_To_Contact__c.field-meta.xml
<CustomField>
    <fullName>CWS_Bill_To_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Captures the Bill To Contact for the Opportunity; only the Primary and Primary Billing Contact on the Bill To Account will be selectable.</inlineHelpText>
    <label>Bill To (Contact)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.CWS_Bill_To_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Master__c.field-meta.xml
<CustomField>
    <fullName>CWS_Master__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This indicates that the opportunity will have the legacy model of minimum commitment maintained as $value at Account level. This is not recommended; please contact System Administrator for help.</inlineHelpText>
    <label>Master?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Min_Commit_QR__c.field-meta.xml
<CustomField>
    <fullName>CWS_Min_Commit_QR__c</fullName>
    <inlineHelpText>Captures amount of quota retirement for Min Commit products on this Opportunity.</inlineHelpText>
    <label>CMS – Incremental ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <inlineHelpText>Captures the prospect&apos;s route to market; used for routing to BDR and PSE/SE pools.</inlineHelpText>
    <label>Route to Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Store_Bill_To_Id__c.field-meta.xml
<CustomField>
    <fullName>CWS_Store_Bill_To_Id__c</fullName>
    <inlineHelpText>Captures the Bill To ID for this Opportunity.</inlineHelpText>
    <label>Store Bill To Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Total_ACV__c.field-meta.xml
<CustomField>
    <fullName>CWS_Total_ACV__c</fullName>
    <description>Roll-up of the ACV of the Quote lines.</description>
    <inlineHelpText>Annual Contract Value from Quote</inlineHelpText>
    <label>Non MinCommit Total  ACV</label>
    <summarizedField>OpportunityLineItem.CWS_ACVLine__c</summarizedField>
    <summaryFilterItems>
        <field>OpportunityLineItem.CWS_Min_Commit__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/CWS_OpportunityACVAlertBatch_Test.cls
/*Class Name: CWS_OpportunityACVAlertBatch_Test
*Description: Test class for CWS_OpportunityACVAlertBatch 
*Created By: Nida
*Created On: 25/07/2020

*Modification Log
*--------------------------------------------------------------------------------------------------
*Developer              Date            User Story              Description
*--------------------------------------------------------------------------------------------------
*Nida					25/7/2020	 	BED-5096    		    Test Class for CWS_OpportunityACVAlertBatch
*Ad Victoriam Solutions 02/14/2022      N/A                     Updated test class to reflect query change in main.
*/

@isTest(SeeAllData=false)
public class CWS_OpportunityACVAlertBatch_Test {
    @testSetup static void setupTestData(){
        
        Map<String, Object> accountFieldValues=new Map<String, Object>{
            'currencyIsoCode'=>'EUR'};
                List<Account> acctLst = CWS_UTLDataFactory.createBulkAccounts('Test Account',accountFieldValues , 1, true);
        
        date check = system.TODAY();
        check = check.addDays(1);
        //Creating Manager user
        Map<String, Object> userExtraFields1=new Map<String, Object>{
            'isActive'=>true,                
                'Email' => 'test@gmail.com'               
                };
                    //UserRole portalRole = [Select Id,name From UserRole Limit 1];
        User userObj1 = CWS_UTLDataFactory.createUser('Admin','disty@test1.com','Dist','System Administrator','CEO',
                                                      'disty@test.com.Admin.cw',userExtraFields1,true);
        User managerUser = [SELECT ID,EMAIL FROM User WHERE Profile.Name ='System Administrator' AND ID!=: UserInfo.getUserId() LIMIT 1];        
        User currentUser = [SELECT ID,ManagerId FROM User WHERE ID=:UserInfo.getUserId() LIMIT 1];
        if( managerUser!=null && currentUser.ManagerId ==null ){
            currentUser.ManagerId = managerUser.Id;            
            Update currentUser;
        }
        Map<String, Object> OppFieldValues=new Map<String, Object>{'StageName'=>'Qualification',
            'CloseDate'=>check,
            'CWS_Bill_To_Account__c'=>acctLst[0].Id,
            'CWS_Route_to_Market__c'=>'Direct',
            'CWS_Store_Bill_To_Id__c' => acctLst[0].Id,'CWS_Master__c' => true,
            'CWS_Min_Commit_QR__c' => 30000
            };
                //  List<Opportunity> OppLst = CWS_UTLDataFactory.createBulkOpps(OppFieldValues, 5,true);
                Opportunity opp = CWS_UTLDataFactory.createOpportunity('optyName',acctLst[0].Id,OppFieldValues ,true);
    }
    testMethod static void ACVAlert(){
        Test.startTest();
        Account acctRec = [Select Id,SBQQ__DefaultOpportunity__c from Account];
        
        //Testing Parameterised constructor      
        List<Id> oppIds = new List<Id>();       
        Id oppId =[Select id from opportunity limit 1].Id;
        oppIds.add(oppId);
        CWS_OpportunityACVAlertBatch Acc1 = new CWS_OpportunityACVAlertBatch(oppIds);
        
        //Testing Constructor
        CWS_OpportunityACVAlertBatch Acc2 = new CWS_OpportunityACVAlertBatch();
        
        //Testing QueryLocator
        List<Opportunity> OppLst = [Select id,Amount,CWS_Total_ACV__c,closeDate,owner.Name,Owner.Manager.Name,Owner.email,Owner.Manager.email,CWS_Bill_To_Contact__c,ownerId,Owner.Manager.Id,CWS_Bill_To_Account__c  from opportunity];
        date check = system.TODAY();
        OppLst[0].closeDate = check.addDays(1);
        update OppLst;
        
        Id batchId = Database.executeBatch(Acc1, 50);
        
        Test.stopTest();
    }
}