force-app/main/default/objects/Contact/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <inlineHelpText>Captures the Contact&apos;s route to market; used for routing to BDR and PSE/SE pools.</inlineHelpText>
    <label>Route to Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
                <default>true</default>
                <label>Direct</label>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>CWS_Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Captures the Bill To Account associated to this Opportunity.</inlineHelpText>
    <label>Bill To (Account)</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>$Source.CWS_Route_to_Market__c</field>
            <operation>equals</operation>
            <value>Channel</value>
        </filterItems>
        <filterItems>
            <field>Account.CWS_Is_Distributor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Bill - To Account)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Min_Commit_QR__c.field-meta.xml
<CustomField>
    <fullName>CWS_Min_Commit_QR__c</fullName>
    <inlineHelpText>Captures amount of quota retirement for Min Commit products on this Opportunity.</inlineHelpText>
    <label>CMS – Incremental ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <inlineHelpText>Captures the prospect&apos;s route to market; used for routing to BDR and PSE/SE pools.</inlineHelpText>
    <label>Route to Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Billing_Term__c.field-meta.xml
<CustomField>
    <fullName>CWS_Billing_Term__c</fullName>
    <inlineHelpText>Indicates the applicable billing term for the product</inlineHelpText>
    <label>Billing Term</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Bi-Annual</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Tri-Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Category__c.field-meta.xml
<CustomField>
    <fullName>CWS_Category__c</fullName>
    <inlineHelpText>Indicates the Category of the product</inlineHelpText>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Charge_Model__c.field-meta.xml
<CustomField>
    <fullName>CWS_Charge_Model__c</fullName>
    <description>Depicts Zuora charge Model</description>
    <inlineHelpText>Indicates the Charge Model of the product</inlineHelpText>
    <label>Charge Model</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discount-Fixed Amount</fullName>
            </value>
            <value>
                <fullName>Discount-Percentage</fullName>
            </value>
            <value>
                <fullName>Flat Fee Pricing</fullName>
            </value>
            <value>
                <fullName>Per Unit Pricing</fullName>
            </value>
            <value>
                <fullName>Overage Pricing</fullName>
            </value>
            <value>
                <fullName>Tiered Pricing</fullName>
            </value>
            <value>
                <fullName>Tiered with Overage Pricing</fullName>
            </value>
            <value>
                <fullName>Volume Pricing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Currencies__c.field-meta.xml
<CustomField>
    <fullName>CWS_Currencies__c</fullName>
    <inlineHelpText>Indicates the applicable currencies for the product</inlineHelpText>
    <label>Currencies</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Item_Revenue_Category__c.field-meta.xml
<CustomField>
    <fullName>CWS_Item_Revenue_Category__c</fullName>
    <inlineHelpText>Captures Item Revenue Category for the product. NetSuite uses this value to auto-populate revenue attributes at item level.</inlineHelpText>
    <label>Item Revenue Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>On-Prem Term Assurance</fullName>
            </value>
            <value>
                <fullName>On-Prem Term Manage</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Usage</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Consulting-Services-Evolve-Billing</fullName>
            </value>
            <value>
                <fullName>Consulting-Services</fullName>
            </value>
            <value>
                <fullName>Consulting-Services-Core Services</fullName>
            </value>
            <value>
                <fullName>Consulting-Services-Billing</fullName>
            </value>
            <value>
                <fullName>Consulting-Services-Evolve-Core Services</fullName>
            </value>
            <value>
                <fullName>Consulting-Services-Implementation-Core Services</fullName>
            </value>
            <value>
                <fullName>Consulting-Services-Implementation-Billing</fullName>
            </value>
            <value>
                <fullName>Consulting-Services-Recurring-Core Services</fullName>
            </value>
            <value>
                <fullName>Consulting-Services-Recurring-Billing</fullName>
            </value>
            <value>
                <fullName>Consulting-SaaS-Billing</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Hybrid SaaS-Core Services</fullName>
            </value>
            <value>
                <fullName>Maintenance-Core Services</fullName>
            </value>
            <value>
                <fullName>Maintenance-Billing</fullName>
            </value>
            <value>
                <fullName>Other-Billing</fullName>
            </value>
            <value>
                <fullName>Other-Invent-Core Services</fullName>
            </value>
            <value>
                <fullName>Other-Invent-Billing</fullName>
            </value>
            <value>
                <fullName>Perpetual</fullName>
            </value>
            <value>
                <fullName>Perpetual-Core Services</fullName>
            </value>
            <value>
                <fullName>SaaS</fullName>
            </value>
            <value>
                <fullName>SaaS-Third Party</fullName>
            </value>
            <value>
                <fullName>SaaS-Core Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_License_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_License_Type__c</fullName>
    <inlineHelpText>Indicates the License Type of the product</inlineHelpText>
    <label>License Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_LicenseType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <inlineHelpText>Indicates the applicable Route to Market for the product</inlineHelpText>
    <label>Route to Market</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Marketplace</fullName>
            </value>
            <value>
                <fullName>Marketplace Only</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_SKU_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_SKU_Type__c</fullName>
    <inlineHelpText>Indicates the SKU Type of the product</inlineHelpText>
    <label>SKU Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_SKU_TYPE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Source__c.field-meta.xml
<CustomField>
    <fullName>CWS_Source__c</fullName>
    <description>to differenciate the CT and CW  products</description>
    <inlineHelpText>Indicates if the product is legacy CMS, CW or R1Soft product</inlineHelpText>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CW</fullName>
            </value>
            <value>
                <fullName>CMS</fullName>
            </value>
            <value>
                <fullName>R1Soft</fullName>
            </value>
            <value>
                <fullName>Marketplace</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_Status__c</fullName>
    <inlineHelpText>Indicates the Status of the product</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>CWS_Sub_Category__c</fullName>
    <inlineHelpText>Indicates the Sub Category of the product</inlineHelpText>
    <label>Sub Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Sub_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_UOM__c.field-meta.xml
<CustomField>
    <fullName>CWS_UOM__c</fullName>
    <inlineHelpText>Indicates Unit of Measure for the product</inlineHelpText>
    <label>Unit of Measure</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_UOM_valueset</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/SBQQ__SubscriptionPricing__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionPricing__c</fullName>
    <description>Type of pricing to use for this subscription. &quot;None&quot; means this product is not a subscription.</description>
    <inlineHelpText>Indicates if it is fixed pricing or percentage of total pricing</inlineHelpText>
    <label>Subscription Pricing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Price</fullName>
            </value>
            <value>
                <fullName>Percent Of Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Term length of this subscription. Only applicable if the product is a subscription.</description>
    <inlineHelpText>Indicates the term (in months) for which the price has been listed for the product</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CWS_AttachmentTriggerHelper_Test.cls
/*Class Name: CWS_AttachmentTriggerHelper_Test
*Description: test Class for CWS_AttachmentTriggerHelper
*Created By: Nida
*Created On: 08/13/2020
*Modification Log
*------------------------------------------------------------------------------------------
*Developer              Date            User Story              Description
*------------------------------------------------------------------------------------------
*Naresh                08/13/2020           BED-6236             
*/
@isTest(SeeAllData=false)
public class CWS_AttachmentTriggerHelper_Test {
    
    @testSetup static void setupTestData(){
        
        //create custom setting data
        CWS_UTLDataFactory.insertTriggerSwitch(new List<String>{'Attachment trigger'});  
        
        Map<String, Object> accountFieldValues=new Map<String, Object>{
            'currencyIsoCode'=>'EUR'};
                List<Account> acctLst = CWS_UTLDataFactory.createBulkAccounts('Test Account',accountFieldValues , 1, true);
        
     /*   Map<String, Object> contactFieldValues=new Map<String, Object>{
            'FirstName'=>'test',
                'LastName' => 'contact',
                'AccountId' => acctLst[0].Id,
                'MailingCountry' => 'United States'};
                    List<Contact> contactLst = CWS_UTLDataFactory.createBulkContacts('Test','Contact',acctLst[0].Id,contactFieldValues , 2, true);
        
        Map<String, Object> userFieldValues=new Map<String, Object>{};
                    List<User> userLst = CWS_UTLDataFactory.createBulkUsers('TUser','testuser@test.com','user','System Administrator','CEO','testagr@test.com', userFieldValues,1,true);
        */
        // Create Opportunity
        Map<String, Object> opportunityFields=new Map<String, Object>{
            'CWS_Route_to_Market__c'=>'Direct', 'CloseDate'=> Date.today(),'CWS_Bill_To_Account__c'=> acctLst[0].Id,
            'Type'=>'New','CurrencyIsoCode'=>'USD','CWS_Min_Commit_QR__c'=> 20000
        };
        Opportunity opty=CWS_UTLDataFactory.createOpportunity('New Business Opty',acctLst[0].Id,opportunityFields,true);
        
        
        //Create Quote record
       Map<String, Object> quoteFields=new Map<String,Object>{
             'SBQQ__Primary__c'=>true,
             'CWS_Quote_Type__c'=>'New Business',
             'CWS_Bill_to_Account__c'=> acctLst[0].Id,
             'CWS_Route_to_Market__c'=>'Direct',
             'CWS_Renewal_Category__c'=> CWS_ConstantClass.Renewal_Type_OptIn,
             'SBQQ__StartDate__c'=> Date.today(),
             'SBQQ__SubscriptionTerm__c'=>12
                 }; 
        SBQQ__Quote__c quote=CWS_UTLDataFactory.createQuote(acctLst[0].Id,opty.Id, quoteFields, true);

         //Create Product
        Map<String, Object> productFields=new Map<String, Object>{
            'CWS_Category__c'=>'Automate', 'SBQQ__SubscriptionPricing__c'=>'Fixed Price', 'SBQQ__SubscriptionTerm__c'=>12,
            'CWS_Charge_Model__c'=>'Per Unit Pricing', 
      		'CWS_License_Type__c'=>'SaaS', 
      		'CWS_Route_to_Market__c'=>'Direct',
              	'CWS_Source__c' => CWS_ConstantClass.PRODUCT_SOURCE_CMS,
      'CWS_SKU_Type__c'=>'Package', 
      'CWS_UOM__c'=>'Each', 
      'CWS_Sub_Category__c'=>'License', 
      'CWS_Currencies__c'=>'USD;CAD;AUD;EUR;GBP', 
      'CWS_Status__c'=>'Active', 
      'CWS_Billing_Term__c'=>'Monthly', 
      'CWS_Item_Revenue_Category__c'=>'Saas-Billing', 
      'CWS_Renewal_Type__c'=>'Opt-out', 
      'CWS_Product_Line__c'=>'None' ,
      'SBQQ__BillingType__c'=>'Advance',
      'SBQQ__PricingMethod__c'=>'List',
      'Description'=>'Testing',
      'CWS_Description__c'=>'Test1232132'	  
              };
                  
        Product2 product=CWS_UTLDataFactory.createProduct('TestProduct1', 'SKU123',productFields,true);
       
        
        
        ContentVersion TestCon = new ContentVersion();
      TestCon.Title = 'Custom SOW test class';
      TestCon.ContentUrl = 'https://test.com';
        
      insert TestCon;
        
        ID sId = [select id, ContentDocumentId from ContentVersion limit 1].ContentDocumentId;
   
     
      
      ContentDocumentLink cd = new ContentDocumentLink();
        cd.ContentDocumentId = sId;
        cd.LinkedEntityId = quote.id;//TestCon.ContentDocumentId;
        insert cd;
        
       ContentDocumentLink cd2 = new ContentDocumentLink();
        cd2.ContentDocumentId = sId;
        cd2.LinkedEntityId = product.id;//TestCon.ContentDocumentId;
        insert cd2;
    }
    @isTest
  static void testAdditionalDocument(){
      Test.StartTest();
      
       list<SBQQ__Quote__c> lstQt=[select id from SBQQ__Quote__c limit 1];
      Set<Id> contentDocumentIdSet =new Set<ID>();     
      
      ContentVersion Att1 = [select id, ContentDocumentId, Title from ContentVersion limit 1];
   
       Map<Id,ContentVersion> Att= new Map<Id,ContentVersion>();
      Att.put(lstQt[0].id,Att1);
      
      If(Att1.ContentDocumentId != null){
            contentDocumentIdSet.add(Att1.ContentDocumentId);
      }  
      
      List<ContentDocumentLink> cd = [select id, ContentDocumentId,  LinkedEntityId , ShareType from ContentDocumentLink WHERE ContentDocumentId IN:contentDocumentIdSet limit 2];

      /*  	 CWS_AttachmentTriggerHelper AttHelp = new CWS_AttachmentTriggerHelper();
      AttHelp.createAdditionalDocument(Att);*/
            CWS_AttachmentTriggerHelper.createAdditionalDocument(Att);
      Map<Id, SObject> newItems = new Map<Id, SObject>();
      CWS_AttachmentTriggerHandler obj = new CWS_AttachmentTriggerHandler();
      obj.BeforeUpdate(newItems, newItems);
      obj.BeforeDelete(newItems);
      obj.AfterUpdate(newItems, newItems);
      obj.AfterDelete(newItems);
      obj.AfterUndelete(newItems);
      
       Test.StopTest();
  }
    
    
    
}