force-app/main/default/objects/Contact/fields/CWS_Integration_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>CWS_Integration_Sync_Status__c</fullName>
    <description>Field will be used to capture integration status, Will be marked for ready in case of changes in certain fields</description>
    <label>Integration Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready For Sync</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CWS_Primary_Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>CWS_Primary_Billing_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Billing Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CWS_Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>CWS_Primary_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <inlineHelpText>Captures the Contact&apos;s route to market; used for routing to BDR and PSE/SE pools.</inlineHelpText>
    <label>Route to Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
                <default>true</default>
                <label>Direct</label>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Bill_To_Account__c.field-meta.xml
<CustomField>
    <fullName>CWS_Bill_To_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Captures the Bill To Account associated to this Opportunity.</inlineHelpText>
    <label>Bill To (Account)</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>$Source.CWS_Route_to_Market__c</field>
            <operation>equals</operation>
            <value>Channel</value>
        </filterItems>
        <filterItems>
            <field>Account.CWS_Is_Distributor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Bill - To Account)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Bill_To_Contact__c.field-meta.xml
<CustomField>
    <fullName>CWS_Bill_To_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Captures the Bill To Contact for the Opportunity; only the Primary and Primary Billing Contact on the Bill To Account will be selectable.</inlineHelpText>
    <label>Bill To (Contact)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.CWS_Bill_To_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <inlineHelpText>Captures the prospect&apos;s route to market; used for routing to BDR and PSE/SE pools.</inlineHelpText>
    <label>Route to Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/CWS_Commission_Only__c.field-meta.xml
<CustomField>
    <fullName>CWS_Commission_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Commission Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/CWS_License_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_License_Type__c</fullName>
    <label>License Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/CWS_SKU_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_SKU_Type__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.CWS_SKU_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SKU Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Category__c.field-meta.xml
<CustomField>
    <fullName>CWS_Category__c</fullName>
    <inlineHelpText>Indicates the Category of the product</inlineHelpText>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_EF_Attribute__c.field-meta.xml
<CustomField>
    <fullName>CWS_EF_Attribute__c</fullName>
    <inlineHelpText>Indicates the Product Type that is used to derive Disti Factor and Economic Factor value at quote lines</inlineHelpText>
    <label>EF Attribute</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_EF_Attribute</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_License_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_License_Type__c</fullName>
    <inlineHelpText>Indicates the License Type of the product</inlineHelpText>
    <label>License Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_LicenseType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_Route_to_Market__c.field-meta.xml
<CustomField>
    <fullName>CWS_Route_to_Market__c</fullName>
    <inlineHelpText>Indicates the applicable Route to Market for the product</inlineHelpText>
    <label>Route to Market</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
            </value>
            <value>
                <fullName>Marketplace</fullName>
            </value>
            <value>
                <fullName>Marketplace Only</fullName>
            </value>
            <value>
                <fullName>IIT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/CWS_SKU_Type__c.field-meta.xml
<CustomField>
    <fullName>CWS_SKU_Type__c</fullName>
    <inlineHelpText>Indicates the SKU Type of the product</inlineHelpText>
    <label>SKU Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CWS_SKU_TYPE</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Term length of this subscription. Only applicable if the product is a subscription.</description>
    <inlineHelpText>Indicates the term (in months) for which the price has been listed for the product</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CWS_OpportunityLineItemHelperTest.cls
/*Class Name: CWS_OpportunityLineItemHelperTest
*Description: Test Class for CWS_OpportunityLineItemHelperTest
*Created By: Aditya
*Created On: 5/22/2020
*/
@isTest
private class CWS_OpportunityLineItemHelperTest {

    @testSetup static void createTestData() {
        //create custom setting data
        CWS_UTLDataFactory.insertTriggerSwitch(new List<String>{'OpportunityLineItem'}); 
        // TO DO: implement unit test
        Map<String, Object> soldtoaccountFieldValues=new Map<String, Object>{
            'BillingCountry'=>'United States',
            'BillingCountryCode'=>'US',
            'currencyIsoCode'=>'USD'
            };
        Account acc =CWS_UTLDataFactory.createAccount('TestAccount', soldtoaccountFieldValues,true);
        
        //Creating Contact for the Account
        Map<String, Object> mapConFieldValues = new Map<String, Object>{
            'CWS_Primary_Billing_Contact__c' => true,
            'CWS_Primary_Contact__c' => true,
            'CWS_Integration_Sync_Status__c' => CWS_ConstantClass.INT_STATUS_SYNCED,
            'Email'=>'test@test.com',
            'MailingCountry'=>'United States'
        };
        Contact con = CWS_UTLDataFactory.createContact('TestFirstName','TestLastName',acc.Id,mapConFieldValues,true);
        //String id = CWS_ConstantClass.Opportunity_CommissionOnly;
        Map<String, Object> opportunityFields=new Map<String, Object>{
            'CWS_Route_to_Market__c'=>'Direct', 
            'CloseDate'=> Date.today(),
            'CWS_Bill_To_Account__c'=> acc.Id,
            'Type'=>'Commission Only',
            'CurrencyIsoCode'=>'USD',
            'CWS_Bill_To_Contact__c'=>con.id,
            'RecordTypeId'=>CWS_ConstantClass.Opportunity_CommissionOnly
            };
        Opportunity opp = CWs_UTLDataFactory.createOpportunity('Test Opp',acc.Id, opportunityFields, true);
        
        Pricebook2 standardPricebook = new Pricebook2(Id = Test.getStandardPricebookId(), IsActive = true);
        Pricebook2 ConnectwisePricebook = new Pricebook2(Name= CWS_ConstantClass.CONNECTWISE_PRICEBOOK, ISActive = true);
        if(ConnectwisePricebook!=null){
            insert ConnectwisePricebook;
        }
        Map<String,Object> additionalFields = new Map<String, Object>();
        Product2 prod = CWS_UTLDataFactory.createProduct('Dummy Product', 'TRDF', additionalFields, True);
        prod.CWS_Category__c = 'Automate';
        prod.CWS_EF_Attribute__c = 'Service';
        prod.SBQQ__SubscriptionTerm__c = 12;
        prod.CWS_SKU_Type__c = 'Products';
        prod.CWS_License_Type__c = 'Saas';
        prod.IsActive = true;
        if(prod!=null){
           upsert prod; 
        }
        List<String> currencyCode = new List<String>{'USD'};
        List<Pricebookentry> pbeList = CWS_UTLDataFactory.createPBEList(standardPricebook.ID, prod.Id, 100 ,currencyCode);
        List<Pricebookentry> pbeList1 = CWS_UTLDataFactory.createPBEList(ConnectwisePricebook.ID, prod.Id, 100 ,currencyCode);
        pbeList.addAll(pbeList1);
        if(pbeList.size()>0){
            insert pbeList;
        }
    }
    
    @isTest public static void testMethod1(){
        Test.startTest();
         List<Opportunity> oppList = [Select id from Opportunity];
         List<Product2> prodList = [Select id,CWS_SKU_Type__c,CWS_License_Type__c from Product2];
         List<PriceBookEntry> pbeList = [Select id from PriceBookEntry];
         OpportunityLineItem oppProd = new OpportunityLineItem();
         oppProd.OpportunityId = oppList[0].Id;
         oppProd.Quantity = 1;
         oppProd.Product2Id = prodList[0].Id;
         oppProd.PricebookEntryId = pbeList[0].Id;
         oppProd.CWS_Commission_Only__c = true;
         //oppProd.CWS_Subscription_Number__c = 12;
         //oppProd.CWS_SKU_Type__c = prodList[0].CWS_SKU_Type__c;
         oppProd.CWS_License_Type__c = prodList[0].CWS_License_Type__c;
         oppProd.TotalPrice = 100;
         if(oppProd!=null){
            insert oppProd;
         }
         oppProd.Quantity = 10;
         oppProd.UnitPrice = 100;
         if(oppProd!=null){
            update oppProd;
         }
         System.assertEquals(oppProd.CWS_Commission_Only__c, True);
        Test.stopTest();
        
         //These methods are directly called because of the reason that the trigger context are not firing on them and
        //if we try to save handler removing these context ot throws compile error as its implementing interface
        CWS_OpportunityLineItemTriggerHandler handler = new CWS_OpportunityLineItemTriggerHandler();
        map<id,OpportunityLineItem> newRecs = new map<id,OpportunityLineItem>();
        handler.AfterInsert(newRecs);
        handler.BeforeDelete(newRecs);
        handler.AfterDelete(newRecs);
        handler.AfterUndelete(newRecs);
        handler.AfterUpdate(newRecs,newRecs);
    }
}